// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"github.com/TeamWarp/warp-go-sdk/internal/apierror"
	"github.com/TeamWarp/warp-go-sdk/shared"
)

type Error = apierror.Error

type Union = shared.Union

const (
	UnionMedical             = shared.UnionMedical
	UnionDental              = shared.UnionDental
	UnionVision              = shared.UnionVision
	UnionLife                = shared.UnionLife
	UnionShortTermDisability = shared.UnionShortTermDisability
	UnionLongTermDisability  = shared.UnionLongTermDisability
	Union401k                = shared.Union401k
	UnionRoth401k            = shared.UnionRoth401k
	Union403b                = shared.Union403b
	UnionRoth403b            = shared.UnionRoth403b
	Union457                 = shared.Union457
	UnionRoth457             = shared.UnionRoth457
	UnionHsa                 = shared.UnionHsa
	UnionFsaMedical          = shared.UnionFsaMedical
	UnionFsaDependentCare    = shared.UnionFsaDependentCare
	UnionTransit             = shared.UnionTransit
	UnionParking             = shared.UnionParking
	UnionAccident            = shared.UnionAccident
	UnionCancer              = shared.UnionCancer
	UnionCriticalIllness     = shared.UnionCriticalIllness
	UnionHospital            = shared.UnionHospital
	UnionMedicalOther        = shared.UnionMedicalOther
	UnionSimpleIra           = shared.UnionSimpleIra
	UnionRothSimpleIra       = shared.UnionRothSimpleIra
	UnionNqdc                = shared.UnionNqdc
	UnionNontaxableFringe    = shared.UnionNontaxableFringe
	UnionPucc                = shared.UnionPucc
	UnionVoluntary           = shared.UnionVoluntary
	UnionPostTax             = shared.UnionPostTax
	UnionOther               = shared.UnionOther
)

type PublicWorkerCompensation = shared.PublicWorkerCompensation

type PublicWorkerCompensationPer = shared.PublicWorkerCompensationPer

const (
	PublicWorkerCompensationPerYear  = shared.PublicWorkerCompensationPerYear
	PublicWorkerCompensationPerMonth = shared.PublicWorkerCompensationPerMonth
	PublicWorkerCompensationPerWeek  = shared.PublicWorkerCompensationPerWeek
	PublicWorkerCompensationPerHour  = shared.PublicWorkerCompensationPerHour
)

type Union2 = shared.Union2

const (
	Union2Infinity  = shared.Union2Infinity
	Union2Infinity2 = shared.Union2Infinity2
	Union2NaN       = shared.Union2NaN
)

type Objects = shared.Objects

type PublicMoneyAmount = shared.PublicMoneyAmount

type EffectHTTPAPIErrorInternalServerErrorEncoded = shared.EffectHTTPAPIErrorInternalServerErrorEncoded

type EffectHTTPAPIErrorInternalServerErrorEncodedTag = shared.EffectHTTPAPIErrorInternalServerErrorEncodedTag

const (
	EffectHTTPAPIErrorInternalServerErrorEncodedTagInternalServerError = shared.EffectHTTPAPIErrorInternalServerErrorEncodedTagInternalServerError
)

type APIKeyUnauthorizedEncoded = shared.APIKeyUnauthorizedEncoded

type APIKeyUnauthorizedEncodedTag = shared.APIKeyUnauthorizedEncodedTag

const (
	APIKeyUnauthorizedEncodedTagAPIKeyUnauthorized = shared.APIKeyUnauthorizedEncodedTagAPIKeyUnauthorized
)

type RateLimitExceededEncoded = shared.RateLimitExceededEncoded

type RateLimitExceededEncodedTag = shared.RateLimitExceededEncodedTag

const (
	RateLimitExceededEncodedTagRateLimitExceeded = shared.RateLimitExceededEncodedTagRateLimitExceeded
)

type MissingRequiredCompanyPermissionsEncoded = shared.MissingRequiredCompanyPermissionsEncoded

type MissingRequiredCompanyPermissionsEncodedRequiredPermission = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermission

type MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScope = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScope

const (
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersProfile            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersProfile
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersGlobalCompensation = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersGlobalCompensation
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersUsCompensation     = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersUsCompensation
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCompliance         = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCompliance
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersPii                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersPii
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersBanking            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersBanking
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersAccess             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersAccess
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependents         = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependents
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependentsPii      = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependentsPii
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCustomFields       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCustomFields
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsGlobal            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsGlobal
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsUs                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsUs
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePaySchedules              = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePaySchedules
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeOffers                    = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeOffers
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDepartments               = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDepartments
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLevels                    = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLevels
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePerformance               = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePerformance
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkplaces                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkplaces
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeOff                   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeOff
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeTracking              = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeTracking
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeExpenses                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeExpenses
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeGeneralLedger             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeGeneralLedger
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBenefits                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBenefits
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTaxCompliance             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTaxCompliance
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeKYB                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeKYB
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeMdm                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeMdm
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLms                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLms
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeAuthorizedUsers           = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeAuthorizedUsers
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBilling                   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBilling
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeSettings                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeSettings
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDeveloper                 = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDeveloper
)

type MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevel = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevel

const (
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelRead   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelRead
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelWrite  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelWrite
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelManage = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelManage
)

type MissingRequiredCompanyPermissionsEncodedTag = shared.MissingRequiredCompanyPermissionsEncodedTag

const (
	MissingRequiredCompanyPermissionsEncodedTagMissingRequiredCompanyPermissions = shared.MissingRequiredCompanyPermissionsEncodedTagMissingRequiredCompanyPermissions
)

type APINotEnabledEncoded = shared.APINotEnabledEncoded

type APINotEnabledEncodedTag = shared.APINotEnabledEncodedTag

const (
	APINotEnabledEncodedTagAPINotEnabled = shared.APINotEnabledEncodedTagAPINotEnabled
)

type Union3 = shared.Union3

type Union4 = shared.Union4

const (
	Union4Text        = shared.Union4Text
	Union4Number      = shared.Union4Number
	Union4Date        = shared.Union4Date
	Union4Boolean     = shared.Union4Boolean
	Union4Currency    = shared.Union4Currency
	Union4Percentage  = shared.Union4Percentage
	Union4Select      = shared.Union4Select
	Union4MultiSelect = shared.Union4MultiSelect
)

type Union5 = shared.Union5

const (
	Union5Active   = shared.Union5Active
	Union5Archived = shared.Union5Archived
)

type Union6 = shared.Union6

const (
	Union6Info         = shared.Union6Info
	Union6Pii          = shared.Union6Pii
	Union6Compensation = shared.Union6Compensation
	Union6Banking      = shared.Union6Banking
	Union6It           = shared.Union6It
	Union6Compliance   = shared.Union6Compliance
)

type Union7 = shared.Union7

const (
	Union7Admins  = shared.Union7Admins
	Union7Manager = shared.Union7Manager
	Union7Worker  = shared.Union7Worker
)

type Union8 = shared.Union8

const (
	Union8Admin  = shared.Union8Admin
	Union8Worker = shared.Union8Worker
)

type CustomFieldOptionAlreadyExistsErrorEncoded = shared.CustomFieldOptionAlreadyExistsErrorEncoded

type CustomFieldOptionAlreadyExistsErrorEncodedTag = shared.CustomFieldOptionAlreadyExistsErrorEncodedTag

const (
	CustomFieldOptionAlreadyExistsErrorEncodedTagCustomFieldOptionAlreadyExistsError = shared.CustomFieldOptionAlreadyExistsErrorEncodedTagCustomFieldOptionAlreadyExistsError
)

type InvalidCustomFieldOperationErrorEncoded = shared.InvalidCustomFieldOperationErrorEncoded

type InvalidCustomFieldOperationErrorEncodedTag = shared.InvalidCustomFieldOperationErrorEncodedTag

const (
	InvalidCustomFieldOperationErrorEncodedTagInvalidCustomFieldOperationError = shared.InvalidCustomFieldOperationErrorEncodedTagInvalidCustomFieldOperationError
)

type Objects3 = shared.Objects3

type Objects3Status = shared.Objects3Status

const (
	Objects3StatusActive   = shared.Objects3StatusActive
	Objects3StatusArchived = shared.Objects3StatusArchived
)

type CustomFieldNotFoundErrorEncoded = shared.CustomFieldNotFoundErrorEncoded

type CustomFieldNotFoundErrorEncodedTag = shared.CustomFieldNotFoundErrorEncodedTag

const (
	CustomFieldNotFoundErrorEncodedTagCustomFieldNotFoundError = shared.CustomFieldNotFoundErrorEncodedTagCustomFieldNotFoundError
)

type CustomFieldOptionNotFoundErrorEncoded = shared.CustomFieldOptionNotFoundErrorEncoded

type CustomFieldOptionNotFoundErrorEncodedTag = shared.CustomFieldOptionNotFoundErrorEncodedTag

const (
	CustomFieldOptionNotFoundErrorEncodedTagCustomFieldOptionNotFoundError = shared.CustomFieldOptionNotFoundErrorEncodedTagCustomFieldOptionNotFoundError
)

type Union12 = shared.Union12

type DepartmentNotFoundEncoded = shared.DepartmentNotFoundEncoded

type DepartmentNotFoundEncodedTag = shared.DepartmentNotFoundEncodedTag

const (
	DepartmentNotFoundEncodedTagDepartmentNotFound = shared.DepartmentNotFoundEncodedTagDepartmentNotFound
)

type Objects5 = shared.Objects5

type Objects5Track = shared.Objects5Track

const (
	Objects5TrackIc        = shared.Objects5TrackIc
	Objects5TrackManager   = shared.Objects5TrackManager
	Objects5TrackExecutive = shared.Objects5TrackExecutive
)

type Union13 = shared.Union13

const (
	Union13Draft    = shared.Union13Draft
	Union13Sent     = shared.Union13Sent
	Union13Accepted = shared.Union13Accepted
	Union13Void     = shared.Union13Void
)

type WorkplaceNotFoundEncoded = shared.WorkplaceNotFoundEncoded

type WorkplaceNotFoundEncodedTag = shared.WorkplaceNotFoundEncodedTag

const (
	WorkplaceNotFoundEncodedTagWorkplaceNotFound = shared.WorkplaceNotFoundEncodedTagWorkplaceNotFound
)

type ManagerNotFoundErrorEncoded = shared.ManagerNotFoundErrorEncoded

type ManagerNotFoundErrorEncodedTag = shared.ManagerNotFoundErrorEncodedTag

const (
	ManagerNotFoundErrorEncodedTagManagerNotFoundError = shared.ManagerNotFoundErrorEncodedTagManagerNotFoundError
)

type OfferNotFoundErrorEncoded = shared.OfferNotFoundErrorEncoded

type OfferNotFoundErrorEncodedTag = shared.OfferNotFoundErrorEncodedTag

const (
	OfferNotFoundErrorEncodedTagOfferNotFoundError = shared.OfferNotFoundErrorEncodedTagOfferNotFoundError
)

type InvalidOfferStatusErrorEncoded = shared.InvalidOfferStatusErrorEncoded

type InvalidOfferStatusErrorEncodedTag = shared.InvalidOfferStatusErrorEncodedTag

const (
	InvalidOfferStatusErrorEncodedTagInvalidOfferStatusError = shared.InvalidOfferStatusErrorEncodedTagInvalidOfferStatusError
)

type PublicPayrollType = shared.PublicPayrollType

const (
	PublicPayrollTypeUs     = shared.PublicPayrollTypeUs
	PublicPayrollTypeGlobal = shared.PublicPayrollTypeGlobal
)

type PublicPayrollSubtype = shared.PublicPayrollSubtype

const (
	PublicPayrollSubtypeRegular       = shared.PublicPayrollSubtypeRegular
	PublicPayrollSubtypeOffCycle      = shared.PublicPayrollSubtypeOffCycle
	PublicPayrollSubtypeBonus         = shared.PublicPayrollSubtypeBonus
	PublicPayrollSubtypeInvoice       = shared.PublicPayrollSubtypeInvoice
	PublicPayrollSubtypeContractor    = shared.PublicPayrollSubtypeContractor
	PublicPayrollSubtypeDismissal     = shared.PublicPayrollSubtypeDismissal
	PublicPayrollSubtypeReimbursement = shared.PublicPayrollSubtypeReimbursement
	PublicPayrollSubtypeManual        = shared.PublicPayrollSubtypeManual
)

type PublicPayrollStatus = shared.PublicPayrollStatus

const (
	PublicPayrollStatusDraft         = shared.PublicPayrollStatusDraft
	PublicPayrollStatusPending       = shared.PublicPayrollStatusPending
	PublicPayrollStatusProcessing    = shared.PublicPayrollStatusProcessing
	PublicPayrollStatusPartiallyPaid = shared.PublicPayrollStatusPartiallyPaid
	PublicPayrollStatusProcessed     = shared.PublicPayrollStatusProcessed
	PublicPayrollStatusFailed        = shared.PublicPayrollStatusFailed
	PublicPayrollStatusVoided        = shared.PublicPayrollStatusVoided
)

type PublicPayFrequency = shared.PublicPayFrequency

const (
	PublicPayFrequencyWeekly      = shared.PublicPayFrequencyWeekly
	PublicPayFrequencyBiweekly    = shared.PublicPayFrequencyBiweekly
	PublicPayFrequencyMonthly     = shared.PublicPayFrequencyMonthly
	PublicPayFrequencySemimonthly = shared.PublicPayFrequencySemimonthly
	PublicPayFrequencyQuarterly   = shared.PublicPayFrequencyQuarterly
	PublicPayFrequencyAnnually    = shared.PublicPayFrequencyAnnually
)

type Union21 = shared.Union21

type PublicPayrollCurrency = shared.PublicPayrollCurrency

const (
	PublicPayrollCurrencyUsd = shared.PublicPayrollCurrencyUsd
	PublicPayrollCurrencyAud = shared.PublicPayrollCurrencyAud
	PublicPayrollCurrencyBgn = shared.PublicPayrollCurrencyBgn
	PublicPayrollCurrencyBrl = shared.PublicPayrollCurrencyBrl
	PublicPayrollCurrencyCad = shared.PublicPayrollCurrencyCad
	PublicPayrollCurrencyChf = shared.PublicPayrollCurrencyChf
	PublicPayrollCurrencyCzk = shared.PublicPayrollCurrencyCzk
	PublicPayrollCurrencyDkk = shared.PublicPayrollCurrencyDkk
	PublicPayrollCurrencyEur = shared.PublicPayrollCurrencyEur
	PublicPayrollCurrencyGbp = shared.PublicPayrollCurrencyGbp
	PublicPayrollCurrencyHkd = shared.PublicPayrollCurrencyHkd
	PublicPayrollCurrencyHuf = shared.PublicPayrollCurrencyHuf
	PublicPayrollCurrencyIdr = shared.PublicPayrollCurrencyIdr
	PublicPayrollCurrencyInr = shared.PublicPayrollCurrencyInr
	PublicPayrollCurrencyJpy = shared.PublicPayrollCurrencyJpy
	PublicPayrollCurrencyMyr = shared.PublicPayrollCurrencyMyr
	PublicPayrollCurrencyNok = shared.PublicPayrollCurrencyNok
	PublicPayrollCurrencyNzd = shared.PublicPayrollCurrencyNzd
	PublicPayrollCurrencyCny = shared.PublicPayrollCurrencyCny
	PublicPayrollCurrencyPln = shared.PublicPayrollCurrencyPln
	PublicPayrollCurrencyRon = shared.PublicPayrollCurrencyRon
	PublicPayrollCurrencyTry = shared.PublicPayrollCurrencyTry
	PublicPayrollCurrencySek = shared.PublicPayrollCurrencySek
	PublicPayrollCurrencySgd = shared.PublicPayrollCurrencySgd
	PublicPayrollCurrencyAed = shared.PublicPayrollCurrencyAed
	PublicPayrollCurrencyArs = shared.PublicPayrollCurrencyArs
	PublicPayrollCurrencyBdt = shared.PublicPayrollCurrencyBdt
	PublicPayrollCurrencyBwp = shared.PublicPayrollCurrencyBwp
	PublicPayrollCurrencyClp = shared.PublicPayrollCurrencyClp
	PublicPayrollCurrencyCop = shared.PublicPayrollCurrencyCop
	PublicPayrollCurrencyCrc = shared.PublicPayrollCurrencyCrc
	PublicPayrollCurrencyEgp = shared.PublicPayrollCurrencyEgp
	PublicPayrollCurrencyFjd = shared.PublicPayrollCurrencyFjd
	PublicPayrollCurrencyGel = shared.PublicPayrollCurrencyGel
	PublicPayrollCurrencyGhs = shared.PublicPayrollCurrencyGhs
	PublicPayrollCurrencyIls = shared.PublicPayrollCurrencyIls
	PublicPayrollCurrencyKes = shared.PublicPayrollCurrencyKes
	PublicPayrollCurrencyKrw = shared.PublicPayrollCurrencyKrw
	PublicPayrollCurrencyLkr = shared.PublicPayrollCurrencyLkr
	PublicPayrollCurrencyMad = shared.PublicPayrollCurrencyMad
	PublicPayrollCurrencyMxn = shared.PublicPayrollCurrencyMxn
	PublicPayrollCurrencyNpr = shared.PublicPayrollCurrencyNpr
	PublicPayrollCurrencyPhp = shared.PublicPayrollCurrencyPhp
	PublicPayrollCurrencyPkr = shared.PublicPayrollCurrencyPkr
	PublicPayrollCurrencyThb = shared.PublicPayrollCurrencyThb
	PublicPayrollCurrencyUah = shared.PublicPayrollCurrencyUah
	PublicPayrollCurrencyUgx = shared.PublicPayrollCurrencyUgx
	PublicPayrollCurrencyUyu = shared.PublicPayrollCurrencyUyu
	PublicPayrollCurrencyVnd = shared.PublicPayrollCurrencyVnd
	PublicPayrollCurrencyZar = shared.PublicPayrollCurrencyZar
	PublicPayrollCurrencyZmw = shared.PublicPayrollCurrencyZmw
	PublicPayrollCurrencyTnd = shared.PublicPayrollCurrencyTnd
	PublicPayrollCurrencyNgn = shared.PublicPayrollCurrencyNgn
	PublicPayrollCurrencyRsd = shared.PublicPayrollCurrencyRsd
	PublicPayrollCurrencyTwd = shared.PublicPayrollCurrencyTwd
	PublicPayrollCurrencyGtq = shared.PublicPayrollCurrencyGtq
	PublicPayrollCurrencyHnl = shared.PublicPayrollCurrencyHnl
	PublicPayrollCurrencyDop = shared.PublicPayrollCurrencyDop
	PublicPayrollCurrencySar = shared.PublicPayrollCurrencySar
	PublicPayrollCurrencyXaf = shared.PublicPayrollCurrencyXaf
	PublicPayrollCurrencyPen = shared.PublicPayrollCurrencyPen
	PublicPayrollCurrencyBob = shared.PublicPayrollCurrencyBob
)

type PublicPayPeriod = shared.PublicPayPeriod

type PublicPaycheckStatus = shared.PublicPaycheckStatus

const (
	PublicPaycheckStatusDraft         = shared.PublicPaycheckStatusDraft
	PublicPaycheckStatusPending       = shared.PublicPaycheckStatusPending
	PublicPaycheckStatusProcessing    = shared.PublicPaycheckStatusProcessing
	PublicPaycheckStatusDebited       = shared.PublicPaycheckStatusDebited
	PublicPaycheckStatusCredited      = shared.PublicPaycheckStatusCredited
	PublicPaycheckStatusPartiallyPaid = shared.PublicPaycheckStatusPartiallyPaid
	PublicPaycheckStatusProcessed     = shared.PublicPaycheckStatusProcessed
	PublicPaycheckStatusFailed        = shared.PublicPaycheckStatusFailed
	PublicPaycheckStatusVoided        = shared.PublicPaycheckStatusVoided
)

type PublicPaycheckPaymentMethod = shared.PublicPaycheckPaymentMethod

const (
	PublicPaycheckPaymentMethodDirectDeposit = shared.PublicPaycheckPaymentMethodDirectDeposit
	PublicPaycheckPaymentMethodManual        = shared.PublicPaycheckPaymentMethodManual
)

type TimeOffPolicyNotFoundEncoded = shared.TimeOffPolicyNotFoundEncoded

type TimeOffPolicyNotFoundEncodedTag = shared.TimeOffPolicyNotFoundEncodedTag

const (
	TimeOffPolicyNotFoundEncodedTagTimeOffPolicyNotFound = shared.TimeOffPolicyNotFoundEncodedTagTimeOffPolicyNotFound
)

type Union24 = shared.Union24

type Union25 = shared.Union25

type Union26 = shared.Union26

const (
	Union26Pending  = shared.Union26Pending
	Union26Approved = shared.Union26Approved
	Union26Denied   = shared.Union26Denied
)

type Union27 = shared.Union27

const (
	Union27Draft       = shared.Union27Draft
	Union27Invited     = shared.Union27Invited
	Union27Onboarding  = shared.Union27Onboarding
	Union27Active      = shared.Union27Active
	Union27Offboarding = shared.Union27Offboarding
	Union27Inactive    = shared.Union27Inactive
)

type Union28 = shared.Union28

const (
	Union28Employee   = shared.Union28Employee
	Union28Contractor = shared.Union28Contractor
)

type Union29 = shared.Union29

type Union30 = shared.Union30

type Union31 = shared.Union31

type Union32 = shared.Union32

type Union33 = shared.Union33

type Union34 = shared.Union34

type WorkerNotFoundErrorEncoded = shared.WorkerNotFoundErrorEncoded

type WorkerNotFoundErrorEncodedTag = shared.WorkerNotFoundErrorEncodedTag

const (
	WorkerNotFoundErrorEncodedTagWorkerNotFoundError = shared.WorkerNotFoundErrorEncodedTagWorkerNotFoundError
)
