// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"github.com/TeamWarp/warp-go-sdk/internal/apierror"
	"github.com/TeamWarp/warp-go-sdk/shared"
)

type Error = apierror.Error

type Union = shared.Union

const (
	UnionUsd = shared.UnionUsd
	UnionAud = shared.UnionAud
	UnionBgn = shared.UnionBgn
	UnionBrl = shared.UnionBrl
	UnionCad = shared.UnionCad
	UnionChf = shared.UnionChf
	UnionCzk = shared.UnionCzk
	UnionDkk = shared.UnionDkk
	UnionEur = shared.UnionEur
	UnionGbp = shared.UnionGbp
	UnionHkd = shared.UnionHkd
	UnionHuf = shared.UnionHuf
	UnionIdr = shared.UnionIdr
	UnionInr = shared.UnionInr
	UnionJpy = shared.UnionJpy
	UnionMyr = shared.UnionMyr
	UnionNok = shared.UnionNok
	UnionNzd = shared.UnionNzd
	UnionCny = shared.UnionCny
	UnionPln = shared.UnionPln
	UnionRon = shared.UnionRon
	UnionTry = shared.UnionTry
	UnionSek = shared.UnionSek
	UnionSgd = shared.UnionSgd
	UnionAed = shared.UnionAed
	UnionArs = shared.UnionArs
	UnionBdt = shared.UnionBdt
	UnionBwp = shared.UnionBwp
	UnionClp = shared.UnionClp
	UnionCop = shared.UnionCop
	UnionCrc = shared.UnionCrc
	UnionEgp = shared.UnionEgp
	UnionFjd = shared.UnionFjd
	UnionGel = shared.UnionGel
	UnionGhs = shared.UnionGhs
	UnionIls = shared.UnionIls
	UnionKes = shared.UnionKes
	UnionKrw = shared.UnionKrw
	UnionLkr = shared.UnionLkr
	UnionMad = shared.UnionMad
	UnionMxn = shared.UnionMxn
	UnionNpr = shared.UnionNpr
	UnionPhp = shared.UnionPhp
	UnionPkr = shared.UnionPkr
	UnionThb = shared.UnionThb
	UnionUah = shared.UnionUah
	UnionUgx = shared.UnionUgx
	UnionUyu = shared.UnionUyu
	UnionVnd = shared.UnionVnd
	UnionZar = shared.UnionZar
	UnionZmw = shared.UnionZmw
	UnionTnd = shared.UnionTnd
	UnionNgn = shared.UnionNgn
	UnionRsd = shared.UnionRsd
	UnionTwd = shared.UnionTwd
	UnionGtq = shared.UnionGtq
	UnionHnl = shared.UnionHnl
	UnionDop = shared.UnionDop
	UnionSar = shared.UnionSar
	UnionXaf = shared.UnionXaf
	UnionPen = shared.UnionPen
)

type PublicWorkerCompensation = shared.PublicWorkerCompensation

type PublicWorkerCompensationPer = shared.PublicWorkerCompensationPer

const (
	PublicWorkerCompensationPerYear  = shared.PublicWorkerCompensationPerYear
	PublicWorkerCompensationPerMonth = shared.PublicWorkerCompensationPerMonth
	PublicWorkerCompensationPerWeek  = shared.PublicWorkerCompensationPerWeek
	PublicWorkerCompensationPerHour  = shared.PublicWorkerCompensationPerHour
)

type PublicMoneyAmount = shared.PublicMoneyAmount

type EffectHTTPAPIErrorInternalServerErrorEncoded = shared.EffectHTTPAPIErrorInternalServerErrorEncoded

type EffectHTTPAPIErrorInternalServerErrorEncodedTag = shared.EffectHTTPAPIErrorInternalServerErrorEncodedTag

const (
	EffectHTTPAPIErrorInternalServerErrorEncodedTagInternalServerError = shared.EffectHTTPAPIErrorInternalServerErrorEncodedTagInternalServerError
)

type APIKeyUnauthorizedEncoded = shared.APIKeyUnauthorizedEncoded

type APIKeyUnauthorizedEncodedTag = shared.APIKeyUnauthorizedEncodedTag

const (
	APIKeyUnauthorizedEncodedTagAPIKeyUnauthorized = shared.APIKeyUnauthorizedEncodedTagAPIKeyUnauthorized
)

type RateLimitExceededEncoded = shared.RateLimitExceededEncoded

type RateLimitExceededEncodedTag = shared.RateLimitExceededEncodedTag

const (
	RateLimitExceededEncodedTagRateLimitExceeded = shared.RateLimitExceededEncodedTagRateLimitExceeded
)

type MissingRequiredCompanyPermissionsEncoded = shared.MissingRequiredCompanyPermissionsEncoded

type MissingRequiredCompanyPermissionsEncodedRequiredPermission = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermission

type MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScope = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScope

const (
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersProfile            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersProfile
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersGlobalCompensation = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersGlobalCompensation
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersUsCompensation     = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersUsCompensation
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCompliance         = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCompliance
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersPii                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersPii
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersBanking            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersBanking
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersAccess             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersAccess
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependents         = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependents
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependentsPii      = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependentsPii
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCustomFields       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCustomFields
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsGlobal            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsGlobal
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsUs                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsUs
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePaySchedules              = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePaySchedules
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeOffers                    = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeOffers
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDepartments               = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDepartments
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLevels                    = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLevels
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkplaces                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkplaces
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeOff                   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeOff
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeTracking              = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeTracking
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeExpenses                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeExpenses
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeGeneralLedger             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeGeneralLedger
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBenefits                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBenefits
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTaxCompliance             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTaxCompliance
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeKYB                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeKYB
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeMdm                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeMdm
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLms                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLms
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeAuthorizedUsers           = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeAuthorizedUsers
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBilling                   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBilling
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeSettings                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeSettings
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDeveloper                 = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDeveloper
)

type MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevel = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevel

const (
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelRead   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelRead
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelWrite  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelWrite
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelManage = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelManage
)

type MissingRequiredCompanyPermissionsEncodedTag = shared.MissingRequiredCompanyPermissionsEncodedTag

const (
	MissingRequiredCompanyPermissionsEncodedTagMissingRequiredCompanyPermissions = shared.MissingRequiredCompanyPermissionsEncodedTagMissingRequiredCompanyPermissions
)

type APINotEnabledEncoded = shared.APINotEnabledEncoded

type APINotEnabledEncodedTag = shared.APINotEnabledEncodedTag

const (
	APINotEnabledEncodedTagAPINotEnabled = shared.APINotEnabledEncodedTagAPINotEnabled
)

type Union2 = shared.Union2

type Union3 = shared.Union3

const (
	Union3Text        = shared.Union3Text
	Union3Number      = shared.Union3Number
	Union3Date        = shared.Union3Date
	Union3Boolean     = shared.Union3Boolean
	Union3Currency    = shared.Union3Currency
	Union3Percentage  = shared.Union3Percentage
	Union3Select      = shared.Union3Select
	Union3MultiSelect = shared.Union3MultiSelect
)

type Union4 = shared.Union4

const (
	Union4Active   = shared.Union4Active
	Union4Archived = shared.Union4Archived
)

type Union5 = shared.Union5

const (
	Union5Info         = shared.Union5Info
	Union5Pii          = shared.Union5Pii
	Union5Compensation = shared.Union5Compensation
	Union5Banking      = shared.Union5Banking
	Union5It           = shared.Union5It
	Union5Compliance   = shared.Union5Compliance
)

type Union6 = shared.Union6

const (
	Union6Admins  = shared.Union6Admins
	Union6Manager = shared.Union6Manager
	Union6Worker  = shared.Union6Worker
)

type Union7 = shared.Union7

const (
	Union7Admin  = shared.Union7Admin
	Union7Worker = shared.Union7Worker
)

type Union8 = shared.Union8

type Objects = shared.Objects

type CustomFieldOptionAlreadyExistsErrorEncoded = shared.CustomFieldOptionAlreadyExistsErrorEncoded

type CustomFieldOptionAlreadyExistsErrorEncodedTag = shared.CustomFieldOptionAlreadyExistsErrorEncodedTag

const (
	CustomFieldOptionAlreadyExistsErrorEncodedTagCustomFieldOptionAlreadyExistsError = shared.CustomFieldOptionAlreadyExistsErrorEncodedTagCustomFieldOptionAlreadyExistsError
)

type InvalidCustomFieldOperationErrorEncoded = shared.InvalidCustomFieldOperationErrorEncoded

type InvalidCustomFieldOperationErrorEncodedTag = shared.InvalidCustomFieldOperationErrorEncodedTag

const (
	InvalidCustomFieldOperationErrorEncodedTagInvalidCustomFieldOperationError = shared.InvalidCustomFieldOperationErrorEncodedTagInvalidCustomFieldOperationError
)

type Objects3 = shared.Objects3

type Objects3Status = shared.Objects3Status

const (
	Objects3StatusActive   = shared.Objects3StatusActive
	Objects3StatusArchived = shared.Objects3StatusArchived
)

type CustomFieldNotFoundErrorEncoded = shared.CustomFieldNotFoundErrorEncoded

type CustomFieldNotFoundErrorEncodedTag = shared.CustomFieldNotFoundErrorEncodedTag

const (
	CustomFieldNotFoundErrorEncodedTagCustomFieldNotFoundError = shared.CustomFieldNotFoundErrorEncodedTagCustomFieldNotFoundError
)

type CustomFieldOptionNotFoundErrorEncoded = shared.CustomFieldOptionNotFoundErrorEncoded

type CustomFieldOptionNotFoundErrorEncodedTag = shared.CustomFieldOptionNotFoundErrorEncodedTag

const (
	CustomFieldOptionNotFoundErrorEncodedTagCustomFieldOptionNotFoundError = shared.CustomFieldOptionNotFoundErrorEncodedTagCustomFieldOptionNotFoundError
)

type DepartmentNotFoundEncoded = shared.DepartmentNotFoundEncoded

type DepartmentNotFoundEncodedTag = shared.DepartmentNotFoundEncodedTag

const (
	DepartmentNotFoundEncodedTagDepartmentNotFound = shared.DepartmentNotFoundEncodedTagDepartmentNotFound
)

type Union12 = shared.Union12

const (
	Union12Draft    = shared.Union12Draft
	Union12Sent     = shared.Union12Sent
	Union12Accepted = shared.Union12Accepted
	Union12Void     = shared.Union12Void
)

type Union13 = shared.Union13

const (
	Union13Employee         = shared.Union13Employee
	Union13UsContractor     = shared.Union13UsContractor
	Union13GlobalContractor = shared.Union13GlobalContractor
)

type Objects5 = shared.Objects5

type Objects5Candidate = shared.Objects5Candidate

type Objects5CandidateContractorDetails = shared.Objects5CandidateContractorDetails

type Objects5Position = shared.Objects5Position

type Objects5PositionCountry = shared.Objects5PositionCountry

const (
	Objects5PositionCountryAd = shared.Objects5PositionCountryAd
	Objects5PositionCountryAe = shared.Objects5PositionCountryAe
	Objects5PositionCountryAf = shared.Objects5PositionCountryAf
	Objects5PositionCountryAg = shared.Objects5PositionCountryAg
	Objects5PositionCountryAI = shared.Objects5PositionCountryAI
	Objects5PositionCountryAl = shared.Objects5PositionCountryAl
	Objects5PositionCountryAm = shared.Objects5PositionCountryAm
	Objects5PositionCountryAo = shared.Objects5PositionCountryAo
	Objects5PositionCountryAq = shared.Objects5PositionCountryAq
	Objects5PositionCountryAr = shared.Objects5PositionCountryAr
	Objects5PositionCountryAs = shared.Objects5PositionCountryAs
	Objects5PositionCountryAt = shared.Objects5PositionCountryAt
	Objects5PositionCountryAu = shared.Objects5PositionCountryAu
	Objects5PositionCountryAw = shared.Objects5PositionCountryAw
	Objects5PositionCountryAx = shared.Objects5PositionCountryAx
	Objects5PositionCountryAz = shared.Objects5PositionCountryAz
	Objects5PositionCountryBa = shared.Objects5PositionCountryBa
	Objects5PositionCountryBb = shared.Objects5PositionCountryBb
	Objects5PositionCountryBd = shared.Objects5PositionCountryBd
	Objects5PositionCountryBe = shared.Objects5PositionCountryBe
	Objects5PositionCountryBf = shared.Objects5PositionCountryBf
	Objects5PositionCountryBg = shared.Objects5PositionCountryBg
	Objects5PositionCountryBh = shared.Objects5PositionCountryBh
	Objects5PositionCountryBi = shared.Objects5PositionCountryBi
	Objects5PositionCountryBj = shared.Objects5PositionCountryBj
	Objects5PositionCountryBl = shared.Objects5PositionCountryBl
	Objects5PositionCountryBm = shared.Objects5PositionCountryBm
	Objects5PositionCountryBn = shared.Objects5PositionCountryBn
	Objects5PositionCountryBo = shared.Objects5PositionCountryBo
	Objects5PositionCountryBq = shared.Objects5PositionCountryBq
	Objects5PositionCountryBr = shared.Objects5PositionCountryBr
	Objects5PositionCountryBs = shared.Objects5PositionCountryBs
	Objects5PositionCountryBt = shared.Objects5PositionCountryBt
	Objects5PositionCountryBv = shared.Objects5PositionCountryBv
	Objects5PositionCountryBw = shared.Objects5PositionCountryBw
	Objects5PositionCountryBy = shared.Objects5PositionCountryBy
	Objects5PositionCountryBz = shared.Objects5PositionCountryBz
	Objects5PositionCountryCa = shared.Objects5PositionCountryCa
	Objects5PositionCountryCc = shared.Objects5PositionCountryCc
	Objects5PositionCountryCd = shared.Objects5PositionCountryCd
	Objects5PositionCountryCf = shared.Objects5PositionCountryCf
	Objects5PositionCountryCg = shared.Objects5PositionCountryCg
	Objects5PositionCountryCh = shared.Objects5PositionCountryCh
	Objects5PositionCountryCi = shared.Objects5PositionCountryCi
	Objects5PositionCountryCk = shared.Objects5PositionCountryCk
	Objects5PositionCountryCl = shared.Objects5PositionCountryCl
	Objects5PositionCountryCm = shared.Objects5PositionCountryCm
	Objects5PositionCountryCn = shared.Objects5PositionCountryCn
	Objects5PositionCountryCo = shared.Objects5PositionCountryCo
	Objects5PositionCountryCr = shared.Objects5PositionCountryCr
	Objects5PositionCountryCu = shared.Objects5PositionCountryCu
	Objects5PositionCountryCv = shared.Objects5PositionCountryCv
	Objects5PositionCountryCw = shared.Objects5PositionCountryCw
	Objects5PositionCountryCx = shared.Objects5PositionCountryCx
	Objects5PositionCountryCy = shared.Objects5PositionCountryCy
	Objects5PositionCountryCz = shared.Objects5PositionCountryCz
	Objects5PositionCountryDe = shared.Objects5PositionCountryDe
	Objects5PositionCountryDj = shared.Objects5PositionCountryDj
	Objects5PositionCountryDk = shared.Objects5PositionCountryDk
	Objects5PositionCountryDm = shared.Objects5PositionCountryDm
	Objects5PositionCountryDo = shared.Objects5PositionCountryDo
	Objects5PositionCountryDz = shared.Objects5PositionCountryDz
	Objects5PositionCountryEc = shared.Objects5PositionCountryEc
	Objects5PositionCountryEe = shared.Objects5PositionCountryEe
	Objects5PositionCountryEg = shared.Objects5PositionCountryEg
	Objects5PositionCountryEh = shared.Objects5PositionCountryEh
	Objects5PositionCountryEr = shared.Objects5PositionCountryEr
	Objects5PositionCountryEs = shared.Objects5PositionCountryEs
	Objects5PositionCountryEt = shared.Objects5PositionCountryEt
	Objects5PositionCountryFi = shared.Objects5PositionCountryFi
	Objects5PositionCountryFj = shared.Objects5PositionCountryFj
	Objects5PositionCountryFk = shared.Objects5PositionCountryFk
	Objects5PositionCountryFm = shared.Objects5PositionCountryFm
	Objects5PositionCountryFo = shared.Objects5PositionCountryFo
	Objects5PositionCountryFr = shared.Objects5PositionCountryFr
	Objects5PositionCountryGa = shared.Objects5PositionCountryGa
	Objects5PositionCountryGB = shared.Objects5PositionCountryGB
	Objects5PositionCountryGd = shared.Objects5PositionCountryGd
	Objects5PositionCountryGe = shared.Objects5PositionCountryGe
	Objects5PositionCountryGf = shared.Objects5PositionCountryGf
	Objects5PositionCountryGg = shared.Objects5PositionCountryGg
	Objects5PositionCountryGh = shared.Objects5PositionCountryGh
	Objects5PositionCountryGi = shared.Objects5PositionCountryGi
	Objects5PositionCountryGl = shared.Objects5PositionCountryGl
	Objects5PositionCountryGm = shared.Objects5PositionCountryGm
	Objects5PositionCountryGn = shared.Objects5PositionCountryGn
	Objects5PositionCountryGp = shared.Objects5PositionCountryGp
	Objects5PositionCountryGq = shared.Objects5PositionCountryGq
	Objects5PositionCountryGr = shared.Objects5PositionCountryGr
	Objects5PositionCountryGs = shared.Objects5PositionCountryGs
	Objects5PositionCountryGt = shared.Objects5PositionCountryGt
	Objects5PositionCountryGu = shared.Objects5PositionCountryGu
	Objects5PositionCountryGw = shared.Objects5PositionCountryGw
	Objects5PositionCountryGy = shared.Objects5PositionCountryGy
	Objects5PositionCountryHk = shared.Objects5PositionCountryHk
	Objects5PositionCountryHm = shared.Objects5PositionCountryHm
	Objects5PositionCountryHn = shared.Objects5PositionCountryHn
	Objects5PositionCountryHr = shared.Objects5PositionCountryHr
	Objects5PositionCountryHt = shared.Objects5PositionCountryHt
	Objects5PositionCountryHu = shared.Objects5PositionCountryHu
	Objects5PositionCountryID = shared.Objects5PositionCountryID
	Objects5PositionCountryIe = shared.Objects5PositionCountryIe
	Objects5PositionCountryIl = shared.Objects5PositionCountryIl
	Objects5PositionCountryIm = shared.Objects5PositionCountryIm
	Objects5PositionCountryIn = shared.Objects5PositionCountryIn
	Objects5PositionCountryIo = shared.Objects5PositionCountryIo
	Objects5PositionCountryIq = shared.Objects5PositionCountryIq
	Objects5PositionCountryIr = shared.Objects5PositionCountryIr
	Objects5PositionCountryIs = shared.Objects5PositionCountryIs
	Objects5PositionCountryIt = shared.Objects5PositionCountryIt
	Objects5PositionCountryJe = shared.Objects5PositionCountryJe
	Objects5PositionCountryJm = shared.Objects5PositionCountryJm
	Objects5PositionCountryJo = shared.Objects5PositionCountryJo
	Objects5PositionCountryJp = shared.Objects5PositionCountryJp
	Objects5PositionCountryKe = shared.Objects5PositionCountryKe
	Objects5PositionCountryKg = shared.Objects5PositionCountryKg
	Objects5PositionCountryKh = shared.Objects5PositionCountryKh
	Objects5PositionCountryKi = shared.Objects5PositionCountryKi
	Objects5PositionCountryKm = shared.Objects5PositionCountryKm
	Objects5PositionCountryKn = shared.Objects5PositionCountryKn
	Objects5PositionCountryKp = shared.Objects5PositionCountryKp
	Objects5PositionCountryKr = shared.Objects5PositionCountryKr
	Objects5PositionCountryKw = shared.Objects5PositionCountryKw
	Objects5PositionCountryKy = shared.Objects5PositionCountryKy
	Objects5PositionCountryKz = shared.Objects5PositionCountryKz
	Objects5PositionCountryLa = shared.Objects5PositionCountryLa
	Objects5PositionCountryLb = shared.Objects5PositionCountryLb
	Objects5PositionCountryLc = shared.Objects5PositionCountryLc
	Objects5PositionCountryLi = shared.Objects5PositionCountryLi
	Objects5PositionCountryLk = shared.Objects5PositionCountryLk
	Objects5PositionCountryLr = shared.Objects5PositionCountryLr
	Objects5PositionCountryLs = shared.Objects5PositionCountryLs
	Objects5PositionCountryLt = shared.Objects5PositionCountryLt
	Objects5PositionCountryLu = shared.Objects5PositionCountryLu
	Objects5PositionCountryLv = shared.Objects5PositionCountryLv
	Objects5PositionCountryLy = shared.Objects5PositionCountryLy
	Objects5PositionCountryMa = shared.Objects5PositionCountryMa
	Objects5PositionCountryMc = shared.Objects5PositionCountryMc
	Objects5PositionCountryMd = shared.Objects5PositionCountryMd
	Objects5PositionCountryMe = shared.Objects5PositionCountryMe
	Objects5PositionCountryMf = shared.Objects5PositionCountryMf
	Objects5PositionCountryMg = shared.Objects5PositionCountryMg
	Objects5PositionCountryMh = shared.Objects5PositionCountryMh
	Objects5PositionCountryMk = shared.Objects5PositionCountryMk
	Objects5PositionCountryMl = shared.Objects5PositionCountryMl
	Objects5PositionCountryMm = shared.Objects5PositionCountryMm
	Objects5PositionCountryMn = shared.Objects5PositionCountryMn
	Objects5PositionCountryMo = shared.Objects5PositionCountryMo
	Objects5PositionCountryMp = shared.Objects5PositionCountryMp
	Objects5PositionCountryMq = shared.Objects5PositionCountryMq
	Objects5PositionCountryMr = shared.Objects5PositionCountryMr
	Objects5PositionCountryMs = shared.Objects5PositionCountryMs
	Objects5PositionCountryMt = shared.Objects5PositionCountryMt
	Objects5PositionCountryMu = shared.Objects5PositionCountryMu
	Objects5PositionCountryMv = shared.Objects5PositionCountryMv
	Objects5PositionCountryMw = shared.Objects5PositionCountryMw
	Objects5PositionCountryMx = shared.Objects5PositionCountryMx
	Objects5PositionCountryMy = shared.Objects5PositionCountryMy
	Objects5PositionCountryMz = shared.Objects5PositionCountryMz
	Objects5PositionCountryNa = shared.Objects5PositionCountryNa
	Objects5PositionCountryNc = shared.Objects5PositionCountryNc
	Objects5PositionCountryNe = shared.Objects5PositionCountryNe
	Objects5PositionCountryNf = shared.Objects5PositionCountryNf
	Objects5PositionCountryNg = shared.Objects5PositionCountryNg
	Objects5PositionCountryNi = shared.Objects5PositionCountryNi
	Objects5PositionCountryNl = shared.Objects5PositionCountryNl
	Objects5PositionCountryNo = shared.Objects5PositionCountryNo
	Objects5PositionCountryNp = shared.Objects5PositionCountryNp
	Objects5PositionCountryNr = shared.Objects5PositionCountryNr
	Objects5PositionCountryNu = shared.Objects5PositionCountryNu
	Objects5PositionCountryNz = shared.Objects5PositionCountryNz
	Objects5PositionCountryOm = shared.Objects5PositionCountryOm
	Objects5PositionCountryPa = shared.Objects5PositionCountryPa
	Objects5PositionCountryPe = shared.Objects5PositionCountryPe
	Objects5PositionCountryPf = shared.Objects5PositionCountryPf
	Objects5PositionCountryPg = shared.Objects5PositionCountryPg
	Objects5PositionCountryPh = shared.Objects5PositionCountryPh
	Objects5PositionCountryPk = shared.Objects5PositionCountryPk
	Objects5PositionCountryPl = shared.Objects5PositionCountryPl
	Objects5PositionCountryPm = shared.Objects5PositionCountryPm
	Objects5PositionCountryPn = shared.Objects5PositionCountryPn
	Objects5PositionCountryPr = shared.Objects5PositionCountryPr
	Objects5PositionCountryPs = shared.Objects5PositionCountryPs
	Objects5PositionCountryPt = shared.Objects5PositionCountryPt
	Objects5PositionCountryPw = shared.Objects5PositionCountryPw
	Objects5PositionCountryPy = shared.Objects5PositionCountryPy
	Objects5PositionCountryQa = shared.Objects5PositionCountryQa
	Objects5PositionCountryRe = shared.Objects5PositionCountryRe
	Objects5PositionCountryRo = shared.Objects5PositionCountryRo
	Objects5PositionCountryRs = shared.Objects5PositionCountryRs
	Objects5PositionCountryRu = shared.Objects5PositionCountryRu
	Objects5PositionCountryRw = shared.Objects5PositionCountryRw
	Objects5PositionCountrySa = shared.Objects5PositionCountrySa
	Objects5PositionCountrySb = shared.Objects5PositionCountrySb
	Objects5PositionCountrySc = shared.Objects5PositionCountrySc
	Objects5PositionCountrySd = shared.Objects5PositionCountrySd
	Objects5PositionCountrySe = shared.Objects5PositionCountrySe
	Objects5PositionCountrySg = shared.Objects5PositionCountrySg
	Objects5PositionCountrySh = shared.Objects5PositionCountrySh
	Objects5PositionCountrySi = shared.Objects5PositionCountrySi
	Objects5PositionCountrySj = shared.Objects5PositionCountrySj
	Objects5PositionCountrySk = shared.Objects5PositionCountrySk
	Objects5PositionCountrySl = shared.Objects5PositionCountrySl
	Objects5PositionCountrySm = shared.Objects5PositionCountrySm
	Objects5PositionCountrySn = shared.Objects5PositionCountrySn
	Objects5PositionCountrySo = shared.Objects5PositionCountrySo
	Objects5PositionCountrySr = shared.Objects5PositionCountrySr
	Objects5PositionCountrySS = shared.Objects5PositionCountrySS
	Objects5PositionCountrySt = shared.Objects5PositionCountrySt
	Objects5PositionCountrySv = shared.Objects5PositionCountrySv
	Objects5PositionCountrySx = shared.Objects5PositionCountrySx
	Objects5PositionCountrySy = shared.Objects5PositionCountrySy
	Objects5PositionCountrySz = shared.Objects5PositionCountrySz
	Objects5PositionCountryTc = shared.Objects5PositionCountryTc
	Objects5PositionCountryTd = shared.Objects5PositionCountryTd
	Objects5PositionCountryTf = shared.Objects5PositionCountryTf
	Objects5PositionCountryTg = shared.Objects5PositionCountryTg
	Objects5PositionCountryTh = shared.Objects5PositionCountryTh
	Objects5PositionCountryTj = shared.Objects5PositionCountryTj
	Objects5PositionCountryTk = shared.Objects5PositionCountryTk
	Objects5PositionCountryTl = shared.Objects5PositionCountryTl
	Objects5PositionCountryTm = shared.Objects5PositionCountryTm
	Objects5PositionCountryTn = shared.Objects5PositionCountryTn
	Objects5PositionCountryTo = shared.Objects5PositionCountryTo
	Objects5PositionCountryTr = shared.Objects5PositionCountryTr
	Objects5PositionCountryTt = shared.Objects5PositionCountryTt
	Objects5PositionCountryTv = shared.Objects5PositionCountryTv
	Objects5PositionCountryTw = shared.Objects5PositionCountryTw
	Objects5PositionCountryTz = shared.Objects5PositionCountryTz
	Objects5PositionCountryUa = shared.Objects5PositionCountryUa
	Objects5PositionCountryUg = shared.Objects5PositionCountryUg
	Objects5PositionCountryUm = shared.Objects5PositionCountryUm
	Objects5PositionCountryUs = shared.Objects5PositionCountryUs
	Objects5PositionCountryUy = shared.Objects5PositionCountryUy
	Objects5PositionCountryUz = shared.Objects5PositionCountryUz
	Objects5PositionCountryVa = shared.Objects5PositionCountryVa
	Objects5PositionCountryVc = shared.Objects5PositionCountryVc
	Objects5PositionCountryVe = shared.Objects5PositionCountryVe
	Objects5PositionCountryVg = shared.Objects5PositionCountryVg
	Objects5PositionCountryVi = shared.Objects5PositionCountryVi
	Objects5PositionCountryVn = shared.Objects5PositionCountryVn
	Objects5PositionCountryVu = shared.Objects5PositionCountryVu
	Objects5PositionCountryWf = shared.Objects5PositionCountryWf
	Objects5PositionCountryWs = shared.Objects5PositionCountryWs
	Objects5PositionCountryXk = shared.Objects5PositionCountryXk
	Objects5PositionCountryYe = shared.Objects5PositionCountryYe
	Objects5PositionCountryYt = shared.Objects5PositionCountryYt
	Objects5PositionCountryZa = shared.Objects5PositionCountryZa
	Objects5PositionCountryZm = shared.Objects5PositionCountryZm
	Objects5PositionCountryZw = shared.Objects5PositionCountryZw
)

type Objects5Department = shared.Objects5Department

type Objects5Workplace = shared.Objects5Workplace

type Objects5Manager = shared.Objects5Manager

type Objects5Compensation = shared.Objects5Compensation

type Objects5CompensationBasePay = shared.Objects5CompensationBasePay

type Objects5CompensationBasePayBasis = shared.Objects5CompensationBasePayBasis

const (
	Objects5CompensationBasePayBasisYear     = shared.Objects5CompensationBasePayBasisYear
	Objects5CompensationBasePayBasisMonth    = shared.Objects5CompensationBasePayBasisMonth
	Objects5CompensationBasePayBasisWeek     = shared.Objects5CompensationBasePayBasisWeek
	Objects5CompensationBasePayBasisHour     = shared.Objects5CompensationBasePayBasisHour
	Objects5CompensationBasePayBasisVariable = shared.Objects5CompensationBasePayBasisVariable
)

type Objects5CompensationBasePayType = shared.Objects5CompensationBasePayType

const (
	Objects5CompensationBasePayTypeFixed      = shared.Objects5CompensationBasePayTypeFixed
	Objects5CompensationBasePayTypePayAsYouGo = shared.Objects5CompensationBasePayTypePayAsYouGo
)

type Objects5CompensationStock = shared.Objects5CompensationStock

type WorkplaceNotFoundEncoded = shared.WorkplaceNotFoundEncoded

type WorkplaceNotFoundEncodedTag = shared.WorkplaceNotFoundEncodedTag

const (
	WorkplaceNotFoundEncodedTagWorkplaceNotFound = shared.WorkplaceNotFoundEncodedTagWorkplaceNotFound
)

type ManagerNotFoundErrorEncoded = shared.ManagerNotFoundErrorEncoded

type ManagerNotFoundErrorEncodedTag = shared.ManagerNotFoundErrorEncodedTag

const (
	ManagerNotFoundErrorEncodedTagManagerNotFoundError = shared.ManagerNotFoundErrorEncodedTagManagerNotFoundError
)

type OfferNotFoundErrorEncoded = shared.OfferNotFoundErrorEncoded

type OfferNotFoundErrorEncodedTag = shared.OfferNotFoundErrorEncodedTag

const (
	OfferNotFoundErrorEncodedTagOfferNotFoundError = shared.OfferNotFoundErrorEncodedTagOfferNotFoundError
)

type InvalidOfferStatusErrorEncoded = shared.InvalidOfferStatusErrorEncoded

type InvalidOfferStatusErrorEncodedTag = shared.InvalidOfferStatusErrorEncodedTag

const (
	InvalidOfferStatusErrorEncodedTagInvalidOfferStatusError = shared.InvalidOfferStatusErrorEncodedTagInvalidOfferStatusError
)

type TimeOffPolicyNotFoundEncoded = shared.TimeOffPolicyNotFoundEncoded

type TimeOffPolicyNotFoundEncodedTag = shared.TimeOffPolicyNotFoundEncodedTag

const (
	TimeOffPolicyNotFoundEncodedTagTimeOffPolicyNotFound = shared.TimeOffPolicyNotFoundEncodedTagTimeOffPolicyNotFound
)

type Union21 = shared.Union21

type Union23 = shared.Union23

const (
	Union23Draft       = shared.Union23Draft
	Union23Invited     = shared.Union23Invited
	Union23Onboarding  = shared.Union23Onboarding
	Union23Active      = shared.Union23Active
	Union23Offboarding = shared.Union23Offboarding
	Union23Inactive    = shared.Union23Inactive
)

type Union24 = shared.Union24

const (
	Union24Employee   = shared.Union24Employee
	Union24Contractor = shared.Union24Contractor
)

type Union26 = shared.Union26

type Union27 = shared.Union27

type Union29 = shared.Union29

type Union30 = shared.Union30

type WorkerNotFoundErrorEncoded = shared.WorkerNotFoundErrorEncoded

type WorkerNotFoundErrorEncodedTag = shared.WorkerNotFoundErrorEncodedTag

const (
	WorkerNotFoundErrorEncodedTagWorkerNotFoundError = shared.WorkerNotFoundErrorEncodedTagWorkerNotFoundError
)

type Union34 = shared.Union34

const (
	Union34Remote = shared.Union34Remote
	Union34Office = shared.Union34Office
)

type Union35 = shared.Union35

const (
	Union35Active   = shared.Union35Active
	Union35Archived = shared.Union35Archived
)
