// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"github.com/TeamWarp/warp-go-sdk/internal/apierror"
	"github.com/TeamWarp/warp-go-sdk/shared"
)

type Error = apierror.Error

type Union = shared.Union

const (
	UnionMedical             = shared.UnionMedical
	UnionDental              = shared.UnionDental
	UnionVision              = shared.UnionVision
	UnionLife                = shared.UnionLife
	UnionShortTermDisability = shared.UnionShortTermDisability
	UnionLongTermDisability  = shared.UnionLongTermDisability
	Union401k                = shared.Union401k
	UnionRoth401k            = shared.UnionRoth401k
	Union403b                = shared.Union403b
	UnionRoth403b            = shared.UnionRoth403b
	Union457                 = shared.Union457
	UnionRoth457             = shared.UnionRoth457
	UnionHsa                 = shared.UnionHsa
	UnionFsaMedical          = shared.UnionFsaMedical
	UnionFsaDependentCare    = shared.UnionFsaDependentCare
	UnionTransit             = shared.UnionTransit
	UnionParking             = shared.UnionParking
	UnionAccident            = shared.UnionAccident
	UnionCancer              = shared.UnionCancer
	UnionCriticalIllness     = shared.UnionCriticalIllness
	UnionHospital            = shared.UnionHospital
	UnionMedicalOther        = shared.UnionMedicalOther
	UnionSimpleIra           = shared.UnionSimpleIra
	UnionRothSimpleIra       = shared.UnionRothSimpleIra
	UnionNqdc                = shared.UnionNqdc
	UnionNontaxableFringe    = shared.UnionNontaxableFringe
	UnionPucc                = shared.UnionPucc
	UnionVoluntary           = shared.UnionVoluntary
	UnionPostTax             = shared.UnionPostTax
	UnionOther               = shared.UnionOther
)

type PublicWorkerCompensation = shared.PublicWorkerCompensation

type PublicWorkerCompensationPer = shared.PublicWorkerCompensationPer

const (
	PublicWorkerCompensationPerYear  = shared.PublicWorkerCompensationPerYear
	PublicWorkerCompensationPerMonth = shared.PublicWorkerCompensationPerMonth
	PublicWorkerCompensationPerWeek  = shared.PublicWorkerCompensationPerWeek
	PublicWorkerCompensationPerHour  = shared.PublicWorkerCompensationPerHour
)

type Objects = shared.Objects

type PublicMoneyAmount = shared.PublicMoneyAmount

type EffectHTTPAPIErrorInternalServerErrorEncoded = shared.EffectHTTPAPIErrorInternalServerErrorEncoded

type EffectHTTPAPIErrorInternalServerErrorEncodedTag = shared.EffectHTTPAPIErrorInternalServerErrorEncodedTag

const (
	EffectHTTPAPIErrorInternalServerErrorEncodedTagInternalServerError = shared.EffectHTTPAPIErrorInternalServerErrorEncodedTagInternalServerError
)

type APIKeyUnauthorizedEncoded = shared.APIKeyUnauthorizedEncoded

type APIKeyUnauthorizedEncodedTag = shared.APIKeyUnauthorizedEncodedTag

const (
	APIKeyUnauthorizedEncodedTagAPIKeyUnauthorized = shared.APIKeyUnauthorizedEncodedTagAPIKeyUnauthorized
)

type RateLimitExceededEncoded = shared.RateLimitExceededEncoded

type RateLimitExceededEncodedTag = shared.RateLimitExceededEncodedTag

const (
	RateLimitExceededEncodedTagRateLimitExceeded = shared.RateLimitExceededEncodedTagRateLimitExceeded
)

type MissingRequiredCompanyPermissionsEncoded = shared.MissingRequiredCompanyPermissionsEncoded

type MissingRequiredCompanyPermissionsEncodedRequiredPermission = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermission

type MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScope = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScope

const (
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersProfile            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersProfile
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersGlobalCompensation = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersGlobalCompensation
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersUsCompensation     = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersUsCompensation
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCompliance         = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCompliance
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersPii                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersPii
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersBanking            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersBanking
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersAccess             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersAccess
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependents         = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependents
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependentsPii      = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersDependentsPii
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCustomFields       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkersCustomFields
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsGlobal            = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsGlobal
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsUs                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePayrollsUs
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePaySchedules              = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopePaySchedules
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeOffers                    = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeOffers
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDepartments               = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDepartments
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLevels                    = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLevels
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkplaces                = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeWorkplaces
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeOff                   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeOff
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeTracking              = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTimeTracking
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeExpenses                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeExpenses
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeGeneralLedger             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeGeneralLedger
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBenefits                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBenefits
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTaxCompliance             = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeTaxCompliance
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeKYB                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeKYB
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeMdm                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeMdm
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLms                       = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeLms
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeAuthorizedUsers           = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeAuthorizedUsers
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBilling                   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeBilling
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeSettings                  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeSettings
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDeveloper                 = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsScopeDeveloper
)

type MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevel = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevel

const (
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelRead   = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelRead
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelWrite  = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelWrite
	MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelManage = shared.MissingRequiredCompanyPermissionsEncodedRequiredPermissionsLevelManage
)

type MissingRequiredCompanyPermissionsEncodedTag = shared.MissingRequiredCompanyPermissionsEncodedTag

const (
	MissingRequiredCompanyPermissionsEncodedTagMissingRequiredCompanyPermissions = shared.MissingRequiredCompanyPermissionsEncodedTagMissingRequiredCompanyPermissions
)

type APINotEnabledEncoded = shared.APINotEnabledEncoded

type APINotEnabledEncodedTag = shared.APINotEnabledEncodedTag

const (
	APINotEnabledEncodedTagAPINotEnabled = shared.APINotEnabledEncodedTagAPINotEnabled
)

type Union2 = shared.Union2

const (
	Union2Infinity  = shared.Union2Infinity
	Union2Infinity2 = shared.Union2Infinity2
	Union2NaN       = shared.Union2NaN
)

type Union3 = shared.Union3

type Union4 = shared.Union4

const (
	Union4Text        = shared.Union4Text
	Union4Number      = shared.Union4Number
	Union4Date        = shared.Union4Date
	Union4Boolean     = shared.Union4Boolean
	Union4Currency    = shared.Union4Currency
	Union4Percentage  = shared.Union4Percentage
	Union4Select      = shared.Union4Select
	Union4MultiSelect = shared.Union4MultiSelect
)

type Union5 = shared.Union5

const (
	Union5Active   = shared.Union5Active
	Union5Archived = shared.Union5Archived
)

type Union6 = shared.Union6

const (
	Union6Info         = shared.Union6Info
	Union6Pii          = shared.Union6Pii
	Union6Compensation = shared.Union6Compensation
	Union6Banking      = shared.Union6Banking
	Union6It           = shared.Union6It
	Union6Compliance   = shared.Union6Compliance
)

type Union7 = shared.Union7

const (
	Union7Admins  = shared.Union7Admins
	Union7Manager = shared.Union7Manager
	Union7Worker  = shared.Union7Worker
)

type Union8 = shared.Union8

const (
	Union8Admin  = shared.Union8Admin
	Union8Worker = shared.Union8Worker
)

type CustomFieldOptionAlreadyExistsErrorEncoded = shared.CustomFieldOptionAlreadyExistsErrorEncoded

type CustomFieldOptionAlreadyExistsErrorEncodedTag = shared.CustomFieldOptionAlreadyExistsErrorEncodedTag

const (
	CustomFieldOptionAlreadyExistsErrorEncodedTagCustomFieldOptionAlreadyExistsError = shared.CustomFieldOptionAlreadyExistsErrorEncodedTagCustomFieldOptionAlreadyExistsError
)

type InvalidCustomFieldOperationErrorEncoded = shared.InvalidCustomFieldOperationErrorEncoded

type InvalidCustomFieldOperationErrorEncodedTag = shared.InvalidCustomFieldOperationErrorEncodedTag

const (
	InvalidCustomFieldOperationErrorEncodedTagInvalidCustomFieldOperationError = shared.InvalidCustomFieldOperationErrorEncodedTagInvalidCustomFieldOperationError
)

type Objects3 = shared.Objects3

type Objects3Status = shared.Objects3Status

const (
	Objects3StatusActive   = shared.Objects3StatusActive
	Objects3StatusArchived = shared.Objects3StatusArchived
)

type CustomFieldNotFoundErrorEncoded = shared.CustomFieldNotFoundErrorEncoded

type CustomFieldNotFoundErrorEncodedTag = shared.CustomFieldNotFoundErrorEncodedTag

const (
	CustomFieldNotFoundErrorEncodedTagCustomFieldNotFoundError = shared.CustomFieldNotFoundErrorEncodedTagCustomFieldNotFoundError
)

type CustomFieldOptionNotFoundErrorEncoded = shared.CustomFieldOptionNotFoundErrorEncoded

type CustomFieldOptionNotFoundErrorEncodedTag = shared.CustomFieldOptionNotFoundErrorEncodedTag

const (
	CustomFieldOptionNotFoundErrorEncodedTagCustomFieldOptionNotFoundError = shared.CustomFieldOptionNotFoundErrorEncodedTagCustomFieldOptionNotFoundError
)

type Union122 = shared.Union122

type Union122Union = shared.Union122Union

type Union122Variant0 = shared.Union122Variant0

type Union122Variant0Type = shared.Union122Variant0Type

const (
	Union122Variant0TypeText = shared.Union122Variant0TypeText
)

type Union122Variant1 = shared.Union122Variant1

type Union122Variant1Type = shared.Union122Variant1Type

const (
	Union122Variant1TypeNumber = shared.Union122Variant1TypeNumber
)

type Union122Variant2 = shared.Union122Variant2

type Union122Variant2Type = shared.Union122Variant2Type

const (
	Union122Variant2TypeDate = shared.Union122Variant2TypeDate
)

type Union122Variant3 = shared.Union122Variant3

type Union122Variant3Type = shared.Union122Variant3Type

const (
	Union122Variant3TypeBoolean = shared.Union122Variant3TypeBoolean
)

type Union122Variant4 = shared.Union122Variant4

type Union122Variant4Type = shared.Union122Variant4Type

const (
	Union122Variant4TypeCurrency = shared.Union122Variant4TypeCurrency
)

type Union122Variant4CurrencyCode = shared.Union122Variant4CurrencyCode

const (
	Union122Variant4CurrencyCodeUsd = shared.Union122Variant4CurrencyCodeUsd
	Union122Variant4CurrencyCodeAud = shared.Union122Variant4CurrencyCodeAud
	Union122Variant4CurrencyCodeBgn = shared.Union122Variant4CurrencyCodeBgn
	Union122Variant4CurrencyCodeBrl = shared.Union122Variant4CurrencyCodeBrl
	Union122Variant4CurrencyCodeCad = shared.Union122Variant4CurrencyCodeCad
	Union122Variant4CurrencyCodeChf = shared.Union122Variant4CurrencyCodeChf
	Union122Variant4CurrencyCodeCzk = shared.Union122Variant4CurrencyCodeCzk
	Union122Variant4CurrencyCodeDkk = shared.Union122Variant4CurrencyCodeDkk
	Union122Variant4CurrencyCodeEur = shared.Union122Variant4CurrencyCodeEur
	Union122Variant4CurrencyCodeGbp = shared.Union122Variant4CurrencyCodeGbp
	Union122Variant4CurrencyCodeHkd = shared.Union122Variant4CurrencyCodeHkd
	Union122Variant4CurrencyCodeHuf = shared.Union122Variant4CurrencyCodeHuf
	Union122Variant4CurrencyCodeIdr = shared.Union122Variant4CurrencyCodeIdr
	Union122Variant4CurrencyCodeInr = shared.Union122Variant4CurrencyCodeInr
	Union122Variant4CurrencyCodeJpy = shared.Union122Variant4CurrencyCodeJpy
	Union122Variant4CurrencyCodeMyr = shared.Union122Variant4CurrencyCodeMyr
	Union122Variant4CurrencyCodeNok = shared.Union122Variant4CurrencyCodeNok
	Union122Variant4CurrencyCodeNzd = shared.Union122Variant4CurrencyCodeNzd
	Union122Variant4CurrencyCodeCny = shared.Union122Variant4CurrencyCodeCny
	Union122Variant4CurrencyCodePln = shared.Union122Variant4CurrencyCodePln
	Union122Variant4CurrencyCodeRon = shared.Union122Variant4CurrencyCodeRon
	Union122Variant4CurrencyCodeTry = shared.Union122Variant4CurrencyCodeTry
	Union122Variant4CurrencyCodeSek = shared.Union122Variant4CurrencyCodeSek
	Union122Variant4CurrencyCodeSgd = shared.Union122Variant4CurrencyCodeSgd
	Union122Variant4CurrencyCodeAed = shared.Union122Variant4CurrencyCodeAed
	Union122Variant4CurrencyCodeArs = shared.Union122Variant4CurrencyCodeArs
	Union122Variant4CurrencyCodeBdt = shared.Union122Variant4CurrencyCodeBdt
	Union122Variant4CurrencyCodeBwp = shared.Union122Variant4CurrencyCodeBwp
	Union122Variant4CurrencyCodeClp = shared.Union122Variant4CurrencyCodeClp
	Union122Variant4CurrencyCodeCop = shared.Union122Variant4CurrencyCodeCop
	Union122Variant4CurrencyCodeCrc = shared.Union122Variant4CurrencyCodeCrc
	Union122Variant4CurrencyCodeEgp = shared.Union122Variant4CurrencyCodeEgp
	Union122Variant4CurrencyCodeFjd = shared.Union122Variant4CurrencyCodeFjd
	Union122Variant4CurrencyCodeGel = shared.Union122Variant4CurrencyCodeGel
	Union122Variant4CurrencyCodeGhs = shared.Union122Variant4CurrencyCodeGhs
	Union122Variant4CurrencyCodeIls = shared.Union122Variant4CurrencyCodeIls
	Union122Variant4CurrencyCodeKes = shared.Union122Variant4CurrencyCodeKes
	Union122Variant4CurrencyCodeKrw = shared.Union122Variant4CurrencyCodeKrw
	Union122Variant4CurrencyCodeLkr = shared.Union122Variant4CurrencyCodeLkr
	Union122Variant4CurrencyCodeMad = shared.Union122Variant4CurrencyCodeMad
	Union122Variant4CurrencyCodeMxn = shared.Union122Variant4CurrencyCodeMxn
	Union122Variant4CurrencyCodeNpr = shared.Union122Variant4CurrencyCodeNpr
	Union122Variant4CurrencyCodePhp = shared.Union122Variant4CurrencyCodePhp
	Union122Variant4CurrencyCodePkr = shared.Union122Variant4CurrencyCodePkr
	Union122Variant4CurrencyCodeThb = shared.Union122Variant4CurrencyCodeThb
	Union122Variant4CurrencyCodeUah = shared.Union122Variant4CurrencyCodeUah
	Union122Variant4CurrencyCodeUgx = shared.Union122Variant4CurrencyCodeUgx
	Union122Variant4CurrencyCodeUyu = shared.Union122Variant4CurrencyCodeUyu
	Union122Variant4CurrencyCodeVnd = shared.Union122Variant4CurrencyCodeVnd
	Union122Variant4CurrencyCodeZar = shared.Union122Variant4CurrencyCodeZar
	Union122Variant4CurrencyCodeZmw = shared.Union122Variant4CurrencyCodeZmw
	Union122Variant4CurrencyCodeTnd = shared.Union122Variant4CurrencyCodeTnd
	Union122Variant4CurrencyCodeNgn = shared.Union122Variant4CurrencyCodeNgn
	Union122Variant4CurrencyCodeRsd = shared.Union122Variant4CurrencyCodeRsd
	Union122Variant4CurrencyCodeTwd = shared.Union122Variant4CurrencyCodeTwd
	Union122Variant4CurrencyCodeGtq = shared.Union122Variant4CurrencyCodeGtq
	Union122Variant4CurrencyCodeHnl = shared.Union122Variant4CurrencyCodeHnl
	Union122Variant4CurrencyCodeDop = shared.Union122Variant4CurrencyCodeDop
	Union122Variant4CurrencyCodeSar = shared.Union122Variant4CurrencyCodeSar
	Union122Variant4CurrencyCodeXaf = shared.Union122Variant4CurrencyCodeXaf
	Union122Variant4CurrencyCodePen = shared.Union122Variant4CurrencyCodePen
)

type Union122Variant5 = shared.Union122Variant5

type Union122Variant5Type = shared.Union122Variant5Type

const (
	Union122Variant5TypePercentage = shared.Union122Variant5TypePercentage
)

type Union122Variant6 = shared.Union122Variant6

type Union122Variant6Type = shared.Union122Variant6Type

const (
	Union122Variant6TypeSelect = shared.Union122Variant6TypeSelect
)

type Union122Variant7 = shared.Union122Variant7

type Union122Variant7Type = shared.Union122Variant7Type

const (
	Union122Variant7TypeMultiSelect = shared.Union122Variant7TypeMultiSelect
)

type Union122Type = shared.Union122Type

const (
	Union122TypeText        = shared.Union122TypeText
	Union122TypeNumber      = shared.Union122TypeNumber
	Union122TypeDate        = shared.Union122TypeDate
	Union122TypeBoolean     = shared.Union122TypeBoolean
	Union122TypeCurrency    = shared.Union122TypeCurrency
	Union122TypePercentage  = shared.Union122TypePercentage
	Union122TypeSelect      = shared.Union122TypeSelect
	Union122TypeMultiSelect = shared.Union122TypeMultiSelect
)

type Union122CurrencyCode = shared.Union122CurrencyCode

const (
	Union122CurrencyCodeUsd = shared.Union122CurrencyCodeUsd
	Union122CurrencyCodeAud = shared.Union122CurrencyCodeAud
	Union122CurrencyCodeBgn = shared.Union122CurrencyCodeBgn
	Union122CurrencyCodeBrl = shared.Union122CurrencyCodeBrl
	Union122CurrencyCodeCad = shared.Union122CurrencyCodeCad
	Union122CurrencyCodeChf = shared.Union122CurrencyCodeChf
	Union122CurrencyCodeCzk = shared.Union122CurrencyCodeCzk
	Union122CurrencyCodeDkk = shared.Union122CurrencyCodeDkk
	Union122CurrencyCodeEur = shared.Union122CurrencyCodeEur
	Union122CurrencyCodeGbp = shared.Union122CurrencyCodeGbp
	Union122CurrencyCodeHkd = shared.Union122CurrencyCodeHkd
	Union122CurrencyCodeHuf = shared.Union122CurrencyCodeHuf
	Union122CurrencyCodeIdr = shared.Union122CurrencyCodeIdr
	Union122CurrencyCodeInr = shared.Union122CurrencyCodeInr
	Union122CurrencyCodeJpy = shared.Union122CurrencyCodeJpy
	Union122CurrencyCodeMyr = shared.Union122CurrencyCodeMyr
	Union122CurrencyCodeNok = shared.Union122CurrencyCodeNok
	Union122CurrencyCodeNzd = shared.Union122CurrencyCodeNzd
	Union122CurrencyCodeCny = shared.Union122CurrencyCodeCny
	Union122CurrencyCodePln = shared.Union122CurrencyCodePln
	Union122CurrencyCodeRon = shared.Union122CurrencyCodeRon
	Union122CurrencyCodeTry = shared.Union122CurrencyCodeTry
	Union122CurrencyCodeSek = shared.Union122CurrencyCodeSek
	Union122CurrencyCodeSgd = shared.Union122CurrencyCodeSgd
	Union122CurrencyCodeAed = shared.Union122CurrencyCodeAed
	Union122CurrencyCodeArs = shared.Union122CurrencyCodeArs
	Union122CurrencyCodeBdt = shared.Union122CurrencyCodeBdt
	Union122CurrencyCodeBwp = shared.Union122CurrencyCodeBwp
	Union122CurrencyCodeClp = shared.Union122CurrencyCodeClp
	Union122CurrencyCodeCop = shared.Union122CurrencyCodeCop
	Union122CurrencyCodeCrc = shared.Union122CurrencyCodeCrc
	Union122CurrencyCodeEgp = shared.Union122CurrencyCodeEgp
	Union122CurrencyCodeFjd = shared.Union122CurrencyCodeFjd
	Union122CurrencyCodeGel = shared.Union122CurrencyCodeGel
	Union122CurrencyCodeGhs = shared.Union122CurrencyCodeGhs
	Union122CurrencyCodeIls = shared.Union122CurrencyCodeIls
	Union122CurrencyCodeKes = shared.Union122CurrencyCodeKes
	Union122CurrencyCodeKrw = shared.Union122CurrencyCodeKrw
	Union122CurrencyCodeLkr = shared.Union122CurrencyCodeLkr
	Union122CurrencyCodeMad = shared.Union122CurrencyCodeMad
	Union122CurrencyCodeMxn = shared.Union122CurrencyCodeMxn
	Union122CurrencyCodeNpr = shared.Union122CurrencyCodeNpr
	Union122CurrencyCodePhp = shared.Union122CurrencyCodePhp
	Union122CurrencyCodePkr = shared.Union122CurrencyCodePkr
	Union122CurrencyCodeThb = shared.Union122CurrencyCodeThb
	Union122CurrencyCodeUah = shared.Union122CurrencyCodeUah
	Union122CurrencyCodeUgx = shared.Union122CurrencyCodeUgx
	Union122CurrencyCodeUyu = shared.Union122CurrencyCodeUyu
	Union122CurrencyCodeVnd = shared.Union122CurrencyCodeVnd
	Union122CurrencyCodeZar = shared.Union122CurrencyCodeZar
	Union122CurrencyCodeZmw = shared.Union122CurrencyCodeZmw
	Union122CurrencyCodeTnd = shared.Union122CurrencyCodeTnd
	Union122CurrencyCodeNgn = shared.Union122CurrencyCodeNgn
	Union122CurrencyCodeRsd = shared.Union122CurrencyCodeRsd
	Union122CurrencyCodeTwd = shared.Union122CurrencyCodeTwd
	Union122CurrencyCodeGtq = shared.Union122CurrencyCodeGtq
	Union122CurrencyCodeHnl = shared.Union122CurrencyCodeHnl
	Union122CurrencyCodeDop = shared.Union122CurrencyCodeDop
	Union122CurrencyCodeSar = shared.Union122CurrencyCodeSar
	Union122CurrencyCodeXaf = shared.Union122CurrencyCodeXaf
	Union122CurrencyCodePen = shared.Union122CurrencyCodePen
)

type Union13 = shared.Union13

type DepartmentNotFoundEncoded = shared.DepartmentNotFoundEncoded

type DepartmentNotFoundEncodedTag = shared.DepartmentNotFoundEncodedTag

const (
	DepartmentNotFoundEncodedTagDepartmentNotFound = shared.DepartmentNotFoundEncodedTagDepartmentNotFound
)

type Objects5 = shared.Objects5

type Objects5Candidate = shared.Objects5Candidate

type Objects5CandidateContractorDetails = shared.Objects5CandidateContractorDetails

type Objects5Position = shared.Objects5Position

type Objects5PositionCountry = shared.Objects5PositionCountry

const (
	Objects5PositionCountryAd = shared.Objects5PositionCountryAd
	Objects5PositionCountryAe = shared.Objects5PositionCountryAe
	Objects5PositionCountryAf = shared.Objects5PositionCountryAf
	Objects5PositionCountryAg = shared.Objects5PositionCountryAg
	Objects5PositionCountryAI = shared.Objects5PositionCountryAI
	Objects5PositionCountryAl = shared.Objects5PositionCountryAl
	Objects5PositionCountryAm = shared.Objects5PositionCountryAm
	Objects5PositionCountryAo = shared.Objects5PositionCountryAo
	Objects5PositionCountryAq = shared.Objects5PositionCountryAq
	Objects5PositionCountryAr = shared.Objects5PositionCountryAr
	Objects5PositionCountryAs = shared.Objects5PositionCountryAs
	Objects5PositionCountryAt = shared.Objects5PositionCountryAt
	Objects5PositionCountryAu = shared.Objects5PositionCountryAu
	Objects5PositionCountryAw = shared.Objects5PositionCountryAw
	Objects5PositionCountryAx = shared.Objects5PositionCountryAx
	Objects5PositionCountryAz = shared.Objects5PositionCountryAz
	Objects5PositionCountryBa = shared.Objects5PositionCountryBa
	Objects5PositionCountryBb = shared.Objects5PositionCountryBb
	Objects5PositionCountryBd = shared.Objects5PositionCountryBd
	Objects5PositionCountryBe = shared.Objects5PositionCountryBe
	Objects5PositionCountryBf = shared.Objects5PositionCountryBf
	Objects5PositionCountryBg = shared.Objects5PositionCountryBg
	Objects5PositionCountryBh = shared.Objects5PositionCountryBh
	Objects5PositionCountryBi = shared.Objects5PositionCountryBi
	Objects5PositionCountryBj = shared.Objects5PositionCountryBj
	Objects5PositionCountryBl = shared.Objects5PositionCountryBl
	Objects5PositionCountryBm = shared.Objects5PositionCountryBm
	Objects5PositionCountryBn = shared.Objects5PositionCountryBn
	Objects5PositionCountryBo = shared.Objects5PositionCountryBo
	Objects5PositionCountryBq = shared.Objects5PositionCountryBq
	Objects5PositionCountryBr = shared.Objects5PositionCountryBr
	Objects5PositionCountryBs = shared.Objects5PositionCountryBs
	Objects5PositionCountryBt = shared.Objects5PositionCountryBt
	Objects5PositionCountryBv = shared.Objects5PositionCountryBv
	Objects5PositionCountryBw = shared.Objects5PositionCountryBw
	Objects5PositionCountryBy = shared.Objects5PositionCountryBy
	Objects5PositionCountryBz = shared.Objects5PositionCountryBz
	Objects5PositionCountryCa = shared.Objects5PositionCountryCa
	Objects5PositionCountryCc = shared.Objects5PositionCountryCc
	Objects5PositionCountryCd = shared.Objects5PositionCountryCd
	Objects5PositionCountryCf = shared.Objects5PositionCountryCf
	Objects5PositionCountryCg = shared.Objects5PositionCountryCg
	Objects5PositionCountryCh = shared.Objects5PositionCountryCh
	Objects5PositionCountryCi = shared.Objects5PositionCountryCi
	Objects5PositionCountryCk = shared.Objects5PositionCountryCk
	Objects5PositionCountryCl = shared.Objects5PositionCountryCl
	Objects5PositionCountryCm = shared.Objects5PositionCountryCm
	Objects5PositionCountryCn = shared.Objects5PositionCountryCn
	Objects5PositionCountryCo = shared.Objects5PositionCountryCo
	Objects5PositionCountryCr = shared.Objects5PositionCountryCr
	Objects5PositionCountryCu = shared.Objects5PositionCountryCu
	Objects5PositionCountryCv = shared.Objects5PositionCountryCv
	Objects5PositionCountryCw = shared.Objects5PositionCountryCw
	Objects5PositionCountryCx = shared.Objects5PositionCountryCx
	Objects5PositionCountryCy = shared.Objects5PositionCountryCy
	Objects5PositionCountryCz = shared.Objects5PositionCountryCz
	Objects5PositionCountryDe = shared.Objects5PositionCountryDe
	Objects5PositionCountryDj = shared.Objects5PositionCountryDj
	Objects5PositionCountryDk = shared.Objects5PositionCountryDk
	Objects5PositionCountryDm = shared.Objects5PositionCountryDm
	Objects5PositionCountryDo = shared.Objects5PositionCountryDo
	Objects5PositionCountryDz = shared.Objects5PositionCountryDz
	Objects5PositionCountryEc = shared.Objects5PositionCountryEc
	Objects5PositionCountryEe = shared.Objects5PositionCountryEe
	Objects5PositionCountryEg = shared.Objects5PositionCountryEg
	Objects5PositionCountryEh = shared.Objects5PositionCountryEh
	Objects5PositionCountryEr = shared.Objects5PositionCountryEr
	Objects5PositionCountryEs = shared.Objects5PositionCountryEs
	Objects5PositionCountryEt = shared.Objects5PositionCountryEt
	Objects5PositionCountryFi = shared.Objects5PositionCountryFi
	Objects5PositionCountryFj = shared.Objects5PositionCountryFj
	Objects5PositionCountryFk = shared.Objects5PositionCountryFk
	Objects5PositionCountryFm = shared.Objects5PositionCountryFm
	Objects5PositionCountryFo = shared.Objects5PositionCountryFo
	Objects5PositionCountryFr = shared.Objects5PositionCountryFr
	Objects5PositionCountryGa = shared.Objects5PositionCountryGa
	Objects5PositionCountryGB = shared.Objects5PositionCountryGB
	Objects5PositionCountryGd = shared.Objects5PositionCountryGd
	Objects5PositionCountryGe = shared.Objects5PositionCountryGe
	Objects5PositionCountryGf = shared.Objects5PositionCountryGf
	Objects5PositionCountryGg = shared.Objects5PositionCountryGg
	Objects5PositionCountryGh = shared.Objects5PositionCountryGh
	Objects5PositionCountryGi = shared.Objects5PositionCountryGi
	Objects5PositionCountryGl = shared.Objects5PositionCountryGl
	Objects5PositionCountryGm = shared.Objects5PositionCountryGm
	Objects5PositionCountryGn = shared.Objects5PositionCountryGn
	Objects5PositionCountryGp = shared.Objects5PositionCountryGp
	Objects5PositionCountryGq = shared.Objects5PositionCountryGq
	Objects5PositionCountryGr = shared.Objects5PositionCountryGr
	Objects5PositionCountryGs = shared.Objects5PositionCountryGs
	Objects5PositionCountryGt = shared.Objects5PositionCountryGt
	Objects5PositionCountryGu = shared.Objects5PositionCountryGu
	Objects5PositionCountryGw = shared.Objects5PositionCountryGw
	Objects5PositionCountryGy = shared.Objects5PositionCountryGy
	Objects5PositionCountryHk = shared.Objects5PositionCountryHk
	Objects5PositionCountryHm = shared.Objects5PositionCountryHm
	Objects5PositionCountryHn = shared.Objects5PositionCountryHn
	Objects5PositionCountryHr = shared.Objects5PositionCountryHr
	Objects5PositionCountryHt = shared.Objects5PositionCountryHt
	Objects5PositionCountryHu = shared.Objects5PositionCountryHu
	Objects5PositionCountryID = shared.Objects5PositionCountryID
	Objects5PositionCountryIe = shared.Objects5PositionCountryIe
	Objects5PositionCountryIl = shared.Objects5PositionCountryIl
	Objects5PositionCountryIm = shared.Objects5PositionCountryIm
	Objects5PositionCountryIn = shared.Objects5PositionCountryIn
	Objects5PositionCountryIo = shared.Objects5PositionCountryIo
	Objects5PositionCountryIq = shared.Objects5PositionCountryIq
	Objects5PositionCountryIr = shared.Objects5PositionCountryIr
	Objects5PositionCountryIs = shared.Objects5PositionCountryIs
	Objects5PositionCountryIt = shared.Objects5PositionCountryIt
	Objects5PositionCountryJe = shared.Objects5PositionCountryJe
	Objects5PositionCountryJm = shared.Objects5PositionCountryJm
	Objects5PositionCountryJo = shared.Objects5PositionCountryJo
	Objects5PositionCountryJp = shared.Objects5PositionCountryJp
	Objects5PositionCountryKe = shared.Objects5PositionCountryKe
	Objects5PositionCountryKg = shared.Objects5PositionCountryKg
	Objects5PositionCountryKh = shared.Objects5PositionCountryKh
	Objects5PositionCountryKi = shared.Objects5PositionCountryKi
	Objects5PositionCountryKm = shared.Objects5PositionCountryKm
	Objects5PositionCountryKn = shared.Objects5PositionCountryKn
	Objects5PositionCountryKp = shared.Objects5PositionCountryKp
	Objects5PositionCountryKr = shared.Objects5PositionCountryKr
	Objects5PositionCountryKw = shared.Objects5PositionCountryKw
	Objects5PositionCountryKy = shared.Objects5PositionCountryKy
	Objects5PositionCountryKz = shared.Objects5PositionCountryKz
	Objects5PositionCountryLa = shared.Objects5PositionCountryLa
	Objects5PositionCountryLb = shared.Objects5PositionCountryLb
	Objects5PositionCountryLc = shared.Objects5PositionCountryLc
	Objects5PositionCountryLi = shared.Objects5PositionCountryLi
	Objects5PositionCountryLk = shared.Objects5PositionCountryLk
	Objects5PositionCountryLr = shared.Objects5PositionCountryLr
	Objects5PositionCountryLs = shared.Objects5PositionCountryLs
	Objects5PositionCountryLt = shared.Objects5PositionCountryLt
	Objects5PositionCountryLu = shared.Objects5PositionCountryLu
	Objects5PositionCountryLv = shared.Objects5PositionCountryLv
	Objects5PositionCountryLy = shared.Objects5PositionCountryLy
	Objects5PositionCountryMa = shared.Objects5PositionCountryMa
	Objects5PositionCountryMc = shared.Objects5PositionCountryMc
	Objects5PositionCountryMd = shared.Objects5PositionCountryMd
	Objects5PositionCountryMe = shared.Objects5PositionCountryMe
	Objects5PositionCountryMf = shared.Objects5PositionCountryMf
	Objects5PositionCountryMg = shared.Objects5PositionCountryMg
	Objects5PositionCountryMh = shared.Objects5PositionCountryMh
	Objects5PositionCountryMk = shared.Objects5PositionCountryMk
	Objects5PositionCountryMl = shared.Objects5PositionCountryMl
	Objects5PositionCountryMm = shared.Objects5PositionCountryMm
	Objects5PositionCountryMn = shared.Objects5PositionCountryMn
	Objects5PositionCountryMo = shared.Objects5PositionCountryMo
	Objects5PositionCountryMp = shared.Objects5PositionCountryMp
	Objects5PositionCountryMq = shared.Objects5PositionCountryMq
	Objects5PositionCountryMr = shared.Objects5PositionCountryMr
	Objects5PositionCountryMs = shared.Objects5PositionCountryMs
	Objects5PositionCountryMt = shared.Objects5PositionCountryMt
	Objects5PositionCountryMu = shared.Objects5PositionCountryMu
	Objects5PositionCountryMv = shared.Objects5PositionCountryMv
	Objects5PositionCountryMw = shared.Objects5PositionCountryMw
	Objects5PositionCountryMx = shared.Objects5PositionCountryMx
	Objects5PositionCountryMy = shared.Objects5PositionCountryMy
	Objects5PositionCountryMz = shared.Objects5PositionCountryMz
	Objects5PositionCountryNa = shared.Objects5PositionCountryNa
	Objects5PositionCountryNc = shared.Objects5PositionCountryNc
	Objects5PositionCountryNe = shared.Objects5PositionCountryNe
	Objects5PositionCountryNf = shared.Objects5PositionCountryNf
	Objects5PositionCountryNg = shared.Objects5PositionCountryNg
	Objects5PositionCountryNi = shared.Objects5PositionCountryNi
	Objects5PositionCountryNl = shared.Objects5PositionCountryNl
	Objects5PositionCountryNo = shared.Objects5PositionCountryNo
	Objects5PositionCountryNp = shared.Objects5PositionCountryNp
	Objects5PositionCountryNr = shared.Objects5PositionCountryNr
	Objects5PositionCountryNu = shared.Objects5PositionCountryNu
	Objects5PositionCountryNz = shared.Objects5PositionCountryNz
	Objects5PositionCountryOm = shared.Objects5PositionCountryOm
	Objects5PositionCountryPa = shared.Objects5PositionCountryPa
	Objects5PositionCountryPe = shared.Objects5PositionCountryPe
	Objects5PositionCountryPf = shared.Objects5PositionCountryPf
	Objects5PositionCountryPg = shared.Objects5PositionCountryPg
	Objects5PositionCountryPh = shared.Objects5PositionCountryPh
	Objects5PositionCountryPk = shared.Objects5PositionCountryPk
	Objects5PositionCountryPl = shared.Objects5PositionCountryPl
	Objects5PositionCountryPm = shared.Objects5PositionCountryPm
	Objects5PositionCountryPn = shared.Objects5PositionCountryPn
	Objects5PositionCountryPr = shared.Objects5PositionCountryPr
	Objects5PositionCountryPs = shared.Objects5PositionCountryPs
	Objects5PositionCountryPt = shared.Objects5PositionCountryPt
	Objects5PositionCountryPw = shared.Objects5PositionCountryPw
	Objects5PositionCountryPy = shared.Objects5PositionCountryPy
	Objects5PositionCountryQa = shared.Objects5PositionCountryQa
	Objects5PositionCountryRe = shared.Objects5PositionCountryRe
	Objects5PositionCountryRo = shared.Objects5PositionCountryRo
	Objects5PositionCountryRs = shared.Objects5PositionCountryRs
	Objects5PositionCountryRu = shared.Objects5PositionCountryRu
	Objects5PositionCountryRw = shared.Objects5PositionCountryRw
	Objects5PositionCountrySa = shared.Objects5PositionCountrySa
	Objects5PositionCountrySb = shared.Objects5PositionCountrySb
	Objects5PositionCountrySc = shared.Objects5PositionCountrySc
	Objects5PositionCountrySd = shared.Objects5PositionCountrySd
	Objects5PositionCountrySe = shared.Objects5PositionCountrySe
	Objects5PositionCountrySg = shared.Objects5PositionCountrySg
	Objects5PositionCountrySh = shared.Objects5PositionCountrySh
	Objects5PositionCountrySi = shared.Objects5PositionCountrySi
	Objects5PositionCountrySj = shared.Objects5PositionCountrySj
	Objects5PositionCountrySk = shared.Objects5PositionCountrySk
	Objects5PositionCountrySl = shared.Objects5PositionCountrySl
	Objects5PositionCountrySm = shared.Objects5PositionCountrySm
	Objects5PositionCountrySn = shared.Objects5PositionCountrySn
	Objects5PositionCountrySo = shared.Objects5PositionCountrySo
	Objects5PositionCountrySr = shared.Objects5PositionCountrySr
	Objects5PositionCountrySS = shared.Objects5PositionCountrySS
	Objects5PositionCountrySt = shared.Objects5PositionCountrySt
	Objects5PositionCountrySv = shared.Objects5PositionCountrySv
	Objects5PositionCountrySx = shared.Objects5PositionCountrySx
	Objects5PositionCountrySy = shared.Objects5PositionCountrySy
	Objects5PositionCountrySz = shared.Objects5PositionCountrySz
	Objects5PositionCountryTc = shared.Objects5PositionCountryTc
	Objects5PositionCountryTd = shared.Objects5PositionCountryTd
	Objects5PositionCountryTf = shared.Objects5PositionCountryTf
	Objects5PositionCountryTg = shared.Objects5PositionCountryTg
	Objects5PositionCountryTh = shared.Objects5PositionCountryTh
	Objects5PositionCountryTj = shared.Objects5PositionCountryTj
	Objects5PositionCountryTk = shared.Objects5PositionCountryTk
	Objects5PositionCountryTl = shared.Objects5PositionCountryTl
	Objects5PositionCountryTm = shared.Objects5PositionCountryTm
	Objects5PositionCountryTn = shared.Objects5PositionCountryTn
	Objects5PositionCountryTo = shared.Objects5PositionCountryTo
	Objects5PositionCountryTr = shared.Objects5PositionCountryTr
	Objects5PositionCountryTt = shared.Objects5PositionCountryTt
	Objects5PositionCountryTv = shared.Objects5PositionCountryTv
	Objects5PositionCountryTw = shared.Objects5PositionCountryTw
	Objects5PositionCountryTz = shared.Objects5PositionCountryTz
	Objects5PositionCountryUa = shared.Objects5PositionCountryUa
	Objects5PositionCountryUg = shared.Objects5PositionCountryUg
	Objects5PositionCountryUm = shared.Objects5PositionCountryUm
	Objects5PositionCountryUs = shared.Objects5PositionCountryUs
	Objects5PositionCountryUy = shared.Objects5PositionCountryUy
	Objects5PositionCountryUz = shared.Objects5PositionCountryUz
	Objects5PositionCountryVa = shared.Objects5PositionCountryVa
	Objects5PositionCountryVc = shared.Objects5PositionCountryVc
	Objects5PositionCountryVe = shared.Objects5PositionCountryVe
	Objects5PositionCountryVg = shared.Objects5PositionCountryVg
	Objects5PositionCountryVi = shared.Objects5PositionCountryVi
	Objects5PositionCountryVn = shared.Objects5PositionCountryVn
	Objects5PositionCountryVu = shared.Objects5PositionCountryVu
	Objects5PositionCountryWf = shared.Objects5PositionCountryWf
	Objects5PositionCountryWs = shared.Objects5PositionCountryWs
	Objects5PositionCountryXk = shared.Objects5PositionCountryXk
	Objects5PositionCountryYe = shared.Objects5PositionCountryYe
	Objects5PositionCountryYt = shared.Objects5PositionCountryYt
	Objects5PositionCountryZa = shared.Objects5PositionCountryZa
	Objects5PositionCountryZm = shared.Objects5PositionCountryZm
	Objects5PositionCountryZw = shared.Objects5PositionCountryZw
)

type Objects5Department = shared.Objects5Department

type Objects5Workplace = shared.Objects5Workplace

type Objects5Manager = shared.Objects5Manager

type Objects5Compensation = shared.Objects5Compensation

type Objects5CompensationBasePay = shared.Objects5CompensationBasePay

type Objects5CompensationBasePayBasis = shared.Objects5CompensationBasePayBasis

const (
	Objects5CompensationBasePayBasisYear     = shared.Objects5CompensationBasePayBasisYear
	Objects5CompensationBasePayBasisMonth    = shared.Objects5CompensationBasePayBasisMonth
	Objects5CompensationBasePayBasisWeek     = shared.Objects5CompensationBasePayBasisWeek
	Objects5CompensationBasePayBasisHour     = shared.Objects5CompensationBasePayBasisHour
	Objects5CompensationBasePayBasisVariable = shared.Objects5CompensationBasePayBasisVariable
)

type Objects5CompensationBasePayType = shared.Objects5CompensationBasePayType

const (
	Objects5CompensationBasePayTypeFixed      = shared.Objects5CompensationBasePayTypeFixed
	Objects5CompensationBasePayTypePayAsYouGo = shared.Objects5CompensationBasePayTypePayAsYouGo
)

type Objects5CompensationStock = shared.Objects5CompensationStock

type Objects5Status = shared.Objects5Status

const (
	Objects5StatusDraft    = shared.Objects5StatusDraft
	Objects5StatusSent     = shared.Objects5StatusSent
	Objects5StatusAccepted = shared.Objects5StatusAccepted
	Objects5StatusVoid     = shared.Objects5StatusVoid
)

type Objects5WorkerType = shared.Objects5WorkerType

const (
	Objects5WorkerTypeEmployee         = shared.Objects5WorkerTypeEmployee
	Objects5WorkerTypeUsContractor     = shared.Objects5WorkerTypeUsContractor
	Objects5WorkerTypeGlobalContractor = shared.Objects5WorkerTypeGlobalContractor
)

type WorkplaceNotFoundEncoded = shared.WorkplaceNotFoundEncoded

type WorkplaceNotFoundEncodedTag = shared.WorkplaceNotFoundEncodedTag

const (
	WorkplaceNotFoundEncodedTagWorkplaceNotFound = shared.WorkplaceNotFoundEncodedTagWorkplaceNotFound
)

type ManagerNotFoundErrorEncoded = shared.ManagerNotFoundErrorEncoded

type ManagerNotFoundErrorEncodedTag = shared.ManagerNotFoundErrorEncodedTag

const (
	ManagerNotFoundErrorEncodedTagManagerNotFoundError = shared.ManagerNotFoundErrorEncodedTagManagerNotFoundError
)

type OfferNotFoundErrorEncoded = shared.OfferNotFoundErrorEncoded

type OfferNotFoundErrorEncodedTag = shared.OfferNotFoundErrorEncodedTag

const (
	OfferNotFoundErrorEncodedTagOfferNotFoundError = shared.OfferNotFoundErrorEncodedTagOfferNotFoundError
)

type InvalidOfferStatusErrorEncoded = shared.InvalidOfferStatusErrorEncoded

type InvalidOfferStatusErrorEncodedTag = shared.InvalidOfferStatusErrorEncodedTag

const (
	InvalidOfferStatusErrorEncodedTagInvalidOfferStatusError = shared.InvalidOfferStatusErrorEncodedTagInvalidOfferStatusError
)

type InvalidOfferStatusErrorEncodedStatus = shared.InvalidOfferStatusErrorEncodedStatus

const (
	InvalidOfferStatusErrorEncodedStatusDraft    = shared.InvalidOfferStatusErrorEncodedStatusDraft
	InvalidOfferStatusErrorEncodedStatusSent     = shared.InvalidOfferStatusErrorEncodedStatusSent
	InvalidOfferStatusErrorEncodedStatusAccepted = shared.InvalidOfferStatusErrorEncodedStatusAccepted
	InvalidOfferStatusErrorEncodedStatusVoid     = shared.InvalidOfferStatusErrorEncodedStatusVoid
)

type PublicPayrollType = shared.PublicPayrollType

const (
	PublicPayrollTypeUs     = shared.PublicPayrollTypeUs
	PublicPayrollTypeGlobal = shared.PublicPayrollTypeGlobal
)

type PublicPayrollSubtype = shared.PublicPayrollSubtype

const (
	PublicPayrollSubtypeRegular       = shared.PublicPayrollSubtypeRegular
	PublicPayrollSubtypeOffCycle      = shared.PublicPayrollSubtypeOffCycle
	PublicPayrollSubtypeBonus         = shared.PublicPayrollSubtypeBonus
	PublicPayrollSubtypeInvoice       = shared.PublicPayrollSubtypeInvoice
	PublicPayrollSubtypeContractor    = shared.PublicPayrollSubtypeContractor
	PublicPayrollSubtypeDismissal     = shared.PublicPayrollSubtypeDismissal
	PublicPayrollSubtypeReimbursement = shared.PublicPayrollSubtypeReimbursement
	PublicPayrollSubtypeManual        = shared.PublicPayrollSubtypeManual
)

type PublicPayrollStatus = shared.PublicPayrollStatus

const (
	PublicPayrollStatusDraft         = shared.PublicPayrollStatusDraft
	PublicPayrollStatusPending       = shared.PublicPayrollStatusPending
	PublicPayrollStatusProcessing    = shared.PublicPayrollStatusProcessing
	PublicPayrollStatusPartiallyPaid = shared.PublicPayrollStatusPartiallyPaid
	PublicPayrollStatusProcessed     = shared.PublicPayrollStatusProcessed
	PublicPayrollStatusFailed        = shared.PublicPayrollStatusFailed
	PublicPayrollStatusVoided        = shared.PublicPayrollStatusVoided
)

type PublicPayFrequency = shared.PublicPayFrequency

const (
	PublicPayFrequencyWeekly      = shared.PublicPayFrequencyWeekly
	PublicPayFrequencyBiweekly    = shared.PublicPayFrequencyBiweekly
	PublicPayFrequencyMonthly     = shared.PublicPayFrequencyMonthly
	PublicPayFrequencySemimonthly = shared.PublicPayFrequencySemimonthly
	PublicPayFrequencyQuarterly   = shared.PublicPayFrequencyQuarterly
	PublicPayFrequencyAnnually    = shared.PublicPayFrequencyAnnually
)

type Union21 = shared.Union21

type PublicPayrollCurrency = shared.PublicPayrollCurrency

const (
	PublicPayrollCurrencyUsd = shared.PublicPayrollCurrencyUsd
	PublicPayrollCurrencyAud = shared.PublicPayrollCurrencyAud
	PublicPayrollCurrencyBgn = shared.PublicPayrollCurrencyBgn
	PublicPayrollCurrencyBrl = shared.PublicPayrollCurrencyBrl
	PublicPayrollCurrencyCad = shared.PublicPayrollCurrencyCad
	PublicPayrollCurrencyChf = shared.PublicPayrollCurrencyChf
	PublicPayrollCurrencyCzk = shared.PublicPayrollCurrencyCzk
	PublicPayrollCurrencyDkk = shared.PublicPayrollCurrencyDkk
	PublicPayrollCurrencyEur = shared.PublicPayrollCurrencyEur
	PublicPayrollCurrencyGbp = shared.PublicPayrollCurrencyGbp
	PublicPayrollCurrencyHkd = shared.PublicPayrollCurrencyHkd
	PublicPayrollCurrencyHuf = shared.PublicPayrollCurrencyHuf
	PublicPayrollCurrencyIdr = shared.PublicPayrollCurrencyIdr
	PublicPayrollCurrencyInr = shared.PublicPayrollCurrencyInr
	PublicPayrollCurrencyJpy = shared.PublicPayrollCurrencyJpy
	PublicPayrollCurrencyMyr = shared.PublicPayrollCurrencyMyr
	PublicPayrollCurrencyNok = shared.PublicPayrollCurrencyNok
	PublicPayrollCurrencyNzd = shared.PublicPayrollCurrencyNzd
	PublicPayrollCurrencyCny = shared.PublicPayrollCurrencyCny
	PublicPayrollCurrencyPln = shared.PublicPayrollCurrencyPln
	PublicPayrollCurrencyRon = shared.PublicPayrollCurrencyRon
	PublicPayrollCurrencyTry = shared.PublicPayrollCurrencyTry
	PublicPayrollCurrencySek = shared.PublicPayrollCurrencySek
	PublicPayrollCurrencySgd = shared.PublicPayrollCurrencySgd
	PublicPayrollCurrencyAed = shared.PublicPayrollCurrencyAed
	PublicPayrollCurrencyArs = shared.PublicPayrollCurrencyArs
	PublicPayrollCurrencyBdt = shared.PublicPayrollCurrencyBdt
	PublicPayrollCurrencyBwp = shared.PublicPayrollCurrencyBwp
	PublicPayrollCurrencyClp = shared.PublicPayrollCurrencyClp
	PublicPayrollCurrencyCop = shared.PublicPayrollCurrencyCop
	PublicPayrollCurrencyCrc = shared.PublicPayrollCurrencyCrc
	PublicPayrollCurrencyEgp = shared.PublicPayrollCurrencyEgp
	PublicPayrollCurrencyFjd = shared.PublicPayrollCurrencyFjd
	PublicPayrollCurrencyGel = shared.PublicPayrollCurrencyGel
	PublicPayrollCurrencyGhs = shared.PublicPayrollCurrencyGhs
	PublicPayrollCurrencyIls = shared.PublicPayrollCurrencyIls
	PublicPayrollCurrencyKes = shared.PublicPayrollCurrencyKes
	PublicPayrollCurrencyKrw = shared.PublicPayrollCurrencyKrw
	PublicPayrollCurrencyLkr = shared.PublicPayrollCurrencyLkr
	PublicPayrollCurrencyMad = shared.PublicPayrollCurrencyMad
	PublicPayrollCurrencyMxn = shared.PublicPayrollCurrencyMxn
	PublicPayrollCurrencyNpr = shared.PublicPayrollCurrencyNpr
	PublicPayrollCurrencyPhp = shared.PublicPayrollCurrencyPhp
	PublicPayrollCurrencyPkr = shared.PublicPayrollCurrencyPkr
	PublicPayrollCurrencyThb = shared.PublicPayrollCurrencyThb
	PublicPayrollCurrencyUah = shared.PublicPayrollCurrencyUah
	PublicPayrollCurrencyUgx = shared.PublicPayrollCurrencyUgx
	PublicPayrollCurrencyUyu = shared.PublicPayrollCurrencyUyu
	PublicPayrollCurrencyVnd = shared.PublicPayrollCurrencyVnd
	PublicPayrollCurrencyZar = shared.PublicPayrollCurrencyZar
	PublicPayrollCurrencyZmw = shared.PublicPayrollCurrencyZmw
	PublicPayrollCurrencyTnd = shared.PublicPayrollCurrencyTnd
	PublicPayrollCurrencyNgn = shared.PublicPayrollCurrencyNgn
	PublicPayrollCurrencyRsd = shared.PublicPayrollCurrencyRsd
	PublicPayrollCurrencyTwd = shared.PublicPayrollCurrencyTwd
	PublicPayrollCurrencyGtq = shared.PublicPayrollCurrencyGtq
	PublicPayrollCurrencyHnl = shared.PublicPayrollCurrencyHnl
	PublicPayrollCurrencyDop = shared.PublicPayrollCurrencyDop
	PublicPayrollCurrencySar = shared.PublicPayrollCurrencySar
	PublicPayrollCurrencyXaf = shared.PublicPayrollCurrencyXaf
	PublicPayrollCurrencyPen = shared.PublicPayrollCurrencyPen
	PublicPayrollCurrencyBob = shared.PublicPayrollCurrencyBob
)

type PublicPayPeriod = shared.PublicPayPeriod

type PublicPaycheckStatus = shared.PublicPaycheckStatus

const (
	PublicPaycheckStatusDraft         = shared.PublicPaycheckStatusDraft
	PublicPaycheckStatusPending       = shared.PublicPaycheckStatusPending
	PublicPaycheckStatusProcessing    = shared.PublicPaycheckStatusProcessing
	PublicPaycheckStatusDebited       = shared.PublicPaycheckStatusDebited
	PublicPaycheckStatusCredited      = shared.PublicPaycheckStatusCredited
	PublicPaycheckStatusPartiallyPaid = shared.PublicPaycheckStatusPartiallyPaid
	PublicPaycheckStatusProcessed     = shared.PublicPaycheckStatusProcessed
	PublicPaycheckStatusFailed        = shared.PublicPaycheckStatusFailed
	PublicPaycheckStatusVoided        = shared.PublicPaycheckStatusVoided
)

type PublicPaycheckPaymentMethod = shared.PublicPaycheckPaymentMethod

const (
	PublicPaycheckPaymentMethodDirectDeposit = shared.PublicPaycheckPaymentMethodDirectDeposit
	PublicPaycheckPaymentMethodManual        = shared.PublicPaycheckPaymentMethodManual
)

type TimeOffPolicyNotFoundEncoded = shared.TimeOffPolicyNotFoundEncoded

type TimeOffPolicyNotFoundEncodedTag = shared.TimeOffPolicyNotFoundEncodedTag

const (
	TimeOffPolicyNotFoundEncodedTagTimeOffPolicyNotFound = shared.TimeOffPolicyNotFoundEncodedTagTimeOffPolicyNotFound
)

type Union24 = shared.Union24

type Union25 = shared.Union25

type Union26 = shared.Union26

const (
	Union26Pending  = shared.Union26Pending
	Union26Approved = shared.Union26Approved
	Union26Denied   = shared.Union26Denied
)

type Union27 = shared.Union27

const (
	Union27Draft       = shared.Union27Draft
	Union27Invited     = shared.Union27Invited
	Union27Onboarding  = shared.Union27Onboarding
	Union27Active      = shared.Union27Active
	Union27Offboarding = shared.Union27Offboarding
	Union27Inactive    = shared.Union27Inactive
)

type Union28 = shared.Union28

const (
	Union28Employee   = shared.Union28Employee
	Union28Contractor = shared.Union28Contractor
)

type Union29 = shared.Union29

type Union30 = shared.Union30

type Union31 = shared.Union31

type Union32 = shared.Union32

type Union33 = shared.Union33

type Union34 = shared.Union34

type WorkerNotFoundErrorEncoded = shared.WorkerNotFoundErrorEncoded

type WorkerNotFoundErrorEncodedTag = shared.WorkerNotFoundErrorEncodedTag

const (
	WorkerNotFoundErrorEncodedTagWorkerNotFoundError = shared.WorkerNotFoundErrorEncodedTagWorkerNotFoundError
)
