// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// BenefitHealthPlanService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewBenefitHealthPlanService] method instead.
type BenefitHealthPlanService struct {
	Options []option.RequestOption
}

// NewBenefitHealthPlanService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewBenefitHealthPlanService(opts ...option.RequestOption) (r *BenefitHealthPlanService) {
	r = &BenefitHealthPlanService{}
	r.Options = opts
	return
}

// List company health plans. Defaults to active plans. A plan whose effectiveEndDate has elapsed is reported and filtered as terminated.
//
// Parameters:
//     ctx: Context for the request.
//     query: BenefitHealthPlanBenefitsListParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *BenefitHealthPlanBenefitsListResponse: Success
//
// Example:
//
//     healthPlan, err := client.Benefits.HealthPlans.BenefitsList(context.Background(), sdk.BenefitHealthPlanBenefitsListParams{
//     	Statuses: sdk.F[[]sdk.BenefitHealthPlanBenefitsListParamsStatus]([]sdk.BenefitHealthPlanBenefitsListParamsStatus{"active"}),
//     })
//     if err != nil {
//     	panic(err)
//     }
//
//     fmt.Println(healthPlan)
func (r *BenefitHealthPlanService) BenefitsList(ctx context.Context, query BenefitHealthPlanBenefitsListParams, opts ...option.RequestOption) (res *BenefitHealthPlanBenefitsListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/benefits/health_plans"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a publicly visible company health plan by id.
//
// Parameters:
//     ctx: Context for the request.
//     id: The tag of a company health plan.
//     opts: Options to apply to this request.
//
// Returns:
//     *BenefitHealthPlanBenefitsGetResponse: A company health plan available through Warp.
//
// Example:
//
//     healthPlan, err := client.Benefits.HealthPlans.BenefitsGet(context.Background(), "chpl_1234")
//     if err != nil {
//     	panic(err)
//     }
//
//     fmt.Println(healthPlan)
func (r *BenefitHealthPlanService) BenefitsGet(ctx context.Context, id string, opts ...option.RequestOption) (res *BenefitHealthPlanBenefitsGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/benefits/health_plans/%s", id)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicHealthPlan struct {
	// The tag of a company health plan.
	ID string `json:"id" api:"required"`
	// The insurance carrier underwriting the health plan.
	Carrier PublicHealthPlanCarrier `json:"carrier" api:"required"`
	// The health coverage type.
	Type PublicHealthPlanType `json:"type" api:"required"`
	// The company-facing plan name.
	Name string `json:"name" api:"required"`
	// The carrier-assigned group number.
	GroupNumber string `json:"groupNumber" api:"required,nullable"`
	// The plan network structure.
	NetworkType PublicHealthPlanNetworkType `json:"networkType" api:"required,nullable"`
	// A date string in the form YYYY-MM-DD
	EffectiveStartDate string `json:"effectiveStartDate" api:"required"`
	EffectiveEndDate string `json:"effectiveEndDate" api:"required,nullable"`
	// The public lifecycle status of a health plan.
	Status PublicHealthPlanStatus `json:"status" api:"required"`
	// a string to be decoded into a Date
	CreatedAt string `json:"createdAt" api:"required"`
	// a string to be decoded into a Date
	UpdatedAt string `json:"updatedAt" api:"required"`
	JSON publicHealthPlanJSON `json:"-"`
}

// publicHealthPlanJSON contains the JSON metadata for the struct [PublicHealthPlan]
type publicHealthPlanJSON struct {
	ID apijson.Field
	Carrier apijson.Field
	Type apijson.Field
	Name apijson.Field
	GroupNumber apijson.Field
	NetworkType apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate apijson.Field
	Status apijson.Field
	CreatedAt apijson.Field
	UpdatedAt apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicHealthPlan) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicHealthPlanJSON) RawJSON() string {
	return r.raw
}

type PublicHealthPlanType string

const (
	PublicHealthPlanTypeMedical PublicHealthPlanType = "medical"
	PublicHealthPlanTypeDental PublicHealthPlanType = "dental"
	PublicHealthPlanTypeVision PublicHealthPlanType = "vision"
	PublicHealthPlanTypeLife PublicHealthPlanType = "life"
	PublicHealthPlanTypeShortTermDisability PublicHealthPlanType = "short_term_disability"
	PublicHealthPlanTypeLongTermDisability PublicHealthPlanType = "long_term_disability"
)

func (r PublicHealthPlanType) IsKnown() bool {
	switch r {
	case PublicHealthPlanTypeMedical, PublicHealthPlanTypeDental, PublicHealthPlanTypeVision, PublicHealthPlanTypeLife, PublicHealthPlanTypeShortTermDisability, PublicHealthPlanTypeLongTermDisability:
		return true
	}
	return false
}

type PublicHealthPlanNetworkType string

const (
	PublicHealthPlanNetworkTypeHmo PublicHealthPlanNetworkType = "hmo"
	PublicHealthPlanNetworkTypePpo PublicHealthPlanNetworkType = "ppo"
	PublicHealthPlanNetworkTypeEpo PublicHealthPlanNetworkType = "epo"
	PublicHealthPlanNetworkTypePos PublicHealthPlanNetworkType = "pos"
	PublicHealthPlanNetworkTypeHdhp PublicHealthPlanNetworkType = "hdhp"
	PublicHealthPlanNetworkTypeIndemnity PublicHealthPlanNetworkType = "indemnity"
)

func (r PublicHealthPlanNetworkType) IsKnown() bool {
	switch r {
	case PublicHealthPlanNetworkTypeHmo, PublicHealthPlanNetworkTypePpo, PublicHealthPlanNetworkTypeEpo, PublicHealthPlanNetworkTypePos, PublicHealthPlanNetworkTypeHdhp, PublicHealthPlanNetworkTypeIndemnity:
		return true
	}
	return false
}

type PublicHealthPlanStatus string

const (
	PublicHealthPlanStatusActive PublicHealthPlanStatus = "active"
	PublicHealthPlanStatusTerminated PublicHealthPlanStatus = "terminated"
)

func (r PublicHealthPlanStatus) IsKnown() bool {
	switch r {
	case PublicHealthPlanStatusActive, PublicHealthPlanStatusTerminated:
		return true
	}
	return false
}

type PublicHealthPlanCarrier struct {
	// The tag of a carrier.
	ID string `json:"id" api:"required"`
	// The carrier name.
	Name string `json:"name" api:"required"`
	JSON publicHealthPlanCarrierJSON `json:"-"`
}

// publicHealthPlanCarrierJSON contains the JSON metadata for the struct [PublicHealthPlanCarrier]
type publicHealthPlanCarrierJSON struct {
	ID apijson.Field
	Name apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicHealthPlanCarrier) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicHealthPlanCarrierJSON) RawJSON() string {
	return r.raw
}

type BenefitHealthPlanBenefitsGetResponse struct {
	// The tag of a company health plan.
	ID string `json:"id" api:"required"`
	// The insurance carrier underwriting the health plan.
	Carrier PublicHealthPlanCarrier `json:"carrier" api:"required"`
	// The health coverage type.
	Type BenefitHealthPlanBenefitsGetResponseType `json:"type" api:"required"`
	// The company-facing plan name.
	Name string `json:"name" api:"required"`
	// The carrier-assigned group number.
	GroupNumber string `json:"groupNumber" api:"required,nullable"`
	// The plan network structure.
	NetworkType BenefitHealthPlanBenefitsGetResponseNetworkType `json:"networkType" api:"required,nullable"`
	// A date string in the form YYYY-MM-DD
	EffectiveStartDate string `json:"effectiveStartDate" api:"required"`
	EffectiveEndDate string `json:"effectiveEndDate" api:"required,nullable"`
	// The public lifecycle status of a health plan.
	Status BenefitHealthPlanBenefitsGetResponseStatus `json:"status" api:"required"`
	// a string to be decoded into a Date
	CreatedAt string `json:"createdAt" api:"required"`
	// a string to be decoded into a Date
	UpdatedAt string `json:"updatedAt" api:"required"`
	JSON benefitHealthPlanBenefitsGetResponseJSON `json:"-"`
}

// benefitHealthPlanBenefitsGetResponseJSON contains the JSON metadata for the struct [BenefitHealthPlanBenefitsGetResponse]
type benefitHealthPlanBenefitsGetResponseJSON struct {
	ID apijson.Field
	Carrier apijson.Field
	Type apijson.Field
	Name apijson.Field
	GroupNumber apijson.Field
	NetworkType apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate apijson.Field
	Status apijson.Field
	CreatedAt apijson.Field
	UpdatedAt apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *BenefitHealthPlanBenefitsGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r benefitHealthPlanBenefitsGetResponseJSON) RawJSON() string {
	return r.raw
}

type BenefitHealthPlanBenefitsGetResponseType string

const (
	BenefitHealthPlanBenefitsGetResponseTypeMedical BenefitHealthPlanBenefitsGetResponseType = "medical"
	BenefitHealthPlanBenefitsGetResponseTypeDental BenefitHealthPlanBenefitsGetResponseType = "dental"
	BenefitHealthPlanBenefitsGetResponseTypeVision BenefitHealthPlanBenefitsGetResponseType = "vision"
	BenefitHealthPlanBenefitsGetResponseTypeLife BenefitHealthPlanBenefitsGetResponseType = "life"
	BenefitHealthPlanBenefitsGetResponseTypeShortTermDisability BenefitHealthPlanBenefitsGetResponseType = "short_term_disability"
	BenefitHealthPlanBenefitsGetResponseTypeLongTermDisability BenefitHealthPlanBenefitsGetResponseType = "long_term_disability"
)

func (r BenefitHealthPlanBenefitsGetResponseType) IsKnown() bool {
	switch r {
	case BenefitHealthPlanBenefitsGetResponseTypeMedical, BenefitHealthPlanBenefitsGetResponseTypeDental, BenefitHealthPlanBenefitsGetResponseTypeVision, BenefitHealthPlanBenefitsGetResponseTypeLife, BenefitHealthPlanBenefitsGetResponseTypeShortTermDisability, BenefitHealthPlanBenefitsGetResponseTypeLongTermDisability:
		return true
	}
	return false
}

type BenefitHealthPlanBenefitsGetResponseNetworkType string

const (
	BenefitHealthPlanBenefitsGetResponseNetworkTypeHmo BenefitHealthPlanBenefitsGetResponseNetworkType = "hmo"
	BenefitHealthPlanBenefitsGetResponseNetworkTypePpo BenefitHealthPlanBenefitsGetResponseNetworkType = "ppo"
	BenefitHealthPlanBenefitsGetResponseNetworkTypeEpo BenefitHealthPlanBenefitsGetResponseNetworkType = "epo"
	BenefitHealthPlanBenefitsGetResponseNetworkTypePos BenefitHealthPlanBenefitsGetResponseNetworkType = "pos"
	BenefitHealthPlanBenefitsGetResponseNetworkTypeHdhp BenefitHealthPlanBenefitsGetResponseNetworkType = "hdhp"
	BenefitHealthPlanBenefitsGetResponseNetworkTypeIndemnity BenefitHealthPlanBenefitsGetResponseNetworkType = "indemnity"
)

func (r BenefitHealthPlanBenefitsGetResponseNetworkType) IsKnown() bool {
	switch r {
	case BenefitHealthPlanBenefitsGetResponseNetworkTypeHmo, BenefitHealthPlanBenefitsGetResponseNetworkTypePpo, BenefitHealthPlanBenefitsGetResponseNetworkTypeEpo, BenefitHealthPlanBenefitsGetResponseNetworkTypePos, BenefitHealthPlanBenefitsGetResponseNetworkTypeHdhp, BenefitHealthPlanBenefitsGetResponseNetworkTypeIndemnity:
		return true
	}
	return false
}

type BenefitHealthPlanBenefitsGetResponseStatus string

const (
	BenefitHealthPlanBenefitsGetResponseStatusActive BenefitHealthPlanBenefitsGetResponseStatus = "active"
	BenefitHealthPlanBenefitsGetResponseStatusTerminated BenefitHealthPlanBenefitsGetResponseStatus = "terminated"
)

func (r BenefitHealthPlanBenefitsGetResponseStatus) IsKnown() bool {
	switch r {
	case BenefitHealthPlanBenefitsGetResponseStatusActive, BenefitHealthPlanBenefitsGetResponseStatusTerminated:
		return true
	}
	return false
}

type BenefitHealthPlanBenefitsListParams struct {
	// The tag of a company health plan.
	AfterID param.Field[string] `query:"afterId"`
	// The tag of a company health plan.
	BeforeID param.Field[string] `query:"beforeId"`
	CarrierIDs param.Field[[]string] `query:"carrierIds"`
	// a number less than or equal to 100
	Limit param.Field[string] `query:"limit"`
	// Statuses to include. Defaults to ["active"]. An elapsed effectiveEndDate is
	// reported and filtered as "terminated".
	Statuses param.Field[[]BenefitHealthPlanBenefitsListParamsStatus] `query:"statuses"`
	Types param.Field[[]BenefitHealthPlanBenefitsListParamsType] `query:"types"`
}

// URLQuery serializes [BenefitHealthPlanBenefitsListParams]'s query parameters as `url.Values`.
func (r BenefitHealthPlanBenefitsListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type BenefitHealthPlanBenefitsListParamsType string

const (
	BenefitHealthPlanBenefitsListParamsTypeMedical BenefitHealthPlanBenefitsListParamsType = "medical"
	BenefitHealthPlanBenefitsListParamsTypeDental BenefitHealthPlanBenefitsListParamsType = "dental"
	BenefitHealthPlanBenefitsListParamsTypeVision BenefitHealthPlanBenefitsListParamsType = "vision"
	BenefitHealthPlanBenefitsListParamsTypeLife BenefitHealthPlanBenefitsListParamsType = "life"
	BenefitHealthPlanBenefitsListParamsTypeShortTermDisability BenefitHealthPlanBenefitsListParamsType = "short_term_disability"
	BenefitHealthPlanBenefitsListParamsTypeLongTermDisability BenefitHealthPlanBenefitsListParamsType = "long_term_disability"
)

func (r BenefitHealthPlanBenefitsListParamsType) IsKnown() bool {
	switch r {
	case BenefitHealthPlanBenefitsListParamsTypeMedical, BenefitHealthPlanBenefitsListParamsTypeDental, BenefitHealthPlanBenefitsListParamsTypeVision, BenefitHealthPlanBenefitsListParamsTypeLife, BenefitHealthPlanBenefitsListParamsTypeShortTermDisability, BenefitHealthPlanBenefitsListParamsTypeLongTermDisability:
		return true
	}
	return false
}

type BenefitHealthPlanBenefitsListParamsStatus string

const (
	BenefitHealthPlanBenefitsListParamsStatusActive BenefitHealthPlanBenefitsListParamsStatus = "active"
	BenefitHealthPlanBenefitsListParamsStatusTerminated BenefitHealthPlanBenefitsListParamsStatus = "terminated"
)

func (r BenefitHealthPlanBenefitsListParamsStatus) IsKnown() bool {
	switch r {
	case BenefitHealthPlanBenefitsListParamsStatusActive, BenefitHealthPlanBenefitsListParamsStatusTerminated:
		return true
	}
	return false
}

type BenefitHealthPlanBenefitsListResponse struct {
	HasMore bool `json:"hasMore" api:"required"`
	// an integer
	Count int64 `json:"count" api:"required"`
	Data []PublicHealthPlan `json:"data" api:"required"`
	JSON benefitHealthPlanBenefitsListResponseJSON `json:"-"`
}

// benefitHealthPlanBenefitsListResponseJSON contains the JSON metadata for the struct [BenefitHealthPlanBenefitsListResponse]
type benefitHealthPlanBenefitsListResponseJSON struct {
	HasMore apijson.Field
	Count apijson.Field
	Data apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *BenefitHealthPlanBenefitsListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r benefitHealthPlanBenefitsListResponseJSON) RawJSON() string {
	return r.raw
}
