// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// BenefitRetirementPlanService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewBenefitRetirementPlanService] method instead.
type BenefitRetirementPlanService struct {
	Options []option.RequestOption
}

// NewBenefitRetirementPlanService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewBenefitRetirementPlanService(opts ...option.RequestOption) (r *BenefitRetirementPlanService) {
	r = &BenefitRetirementPlanService{}
	r.Options = opts
	return
}

// List company retirement plans. Defaults to active plans. A plan whose effectiveEndDate has elapsed is reported and filtered as terminated.
//
// Parameters:
//     ctx: Context for the request.
//     query: BenefitRetirementPlanBenefitsListParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *BenefitRetirementPlanBenefitsListResponse: Success
//
// Example:
//
//     retirementPlan, err := client.Benefits.RetirementPlans.BenefitsList(context.Background(), sdk.BenefitRetirementPlanBenefitsListParams{
//     	Statuses: sdk.F[[]sdk.BenefitRetirementPlanBenefitsListParamsStatus]([]sdk.BenefitRetirementPlanBenefitsListParamsStatus{"active"}),
//     })
//     if err != nil {
//     	panic(err)
//     }
//
//     fmt.Println(retirementPlan)
func (r *BenefitRetirementPlanService) BenefitsList(ctx context.Context, query BenefitRetirementPlanBenefitsListParams, opts ...option.RequestOption) (res *BenefitRetirementPlanBenefitsListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/benefits/retirement_plans"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a company retirement plan by id, regardless of status.
//
// Parameters:
//     ctx: Context for the request.
//     id: The tag of a company retirement plan.
//     opts: Options to apply to this request.
//
// Returns:
//     *BenefitRetirementPlanBenefitsGetResponse: A company retirement plan available through Warp.
//
// Example:
//
//     retirementPlan, err := client.Benefits.RetirementPlans.BenefitsGet(context.Background(), "crpl_1234")
//     if err != nil {
//     	panic(err)
//     }
//
//     fmt.Println(retirementPlan)
func (r *BenefitRetirementPlanService) BenefitsGet(ctx context.Context, id string, opts ...option.RequestOption) (res *BenefitRetirementPlanBenefitsGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/benefits/retirement_plans/%s", id)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicRetirementPlan struct {
	// The tag of a company retirement plan.
	ID string `json:"id" api:"required"`
	// The retirement plan type.
	Type PublicRetirementPlanType `json:"type" api:"required"`
	// The company-facing plan name.
	Name string `json:"name" api:"required"`
	// The system administering the plan. Manual plans are administered by the company
	// outside a connected provider.
	Provider PublicRetirementPlanProvider `json:"provider" api:"required"`
	// A date string in the form YYYY-MM-DD
	EffectiveStartDate string `json:"effectiveStartDate" api:"required"`
	EffectiveEndDate string `json:"effectiveEndDate" api:"required,nullable"`
	// The public lifecycle status of a retirement plan.
	Status PublicRetirementPlanStatus `json:"status" api:"required"`
	// a string to be decoded into a Date
	CreatedAt string `json:"createdAt" api:"required"`
	// a string to be decoded into a Date
	UpdatedAt string `json:"updatedAt" api:"required"`
	JSON publicRetirementPlanJSON `json:"-"`
}

// publicRetirementPlanJSON contains the JSON metadata for the struct [PublicRetirementPlan]
type publicRetirementPlanJSON struct {
	ID apijson.Field
	Type apijson.Field
	Name apijson.Field
	Provider apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate apijson.Field
	Status apijson.Field
	CreatedAt apijson.Field
	UpdatedAt apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicRetirementPlan) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicRetirementPlanJSON) RawJSON() string {
	return r.raw
}

type PublicRetirementPlanType string

const (
	PublicRetirementPlanType401k PublicRetirementPlanType = "401k"
	PublicRetirementPlanTypeRoth401k PublicRetirementPlanType = "roth_401k"
	PublicRetirementPlanType403b PublicRetirementPlanType = "403b"
	PublicRetirementPlanTypeRoth403b PublicRetirementPlanType = "roth_403b"
	PublicRetirementPlanType457 PublicRetirementPlanType = "457"
	PublicRetirementPlanTypeRoth457 PublicRetirementPlanType = "roth_457"
	PublicRetirementPlanTypeSimpleIra PublicRetirementPlanType = "simple_ira"
	PublicRetirementPlanTypeRothSimpleIra PublicRetirementPlanType = "roth_simple_ira"
)

func (r PublicRetirementPlanType) IsKnown() bool {
	switch r {
	case PublicRetirementPlanType401k, PublicRetirementPlanTypeRoth401k, PublicRetirementPlanType403b, PublicRetirementPlanTypeRoth403b, PublicRetirementPlanType457, PublicRetirementPlanTypeRoth457, PublicRetirementPlanTypeSimpleIra, PublicRetirementPlanTypeRothSimpleIra:
		return true
	}
	return false
}

type PublicRetirementPlanProvider string

const (
	PublicRetirementPlanProviderManual PublicRetirementPlanProvider = "manual"
	PublicRetirementPlanProviderHumanInterest PublicRetirementPlanProvider = "human_interest"
	PublicRetirementPlanProviderAccrue PublicRetirementPlanProvider = "accrue"
)

func (r PublicRetirementPlanProvider) IsKnown() bool {
	switch r {
	case PublicRetirementPlanProviderManual, PublicRetirementPlanProviderHumanInterest, PublicRetirementPlanProviderAccrue:
		return true
	}
	return false
}

type PublicRetirementPlanStatus string

const (
	PublicRetirementPlanStatusActive PublicRetirementPlanStatus = "active"
	PublicRetirementPlanStatusTerminated PublicRetirementPlanStatus = "terminated"
)

func (r PublicRetirementPlanStatus) IsKnown() bool {
	switch r {
	case PublicRetirementPlanStatusActive, PublicRetirementPlanStatusTerminated:
		return true
	}
	return false
}

type BenefitRetirementPlanBenefitsGetResponse struct {
	// The tag of a company retirement plan.
	ID string `json:"id" api:"required"`
	// The retirement plan type.
	Type BenefitRetirementPlanBenefitsGetResponseType `json:"type" api:"required"`
	// The company-facing plan name.
	Name string `json:"name" api:"required"`
	// The system administering the plan. Manual plans are administered by the company
	// outside a connected provider.
	Provider BenefitRetirementPlanBenefitsGetResponseProvider `json:"provider" api:"required"`
	// A date string in the form YYYY-MM-DD
	EffectiveStartDate string `json:"effectiveStartDate" api:"required"`
	EffectiveEndDate string `json:"effectiveEndDate" api:"required,nullable"`
	// The public lifecycle status of a retirement plan.
	Status BenefitRetirementPlanBenefitsGetResponseStatus `json:"status" api:"required"`
	// a string to be decoded into a Date
	CreatedAt string `json:"createdAt" api:"required"`
	// a string to be decoded into a Date
	UpdatedAt string `json:"updatedAt" api:"required"`
	JSON benefitRetirementPlanBenefitsGetResponseJSON `json:"-"`
}

// benefitRetirementPlanBenefitsGetResponseJSON contains the JSON metadata for the struct [BenefitRetirementPlanBenefitsGetResponse]
type benefitRetirementPlanBenefitsGetResponseJSON struct {
	ID apijson.Field
	Type apijson.Field
	Name apijson.Field
	Provider apijson.Field
	EffectiveStartDate apijson.Field
	EffectiveEndDate apijson.Field
	Status apijson.Field
	CreatedAt apijson.Field
	UpdatedAt apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *BenefitRetirementPlanBenefitsGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r benefitRetirementPlanBenefitsGetResponseJSON) RawJSON() string {
	return r.raw
}

type BenefitRetirementPlanBenefitsGetResponseType string

const (
	BenefitRetirementPlanBenefitsGetResponseType401k BenefitRetirementPlanBenefitsGetResponseType = "401k"
	BenefitRetirementPlanBenefitsGetResponseTypeRoth401k BenefitRetirementPlanBenefitsGetResponseType = "roth_401k"
	BenefitRetirementPlanBenefitsGetResponseType403b BenefitRetirementPlanBenefitsGetResponseType = "403b"
	BenefitRetirementPlanBenefitsGetResponseTypeRoth403b BenefitRetirementPlanBenefitsGetResponseType = "roth_403b"
	BenefitRetirementPlanBenefitsGetResponseType457 BenefitRetirementPlanBenefitsGetResponseType = "457"
	BenefitRetirementPlanBenefitsGetResponseTypeRoth457 BenefitRetirementPlanBenefitsGetResponseType = "roth_457"
	BenefitRetirementPlanBenefitsGetResponseTypeSimpleIra BenefitRetirementPlanBenefitsGetResponseType = "simple_ira"
	BenefitRetirementPlanBenefitsGetResponseTypeRothSimpleIra BenefitRetirementPlanBenefitsGetResponseType = "roth_simple_ira"
)

func (r BenefitRetirementPlanBenefitsGetResponseType) IsKnown() bool {
	switch r {
	case BenefitRetirementPlanBenefitsGetResponseType401k, BenefitRetirementPlanBenefitsGetResponseTypeRoth401k, BenefitRetirementPlanBenefitsGetResponseType403b, BenefitRetirementPlanBenefitsGetResponseTypeRoth403b, BenefitRetirementPlanBenefitsGetResponseType457, BenefitRetirementPlanBenefitsGetResponseTypeRoth457, BenefitRetirementPlanBenefitsGetResponseTypeSimpleIra, BenefitRetirementPlanBenefitsGetResponseTypeRothSimpleIra:
		return true
	}
	return false
}

type BenefitRetirementPlanBenefitsGetResponseProvider string

const (
	BenefitRetirementPlanBenefitsGetResponseProviderManual BenefitRetirementPlanBenefitsGetResponseProvider = "manual"
	BenefitRetirementPlanBenefitsGetResponseProviderHumanInterest BenefitRetirementPlanBenefitsGetResponseProvider = "human_interest"
	BenefitRetirementPlanBenefitsGetResponseProviderAccrue BenefitRetirementPlanBenefitsGetResponseProvider = "accrue"
)

func (r BenefitRetirementPlanBenefitsGetResponseProvider) IsKnown() bool {
	switch r {
	case BenefitRetirementPlanBenefitsGetResponseProviderManual, BenefitRetirementPlanBenefitsGetResponseProviderHumanInterest, BenefitRetirementPlanBenefitsGetResponseProviderAccrue:
		return true
	}
	return false
}

type BenefitRetirementPlanBenefitsGetResponseStatus string

const (
	BenefitRetirementPlanBenefitsGetResponseStatusActive BenefitRetirementPlanBenefitsGetResponseStatus = "active"
	BenefitRetirementPlanBenefitsGetResponseStatusTerminated BenefitRetirementPlanBenefitsGetResponseStatus = "terminated"
)

func (r BenefitRetirementPlanBenefitsGetResponseStatus) IsKnown() bool {
	switch r {
	case BenefitRetirementPlanBenefitsGetResponseStatusActive, BenefitRetirementPlanBenefitsGetResponseStatusTerminated:
		return true
	}
	return false
}

type BenefitRetirementPlanBenefitsListParams struct {
	// The tag of a company retirement plan.
	AfterID param.Field[string] `query:"afterId"`
	// The tag of a company retirement plan.
	BeforeID param.Field[string] `query:"beforeId"`
	// a number less than or equal to 100
	Limit param.Field[string] `query:"limit"`
	// Statuses to include. Defaults to ["active"]. An elapsed effectiveEndDate is
	// reported and filtered as "terminated".
	Statuses param.Field[[]BenefitRetirementPlanBenefitsListParamsStatus] `query:"statuses"`
	Types param.Field[[]BenefitRetirementPlanBenefitsListParamsType] `query:"types"`
}

// URLQuery serializes [BenefitRetirementPlanBenefitsListParams]'s query parameters as `url.Values`.
func (r BenefitRetirementPlanBenefitsListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type BenefitRetirementPlanBenefitsListParamsType string

const (
	BenefitRetirementPlanBenefitsListParamsType401k BenefitRetirementPlanBenefitsListParamsType = "401k"
	BenefitRetirementPlanBenefitsListParamsTypeRoth401k BenefitRetirementPlanBenefitsListParamsType = "roth_401k"
	BenefitRetirementPlanBenefitsListParamsType403b BenefitRetirementPlanBenefitsListParamsType = "403b"
	BenefitRetirementPlanBenefitsListParamsTypeRoth403b BenefitRetirementPlanBenefitsListParamsType = "roth_403b"
	BenefitRetirementPlanBenefitsListParamsType457 BenefitRetirementPlanBenefitsListParamsType = "457"
	BenefitRetirementPlanBenefitsListParamsTypeRoth457 BenefitRetirementPlanBenefitsListParamsType = "roth_457"
	BenefitRetirementPlanBenefitsListParamsTypeSimpleIra BenefitRetirementPlanBenefitsListParamsType = "simple_ira"
	BenefitRetirementPlanBenefitsListParamsTypeRothSimpleIra BenefitRetirementPlanBenefitsListParamsType = "roth_simple_ira"
)

func (r BenefitRetirementPlanBenefitsListParamsType) IsKnown() bool {
	switch r {
	case BenefitRetirementPlanBenefitsListParamsType401k, BenefitRetirementPlanBenefitsListParamsTypeRoth401k, BenefitRetirementPlanBenefitsListParamsType403b, BenefitRetirementPlanBenefitsListParamsTypeRoth403b, BenefitRetirementPlanBenefitsListParamsType457, BenefitRetirementPlanBenefitsListParamsTypeRoth457, BenefitRetirementPlanBenefitsListParamsTypeSimpleIra, BenefitRetirementPlanBenefitsListParamsTypeRothSimpleIra:
		return true
	}
	return false
}

type BenefitRetirementPlanBenefitsListParamsStatus string

const (
	BenefitRetirementPlanBenefitsListParamsStatusActive BenefitRetirementPlanBenefitsListParamsStatus = "active"
	BenefitRetirementPlanBenefitsListParamsStatusTerminated BenefitRetirementPlanBenefitsListParamsStatus = "terminated"
)

func (r BenefitRetirementPlanBenefitsListParamsStatus) IsKnown() bool {
	switch r {
	case BenefitRetirementPlanBenefitsListParamsStatusActive, BenefitRetirementPlanBenefitsListParamsStatusTerminated:
		return true
	}
	return false
}

type BenefitRetirementPlanBenefitsListResponse struct {
	HasMore bool `json:"hasMore" api:"required"`
	// an integer
	Count int64 `json:"count" api:"required"`
	Data []PublicRetirementPlan `json:"data" api:"required"`
	JSON benefitRetirementPlanBenefitsListResponseJSON `json:"-"`
}

// benefitRetirementPlanBenefitsListResponseJSON contains the JSON metadata for the struct [BenefitRetirementPlanBenefitsListResponse]
type benefitRetirementPlanBenefitsListResponseJSON struct {
	HasMore apijson.Field
	Count apijson.Field
	Data apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *BenefitRetirementPlanBenefitsListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r benefitRetirementPlanBenefitsListResponseJSON) RawJSON() string {
	return r.raw
}
