// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"net/http"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// LevelService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewLevelService] method instead.
type LevelService struct {
	Options []option.RequestOption
}

// NewLevelService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewLevelService(opts ...option.RequestOption) (r *LevelService) {
	r = &LevelService{}
	r.Options = opts
	return
}

// List the active standard job levels available to your company.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*[]LevelListResponse: Success
//
// Example:
//
//	level, err := client.Levels.List(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(level)
func (r *LevelService) List(ctx context.Context, opts ...option.RequestOption) (res *[]LevelListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/levels"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type LevelListResponse struct {
	// The unique public id of the job level
	ID    string                 `json:"id" api:"required"`
	Code  string                 `json:"code" api:"required"`
	Name  string                 `json:"name" api:"required"`
	Track LevelListResponseTrack `json:"track" api:"required"`
	JSON  levelListResponseJSON  `json:"-"`
}

// levelListResponseJSON contains the JSON metadata for the struct [LevelListResponse]
type levelListResponseJSON struct {
	ID          apijson.Field
	Code        apijson.Field
	Name        apijson.Field
	Track       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *LevelListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r levelListResponseJSON) RawJSON() string {
	return r.raw
}

type LevelListResponseTrack string

const (
	LevelListResponseTrackIc        LevelListResponseTrack = "ic"
	LevelListResponseTrackManager   LevelListResponseTrack = "manager"
	LevelListResponseTrackExecutive LevelListResponseTrack = "executive"
)

func (r LevelListResponseTrack) IsKnown() bool {
	switch r {
	case LevelListResponseTrackIc, LevelListResponseTrackManager, LevelListResponseTrackExecutive:
		return true
	}
	return false
}
