// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// PayrollService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPayrollService] method instead.
type PayrollService struct {
	Options []option.RequestOption
}

// NewPayrollService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPayrollService(opts ...option.RequestOption) (r *PayrollService) {
	r = &PayrollService{}
	r.Options = opts
	return
}

// List per-worker paycheck summaries newest first with stable cursor ordering. By default, the response includes every worker type visible to the API key, including US W-2 employees, US 1099 contractors, and global contractors; use workerTypes to narrow the results. Payroll type visibility follows the API key permissions. All lifecycle statuses are included unless statuses are provided.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: PayrollListPaychecksParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayrollListPaychecksResponse: A cursor-paginated page of paycheck summaries.
//
// Example:
//
//	payroll, err := client.Payroll.ListPaychecks(context.Background(), sdk.PayrollListPaychecksParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) ListPaychecks(ctx context.Context, query PayrollListPaychecksParams, opts ...option.RequestOption) (res *PayrollListPaychecksResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/paychecks"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a paycheck by id. All worker types use the same paycheck schema. Categories that do not apply to a worker are represented by zero-valued totals and empty line-item arrays. For example, a US 1099 contractor with no applicable payroll taxes returns zero `workerTaxes` and `employerTaxes` totals and an empty `taxes` array. Missing, foreign, unauthorized, or unavailable paychecks return 404.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The paycheck ID.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayrollGetPaycheckResponse: A paycheck with currency-specific calculation lines, totals grouped by currency, and authoritative parent-payroll funding-currency totals. Source currencies for expenses, benefits, or other inputs are outside this payroll-calculation resource.
//
// Example:
//
//	payroll, err := client.Payroll.GetPaycheck(context.Background(), "pyc_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) GetPaycheck(ctx context.Context, id string, opts ...option.RequestOption) (res *PayrollGetPaycheckResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paychecks/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// List payroll summaries newest first with stable cursor ordering. Every amount in totals is expressed in fundingCurrency, the currency the employer uses to fund the payroll. Line-derived categories are converted and rounded per paycheck before aggregation, while netPay remains provider-authoritative. Payroll type visibility follows the API key permissions. All lifecycle statuses are included unless statuses are provided.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: PayrollListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayrollListResponse: A cursor-paginated page of payroll summaries.
//
// Example:
//
//	payroll, err := client.Payroll.List(context.Background(), sdk.PayrollListParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) List(ctx context.Context, query PayrollListParams, opts ...option.RequestOption) (res *PayrollListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/payrolls"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get a payroll by id. Every amount in totals is expressed in fundingCurrency, the currency the employer uses to fund the payroll. Line-derived categories are converted and rounded per paycheck before aggregation, while netPay remains provider-authoritative. Missing, foreign, unauthorized, or unavailable payrolls return 404.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: The payroll ID.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayrollGetResponse: A payroll run with funding and lifecycle details. Every amount in totals is expressed in fundingCurrency; line-derived categories are converted and rounded per paycheck before aggregation, while netPay remains provider-authoritative.
//
// Example:
//
//	payroll, err := client.Payroll.Get(context.Background(), "pay_1234")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payroll)
func (r *PayrollService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *PayrollGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payrolls/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PublicPaycheckPayroll struct {
	// The tag of the payroll.
	ID              string                    `json:"id" api:"required"`
	Type            interface{}               `json:"type" api:"required"`
	Subtype         interface{}               `json:"subtype" api:"required"`
	Status          interface{}               `json:"status" api:"required"`
	FundingCurrency interface{}               `json:"fundingCurrency" api:"required"`
	PayPeriod       interface{}               `json:"payPeriod" api:"required"`
	PayFrequency    PublicPayFrequency        `json:"payFrequency" api:"required,nullable"`
	JSON            publicPaycheckPayrollJSON `json:"-"`
}

// publicPaycheckPayrollJSON contains the JSON metadata for the struct [PublicPaycheckPayroll]
type publicPaycheckPayrollJSON struct {
	ID              apijson.Field
	Type            apijson.Field
	Subtype         apijson.Field
	Status          apijson.Field
	FundingCurrency apijson.Field
	PayPeriod       apijson.Field
	PayFrequency    apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *PublicPaycheckPayroll) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckPayrollJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckWorker struct {
	// The worker id.
	ID string `json:"id" api:"required"`
	// The worker first name.
	FirstName string `json:"firstName" api:"required"`
	// The worker last name.
	LastName    string                         `json:"lastName" api:"required"`
	DisplayName string                         `json:"displayName" api:"required"`
	WorkerType  PublicPaycheckWorkerWorkerType `json:"workerType" api:"required"`
	JSON        publicPaycheckWorkerJSON       `json:"-"`
}

// publicPaycheckWorkerJSON contains the JSON metadata for the struct [PublicPaycheckWorker]
type publicPaycheckWorkerJSON struct {
	ID          apijson.Field
	FirstName   apijson.Field
	LastName    apijson.Field
	DisplayName apijson.Field
	WorkerType  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckWorker) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckWorkerJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckWorkerWorkerType string

const (
	PublicPaycheckWorkerWorkerTypeUsW2             PublicPaycheckWorkerWorkerType = "us_w2"
	PublicPaycheckWorkerWorkerTypeUs1099           PublicPaycheckWorkerWorkerType = "us_1099"
	PublicPaycheckWorkerWorkerTypeGlobalContractor PublicPaycheckWorkerWorkerType = "global_contractor"
)

func (r PublicPaycheckWorkerWorkerType) IsKnown() bool {
	switch r {
	case PublicPaycheckWorkerWorkerTypeUsW2, PublicPaycheckWorkerWorkerTypeUs1099, PublicPaycheckWorkerWorkerTypeGlobalContractor:
		return true
	}
	return false
}

type PublicPaycheckDetailTotals struct {
	ByCurrency        string                         `json:"byCurrency" api:"required"`
	InFundingCurrency interface{}                    `json:"inFundingCurrency" api:"required"`
	JSON              publicPaycheckDetailTotalsJSON `json:"-"`
}

// publicPaycheckDetailTotalsJSON contains the JSON metadata for the struct [PublicPaycheckDetailTotals]
type publicPaycheckDetailTotalsJSON struct {
	ByCurrency        apijson.Field
	InFundingCurrency apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *PublicPaycheckDetailTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckDetailTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotals struct {
	Currency interface{} `json:"currency" api:"required"`
	// Gross earnings before worker taxes, deductions, and benefit contributions.
	// Reimbursements are reported separately.
	GrossPay PublicPaycheckCurrencyTotalsGrossPay `json:"grossPay" api:"required"`
	// Calculated net pay after reimbursements, worker taxes, deductions, and benefit
	// contributions. It excludes payment execution fees and may differ from the amount
	// the worker ultimately receives.
	NetPay PublicPaycheckCurrencyTotalsNetPay `json:"netPay" api:"required"`
	// Amounts reimbursed to the worker in addition to gross pay. Reimbursements
	// increase net pay and employer cost.
	Reimbursements PublicPaycheckCurrencyTotalsReimbursements `json:"reimbursements" api:"required"`
	// Payroll taxes withheld from the worker's pay, reducing net pay.
	WorkerTaxes PublicPaycheckCurrencyTotalsWorkerTaxes `json:"workerTaxes" api:"required"`
	// Payroll taxes paid by the employer in addition to gross pay.
	EmployerTaxes PublicPaycheckCurrencyTotalsEmployerTaxes `json:"employerTaxes" api:"required"`
	// Non-benefit amounts deducted from the worker's pay before taxes, reducing
	// taxable pay and net pay.
	PreTaxDeductions PublicPaycheckCurrencyTotalsPreTaxDeductions `json:"preTaxDeductions" api:"required"`
	// Non-benefit amounts deducted from the worker's pay after taxes, reducing net
	// pay.
	PostTaxDeductions PublicPaycheckCurrencyTotalsPostTaxDeductions `json:"postTaxDeductions" api:"required"`
	// Amounts the worker pays toward benefits, deducted from their pay.
	WorkerBenefitContributions PublicPaycheckCurrencyTotalsWorkerBenefitContributions `json:"workerBenefitContributions" api:"required"`
	// Amounts the employer pays toward the worker's benefits in addition to gross pay.
	EmployerBenefitContributions PublicPaycheckCurrencyTotalsEmployerBenefitContributions `json:"employerBenefitContributions" api:"required"`
	JSON                         publicPaycheckCurrencyTotalsJSON                         `json:"-"`
}

// publicPaycheckCurrencyTotalsJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotals]
type publicPaycheckCurrencyTotalsJSON struct {
	Currency                     apijson.Field
	GrossPay                     apijson.Field
	NetPay                       apijson.Field
	Reimbursements               apijson.Field
	WorkerTaxes                  apijson.Field
	EmployerTaxes                apijson.Field
	PreTaxDeductions             apijson.Field
	PostTaxDeductions            apijson.Field
	WorkerBenefitContributions   apijson.Field
	EmployerBenefitContributions apijson.Field
	raw                          string
	ExtraFields                  map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotals struct {
	CashRequirement PublicPayrollDetailTotalsCashRequirement `json:"cashRequirement" api:"required,nullable"`
	// Gross earnings before worker taxes, deductions, and benefit contributions.
	// Reimbursements are reported separately.
	GrossPay PublicPayrollDetailTotalsGrossPay `json:"grossPay" api:"required"`
	// The provider-calculated amount to send for workers: gross pay plus
	// reimbursements, less worker taxes, deductions, and benefit contributions. It
	// excludes payment execution fees and may differ from recomputed totals because of
	// provider and FX rounding.
	NetPay PublicPayrollDetailTotalsNetPay `json:"netPay" api:"required"`
	// Amounts reimbursed to workers in addition to gross pay. Reimbursements increase
	// net pay and employer cost.
	Reimbursements PublicPayrollDetailTotalsReimbursements `json:"reimbursements" api:"required"`
	// Payroll taxes withheld from worker pay, reducing net pay.
	WorkerTaxes PublicPayrollDetailTotalsWorkerTaxes `json:"workerTaxes" api:"required"`
	// Payroll taxes paid by the employer in addition to gross pay.
	EmployerTaxes PublicPayrollDetailTotalsEmployerTaxes `json:"employerTaxes" api:"required"`
	// Non-benefit amounts deducted from worker pay before taxes, reducing taxable pay
	// and net pay.
	PreTaxDeductions PublicPayrollDetailTotalsPreTaxDeductions `json:"preTaxDeductions" api:"required"`
	// Non-benefit amounts deducted from worker pay after taxes, reducing net pay.
	PostTaxDeductions PublicPayrollDetailTotalsPostTaxDeductions `json:"postTaxDeductions" api:"required"`
	// Amounts workers pay toward benefits, deducted from their pay.
	WorkerBenefitContributions PublicPayrollDetailTotalsWorkerBenefitContributions `json:"workerBenefitContributions" api:"required"`
	// Amounts the employer pays toward worker benefits in addition to gross pay.
	EmployerBenefitContributions PublicPayrollDetailTotalsEmployerBenefitContributions `json:"employerBenefitContributions" api:"required"`
	// Banking and transaction fees paid by the employer to fund and pay the payroll.
	TransactionFees PublicPayrollDetailTotalsTransactionFees `json:"transactionFees" api:"required"`
	// The employer's total payroll cost: gross pay, reimbursements, employer taxes,
	// employer benefit contributions, and transaction fees.
	TotalCost PublicPayrollDetailTotalsTotalCost `json:"totalCost" api:"required"`
	JSON      publicPayrollDetailTotalsJSON      `json:"-"`
}

// publicPayrollDetailTotalsJSON contains the JSON metadata for the struct [PublicPayrollDetailTotals]
type publicPayrollDetailTotalsJSON struct {
	CashRequirement              apijson.Field
	GrossPay                     apijson.Field
	NetPay                       apijson.Field
	Reimbursements               apijson.Field
	WorkerTaxes                  apijson.Field
	EmployerTaxes                apijson.Field
	PreTaxDeductions             apijson.Field
	PostTaxDeductions            apijson.Field
	WorkerBenefitContributions   apijson.Field
	EmployerBenefitContributions apijson.Field
	TransactionFees              apijson.Field
	TotalCost                    apijson.Field
	raw                          string
	ExtraFields                  map[string]apijson.Field
}

func (r *PublicPayrollDetailTotals) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollTimeline struct {
	ApprovedAt string                    `json:"approvedAt" api:"required,nullable"`
	JSON       publicPayrollTimelineJSON `json:"-"`
}

// publicPayrollTimelineJSON contains the JSON metadata for the struct [PublicPayrollTimeline]
type publicPayrollTimelineJSON struct {
	ApprovedAt  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollTimeline) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollTimelineJSON) RawJSON() string {
	return r.raw
}

type PayrollListPaychecksResponse struct {
	HasMore bool                             `json:"hasMore" api:"required"`
	Count   int64                            `json:"count" api:"required"`
	Data    string                           `json:"data" api:"required"`
	JSON    payrollListPaychecksResponseJSON `json:"-"`
}

// payrollListPaychecksResponseJSON contains the JSON metadata for the struct [PayrollListPaychecksResponse]
type payrollListPaychecksResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PayrollListPaychecksResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payrollListPaychecksResponseJSON) RawJSON() string {
	return r.raw
}

type PayrollGetPaycheckResponse struct {
	// The tag of the paycheck.
	ID             string                         `json:"id" api:"required"`
	Payroll        interface{}                    `json:"payroll" api:"required"`
	Worker         interface{}                    `json:"worker" api:"required"`
	Status         interface{}                    `json:"status" api:"required"`
	Payday         string                         `json:"payday" api:"required"`
	PaymentMethod  interface{}                    `json:"paymentMethod" api:"required"`
	Totals         interface{}                    `json:"totals" api:"required"`
	Description    string                         `json:"description" api:"required,nullable"`
	ExchangeRates  string                         `json:"exchangeRates" api:"required"`
	ReportedHours  float64                        `json:"reportedHours" api:"required,nullable"`
	Earnings       string                         `json:"earnings" api:"required"`
	Reimbursements string                         `json:"reimbursements" api:"required"`
	Deductions     string                         `json:"deductions" api:"required"`
	Benefits       string                         `json:"benefits" api:"required"`
	Taxes          string                         `json:"taxes" api:"required"`
	JSON           payrollGetPaycheckResponseJSON `json:"-"`
}

// payrollGetPaycheckResponseJSON contains the JSON metadata for the struct [PayrollGetPaycheckResponse]
type payrollGetPaycheckResponseJSON struct {
	ID             apijson.Field
	Payroll        apijson.Field
	Worker         apijson.Field
	Status         apijson.Field
	Payday         apijson.Field
	PaymentMethod  apijson.Field
	Totals         apijson.Field
	Description    apijson.Field
	ExchangeRates  apijson.Field
	ReportedHours  apijson.Field
	Earnings       apijson.Field
	Reimbursements apijson.Field
	Deductions     apijson.Field
	Benefits       apijson.Field
	Taxes          apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *PayrollGetPaycheckResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payrollGetPaycheckResponseJSON) RawJSON() string {
	return r.raw
}

type PayrollListResponse struct {
	HasMore bool                    `json:"hasMore" api:"required"`
	Count   int64                   `json:"count" api:"required"`
	Data    interface{}             `json:"data" api:"required"`
	JSON    payrollListResponseJSON `json:"-"`
}

// payrollListResponseJSON contains the JSON metadata for the struct [PayrollListResponse]
type payrollListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PayrollListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payrollListResponseJSON) RawJSON() string {
	return r.raw
}

type PayrollGetResponse struct {
	// The tag of the payroll.
	ID               string                 `json:"id" api:"required"`
	Type             interface{}            `json:"type" api:"required"`
	Subtype          interface{}            `json:"subtype" api:"required"`
	Status           interface{}            `json:"status" api:"required"`
	FundingCurrency  interface{}            `json:"fundingCurrency" api:"required"`
	Payday           string                 `json:"payday" api:"required"`
	PayPeriod        interface{}            `json:"payPeriod" api:"required"`
	PayFrequency     PublicPayFrequency     `json:"payFrequency" api:"required,nullable"`
	Description      string                 `json:"description" api:"required,nullable"`
	ApprovalDeadline string                 `json:"approvalDeadline" api:"required,nullable"`
	PaycheckCount    int64                  `json:"paycheckCount" api:"required"`
	Totals           interface{}            `json:"totals" api:"required"`
	FundingMethod    interface{}            `json:"fundingMethod" api:"required"`
	ReopenDeadline   string                 `json:"reopenDeadline" api:"required,nullable"`
	Timeline         interface{}            `json:"timeline" api:"required"`
	JSON             payrollGetResponseJSON `json:"-"`
}

// payrollGetResponseJSON contains the JSON metadata for the struct [PayrollGetResponse]
type payrollGetResponseJSON struct {
	ID               apijson.Field
	Type             apijson.Field
	Subtype          apijson.Field
	Status           apijson.Field
	FundingCurrency  apijson.Field
	Payday           apijson.Field
	PayPeriod        apijson.Field
	PayFrequency     apijson.Field
	Description      apijson.Field
	ApprovalDeadline apijson.Field
	PaycheckCount    apijson.Field
	Totals           apijson.Field
	FundingMethod    apijson.Field
	ReopenDeadline   apijson.Field
	Timeline         apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *PayrollGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payrollGetResponseJSON) RawJSON() string {
	return r.raw
}

type PayrollGetResponsePayFrequency string

const (
	PayrollGetResponsePayFrequencyWeekly      PayrollGetResponsePayFrequency = "weekly"
	PayrollGetResponsePayFrequencyBiweekly    PayrollGetResponsePayFrequency = "biweekly"
	PayrollGetResponsePayFrequencyMonthly     PayrollGetResponsePayFrequency = "monthly"
	PayrollGetResponsePayFrequencySemimonthly PayrollGetResponsePayFrequency = "semimonthly"
	PayrollGetResponsePayFrequencyQuarterly   PayrollGetResponsePayFrequency = "quarterly"
	PayrollGetResponsePayFrequencyAnnually    PayrollGetResponsePayFrequency = "annually"
)

func (r PayrollGetResponsePayFrequency) IsKnown() bool {
	switch r {
	case PayrollGetResponsePayFrequencyWeekly, PayrollGetResponsePayFrequencyBiweekly, PayrollGetResponsePayFrequencyMonthly, PayrollGetResponsePayFrequencySemimonthly, PayrollGetResponsePayFrequencyQuarterly, PayrollGetResponsePayFrequencyAnnually:
		return true
	}
	return false
}

type PayrollListPaychecksParams struct {
	// The maximum number of paychecks to return, from 1 to 50.
	Limit param.Field[string] `query:"limit" api:"required"`
	// Return paychecks after this paycheck ID in the stable cursor order. Cannot be
	// used with beforeId.
	AfterID param.Field[string] `query:"afterId"`
	// Return paychecks before this paycheck ID in the stable cursor order. Cannot be
	// used with afterId.
	BeforeID param.Field[string] `query:"beforeId"`
	// Paycheck compensation currencies to include.
	CompensationCurrencies param.Field[[]PublicPayrollCurrency] `query:"compensationCurrencies"`
	// Pay cadences to include.
	PayFrequencies param.Field[[]PublicPayFrequency] `query:"payFrequencies"`
	// Exclusive end of the half-open payday range.
	PaydayBefore param.Field[string] `query:"paydayBefore"`
	// Inclusive start of the half-open payday range.
	PaydayOnOrAfter param.Field[string] `query:"paydayOnOrAfter"`
	// Payment methods to include.
	PaymentMethods param.Field[[]PublicPaycheckPaymentMethod] `query:"paymentMethods"`
	// Payrolls whose paychecks should be included.
	PayrollIDs param.Field[[]string] `query:"payrollIds"`
	// Payroll calculation types to include, subject to the API key permissions.
	PayrollTypes param.Field[[]PublicPayrollType] `query:"payrollTypes"`
	// Lifecycle statuses to include. Omit to include every status.
	Statuses param.Field[[]PublicPaycheckStatus] `query:"statuses"`
	// Workers whose paychecks should be included.
	WorkerIDs param.Field[[]string] `query:"workerIds"`
	// Worker classifications in effect for the paycheck to include. Omit to include
	// every worker type visible to the API key.
	WorkerTypes param.Field[[]PayrollListPaychecksParamsWorkerType] `query:"workerTypes"`
}

// URLQuery serializes [PayrollListPaychecksParams]'s query parameters as `url.Values`.
func (r PayrollListPaychecksParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PayrollListPaychecksParamsWorkerType string

const (
	PayrollListPaychecksParamsWorkerTypeUsW2             PayrollListPaychecksParamsWorkerType = "us_w2"
	PayrollListPaychecksParamsWorkerTypeUs1099           PayrollListPaychecksParamsWorkerType = "us_1099"
	PayrollListPaychecksParamsWorkerTypeGlobalContractor PayrollListPaychecksParamsWorkerType = "global_contractor"
)

func (r PayrollListPaychecksParamsWorkerType) IsKnown() bool {
	switch r {
	case PayrollListPaychecksParamsWorkerTypeUsW2, PayrollListPaychecksParamsWorkerTypeUs1099, PayrollListPaychecksParamsWorkerTypeGlobalContractor:
		return true
	}
	return false
}

type PayrollListParams struct {
	// The maximum number of payrolls to return, from 1 to 50.
	Limit param.Field[string] `query:"limit" api:"required"`
	// Return payrolls after this payroll ID in the stable cursor order. Cannot be used
	// with beforeId.
	AfterID param.Field[string] `query:"afterId"`
	// Return payrolls before this payroll ID in the stable cursor order. Cannot be
	// used with afterId.
	BeforeID param.Field[string] `query:"beforeId"`
	// Pay cadences to include.
	PayFrequencies param.Field[[]PublicPayFrequency] `query:"payFrequencies"`
	// Exclusive end of the half-open pay-period-end range.
	PayPeriodEndBefore param.Field[string] `query:"payPeriodEndBefore"`
	// Inclusive start of the half-open pay-period-end range.
	PayPeriodEndOnOrAfter param.Field[string] `query:"payPeriodEndOnOrAfter"`
	// Exclusive end of the half-open payday range.
	PaydayBefore param.Field[string] `query:"paydayBefore"`
	// Inclusive start of the half-open payday range.
	PaydayOnOrAfter param.Field[string] `query:"paydayOnOrAfter"`
	// Lifecycle statuses to include. Omit to include every status.
	Statuses param.Field[[]PublicPayrollStatus] `query:"statuses"`
	// Payroll subtypes to include.
	Subtypes param.Field[[]PublicPayrollSubtype] `query:"subtypes"`
	// Payroll calculation types to include.
	Types param.Field[[]PublicPayrollType] `query:"types"`
}

// URLQuery serializes [PayrollListParams]'s query parameters as `url.Values`.
func (r PayrollListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PublicPaycheckCurrencyTotalsGrossPay struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                   `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsGrossPayJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsGrossPayJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsGrossPay]
type publicPaycheckCurrencyTotalsGrossPayJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsGrossPay) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsGrossPayJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsNetPay struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                 `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsNetPayJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsNetPayJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsNetPay]
type publicPaycheckCurrencyTotalsNetPayJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsNetPay) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsNetPayJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsReimbursements struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                         `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsReimbursementsJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsReimbursementsJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsReimbursements]
type publicPaycheckCurrencyTotalsReimbursementsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsReimbursements) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsReimbursementsJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsWorkerTaxes struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                      `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsWorkerTaxesJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsWorkerTaxesJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsWorkerTaxes]
type publicPaycheckCurrencyTotalsWorkerTaxesJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsWorkerTaxes) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsWorkerTaxesJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsEmployerTaxes struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                        `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsEmployerTaxesJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsEmployerTaxesJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsEmployerTaxes]
type publicPaycheckCurrencyTotalsEmployerTaxesJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsEmployerTaxes) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsEmployerTaxesJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsPreTaxDeductions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                           `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsPreTaxDeductionsJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsPreTaxDeductionsJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsPreTaxDeductions]
type publicPaycheckCurrencyTotalsPreTaxDeductionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsPreTaxDeductions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsPreTaxDeductionsJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsPostTaxDeductions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                            `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsPostTaxDeductionsJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsPostTaxDeductionsJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsPostTaxDeductions]
type publicPaycheckCurrencyTotalsPostTaxDeductionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsPostTaxDeductions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsPostTaxDeductionsJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsWorkerBenefitContributions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                                     `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsWorkerBenefitContributionsJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsWorkerBenefitContributionsJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsWorkerBenefitContributions]
type publicPaycheckCurrencyTotalsWorkerBenefitContributionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsWorkerBenefitContributions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsWorkerBenefitContributionsJSON) RawJSON() string {
	return r.raw
}

type PublicPaycheckCurrencyTotalsEmployerBenefitContributions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                                       `json:"display" api:"required"`
	JSON    publicPaycheckCurrencyTotalsEmployerBenefitContributionsJSON `json:"-"`
}

// publicPaycheckCurrencyTotalsEmployerBenefitContributionsJSON contains the JSON metadata for the struct [PublicPaycheckCurrencyTotalsEmployerBenefitContributions]
type publicPaycheckCurrencyTotalsEmployerBenefitContributionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPaycheckCurrencyTotalsEmployerBenefitContributions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPaycheckCurrencyTotalsEmployerBenefitContributionsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsCashRequirement struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                       `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsCashRequirementJSON `json:"-"`
}

// publicPayrollDetailTotalsCashRequirementJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsCashRequirement]
type publicPayrollDetailTotalsCashRequirementJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsCashRequirement) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsCashRequirementJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsGrossPay struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsGrossPayJSON `json:"-"`
}

// publicPayrollDetailTotalsGrossPayJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsGrossPay]
type publicPayrollDetailTotalsGrossPayJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsGrossPay) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsGrossPayJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsNetPay struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                              `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsNetPayJSON `json:"-"`
}

// publicPayrollDetailTotalsNetPayJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsNetPay]
type publicPayrollDetailTotalsNetPayJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsNetPay) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsNetPayJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsReimbursements struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                      `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsReimbursementsJSON `json:"-"`
}

// publicPayrollDetailTotalsReimbursementsJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsReimbursements]
type publicPayrollDetailTotalsReimbursementsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsReimbursements) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsReimbursementsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsWorkerTaxes struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                   `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsWorkerTaxesJSON `json:"-"`
}

// publicPayrollDetailTotalsWorkerTaxesJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsWorkerTaxes]
type publicPayrollDetailTotalsWorkerTaxesJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsWorkerTaxes) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsWorkerTaxesJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsEmployerTaxes struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                     `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsEmployerTaxesJSON `json:"-"`
}

// publicPayrollDetailTotalsEmployerTaxesJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsEmployerTaxes]
type publicPayrollDetailTotalsEmployerTaxesJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsEmployerTaxes) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsEmployerTaxesJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsPreTaxDeductions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                        `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsPreTaxDeductionsJSON `json:"-"`
}

// publicPayrollDetailTotalsPreTaxDeductionsJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsPreTaxDeductions]
type publicPayrollDetailTotalsPreTaxDeductionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsPreTaxDeductions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsPreTaxDeductionsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsPostTaxDeductions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                         `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsPostTaxDeductionsJSON `json:"-"`
}

// publicPayrollDetailTotalsPostTaxDeductionsJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsPostTaxDeductions]
type publicPayrollDetailTotalsPostTaxDeductionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsPostTaxDeductions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsPostTaxDeductionsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsWorkerBenefitContributions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                                  `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsWorkerBenefitContributionsJSON `json:"-"`
}

// publicPayrollDetailTotalsWorkerBenefitContributionsJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsWorkerBenefitContributions]
type publicPayrollDetailTotalsWorkerBenefitContributionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsWorkerBenefitContributions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsWorkerBenefitContributionsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsEmployerBenefitContributions struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                                    `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsEmployerBenefitContributionsJSON `json:"-"`
}

// publicPayrollDetailTotalsEmployerBenefitContributionsJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsEmployerBenefitContributions]
type publicPayrollDetailTotalsEmployerBenefitContributionsJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsEmployerBenefitContributions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsEmployerBenefitContributionsJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsTransactionFees struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                       `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsTransactionFeesJSON `json:"-"`
}

// publicPayrollDetailTotalsTransactionFeesJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsTransactionFees]
type publicPayrollDetailTotalsTransactionFeesJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsTransactionFees) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsTransactionFeesJSON) RawJSON() string {
	return r.raw
}

type PublicPayrollDetailTotalsTotalCost struct {
	// The amount in ISO 4217 minor units. For USD, 300000 represents $3,000.00.
	Amount int64 `json:"amount" api:"required"`
	// The server-formatted display string for the amount in its currency.
	Display string                                 `json:"display" api:"required"`
	JSON    publicPayrollDetailTotalsTotalCostJSON `json:"-"`
}

// publicPayrollDetailTotalsTotalCostJSON contains the JSON metadata for the struct [PublicPayrollDetailTotalsTotalCost]
type publicPayrollDetailTotalsTotalCostJSON struct {
	Amount      apijson.Field
	Display     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PublicPayrollDetailTotalsTotalCost) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r publicPayrollDetailTotalsTotalCostJSON) RawJSON() string {
	return r.raw
}
