// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warpgosdk

import (
	"context"
	"net/http"
	"net/url"
	"slices"

	"github.com/marclave/warp-go-sdk/internal/apijson"
	"github.com/marclave/warp-go-sdk/internal/apiquery"
	"github.com/marclave/warp-go-sdk/internal/param"
	"github.com/marclave/warp-go-sdk/internal/requestconfig"
	"github.com/marclave/warp-go-sdk/option"
)

// TimeOffService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewTimeOffService] method instead.
type TimeOffService struct {
	Options []option.RequestOption
	Policies *TimeOffPolicyService
}

// NewTimeOffService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewTimeOffService(opts ...option.RequestOption) (r *TimeOffService) {
	r = &TimeOffService{}
	r.Options = opts
	r.Policies = NewTimeOffPolicyService(opts...)
	return
}

// Time off assignments are mappings between workers and time off policies. Useful for finding out which policies a worker is assigned to, or which workers are assigned to a given policy.
//
// Parameters:
//     ctx: Context for the request.
//     query: TimeOffListAssignmentsParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *TimeOffListAssignmentsResponse: Success
//
// Example:
//
//     timeOff, err := client.TimeOff.ListAssignments(context.Background(), sdk.TimeOffListAssignmentsParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(timeOff)
func (r *TimeOffService) ListAssignments(ctx context.Context, query TimeOffListAssignmentsParams, opts ...option.RequestOption) (res *TimeOffListAssignmentsResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/time_off/assignments"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get worker remaining time-off balances.
//
// Parameters:
//     ctx: Context for the request.
//     query: TimeOffListBalancesParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *TimeOffListBalancesResponse: Success
//
// Example:
//
//     timeOff, err := client.TimeOff.ListBalances(context.Background(), sdk.TimeOffListBalancesParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(timeOff)
func (r *TimeOffService) ListBalances(ctx context.Context, query TimeOffListBalancesParams, opts ...option.RequestOption) (res *TimeOffListBalancesResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/time_off/balances"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Get the time off requests that workers in your company have made.
//
// Parameters:
//     ctx: Context for the request.
//     query: TimeOffListRequestsParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *TimeOffListRequestsResponse: Success
//
// Example:
//
//     timeOff, err := client.TimeOff.ListRequests(context.Background(), sdk.TimeOffListRequestsParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(timeOff)
func (r *TimeOffService) ListRequests(ctx context.Context, query TimeOffListRequestsParams, opts ...option.RequestOption) (res *TimeOffListRequestsResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/time_off/requests"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

type Issue struct {
	// The tag identifying the type of parse issue
	//
	// Any of "Pointer", "Unexpected", "Missing", "Composite", "Refinement",
	// "Transformation", "Type", "Forbidden".
	Tag IssueTag `json:"_tag" api:"required"`
	// The path to the property where the issue occurred
	Path []any `json:"path" api:"required"`
	// A descriptive message explaining the issue
	Message string `json:"message" api:"required"`
	JSON issueJSON `json:"-"`
}

// issueJSON contains the JSON metadata for the struct [Issue]
type issueJSON struct {
	Tag apijson.Field
	Path apijson.Field
	Message apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Issue) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r issueJSON) RawJSON() string {
	return r.raw
}

type IssueTag string

const (
	IssueTagPointer IssueTag = "Pointer"
	IssueTagUnexpected IssueTag = "Unexpected"
	IssueTagMissing IssueTag = "Missing"
	IssueTagComposite IssueTag = "Composite"
	IssueTagRefinement IssueTag = "Refinement"
	IssueTagTransformation IssueTag = "Transformation"
	IssueTagType IssueTag = "Type"
	IssueTagForbidden IssueTag = "Forbidden"
)

func (r IssueTag) IsKnown() bool {
	switch r {
	case IssueTagPointer, IssueTagUnexpected, IssueTagMissing, IssueTagComposite, IssueTagRefinement, IssueTagTransformation, IssueTagType, IssueTagForbidden:
		return true
	}
	return false
}

type MissingRequiredCompanyPermissions struct {
	RequiredPermissions []MissingRequiredCompanyPermissionsRequiredPermission `json:"requiredPermissions" api:"required"`
	Message string `json:"message" api:"required"`
	// Any of "MissingRequiredCompanyPermissions".
	Tag MissingRequiredCompanyPermissionsTag `json:"_tag" api:"required"`
	JSON missingRequiredCompanyPermissionsJSON `json:"-"`
}

// missingRequiredCompanyPermissionsJSON contains the JSON metadata for the struct [MissingRequiredCompanyPermissions]
type missingRequiredCompanyPermissionsJSON struct {
	RequiredPermissions apijson.Field
	Message apijson.Field
	Tag apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MissingRequiredCompanyPermissions) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r missingRequiredCompanyPermissionsJSON) RawJSON() string {
	return r.raw
}

type MissingRequiredCompanyPermissionsTag string

const (
	MissingRequiredCompanyPermissionsTagMissingRequiredCompanyPermissions MissingRequiredCompanyPermissionsTag = "MissingRequiredCompanyPermissions"
)

func (r MissingRequiredCompanyPermissionsTag) IsKnown() bool {
	switch r {
	case MissingRequiredCompanyPermissionsTagMissingRequiredCompanyPermissions:
		return true
	}
	return false
}

type APINotEnabled struct {
	Message string `json:"message" api:"required"`
	// Any of "ApiNotEnabled".
	Tag APINotEnabledTag `json:"_tag" api:"required"`
	JSON apiNotEnabledJSON `json:"-"`
}

// apiNotEnabledJSON contains the JSON metadata for the struct [APINotEnabled]
type apiNotEnabledJSON struct {
	Message apijson.Field
	Tag apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *APINotEnabled) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r apiNotEnabledJSON) RawJSON() string {
	return r.raw
}

type APINotEnabledTag string

const (
	APINotEnabledTagAPINotEnabled APINotEnabledTag = "ApiNotEnabled"
)

func (r APINotEnabledTag) IsKnown() bool {
	switch r {
	case APINotEnabledTagAPINotEnabled:
		return true
	}
	return false
}

type TimeOffListAssignmentsResponse struct {
	Issues []Issue `json:"issues" api:"required"`
	Message string `json:"message" api:"required"`
	// Any of "HttpApiDecodeError".
	Tag TimeOffListAssignmentsResponseTag `json:"_tag" api:"required"`
	JSON timeOffListAssignmentsResponseJSON `json:"-"`
}

// timeOffListAssignmentsResponseJSON contains the JSON metadata for the struct [TimeOffListAssignmentsResponse]
type timeOffListAssignmentsResponseJSON struct {
	Issues apijson.Field
	Message apijson.Field
	Tag apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffListAssignmentsResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListAssignmentsResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffListAssignmentsResponseTag string

const (
	TimeOffListAssignmentsResponseTagHTTPAPIDecodeError TimeOffListAssignmentsResponseTag = "HttpApiDecodeError"
)

func (r TimeOffListAssignmentsResponseTag) IsKnown() bool {
	switch r {
	case TimeOffListAssignmentsResponseTagHTTPAPIDecodeError:
		return true
	}
	return false
}

type TimeOffListBalancesResponse struct {
	Issues []Issue `json:"issues" api:"required"`
	Message string `json:"message" api:"required"`
	// Any of "HttpApiDecodeError".
	Tag TimeOffListBalancesResponseTag `json:"_tag" api:"required"`
	JSON timeOffListBalancesResponseJSON `json:"-"`
}

// timeOffListBalancesResponseJSON contains the JSON metadata for the struct [TimeOffListBalancesResponse]
type timeOffListBalancesResponseJSON struct {
	Issues apijson.Field
	Message apijson.Field
	Tag apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffListBalancesResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListBalancesResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffListBalancesResponseTag string

const (
	TimeOffListBalancesResponseTagHTTPAPIDecodeError TimeOffListBalancesResponseTag = "HttpApiDecodeError"
)

func (r TimeOffListBalancesResponseTag) IsKnown() bool {
	switch r {
	case TimeOffListBalancesResponseTagHTTPAPIDecodeError:
		return true
	}
	return false
}

type TimeOffListRequestsResponse struct {
	Issues []Issue `json:"issues" api:"required"`
	Message string `json:"message" api:"required"`
	// Any of "HttpApiDecodeError".
	Tag TimeOffListRequestsResponseTag `json:"_tag" api:"required"`
	JSON timeOffListRequestsResponseJSON `json:"-"`
}

// timeOffListRequestsResponseJSON contains the JSON metadata for the struct [TimeOffListRequestsResponse]
type timeOffListRequestsResponseJSON struct {
	Issues apijson.Field
	Message apijson.Field
	Tag apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TimeOffListRequestsResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r timeOffListRequestsResponseJSON) RawJSON() string {
	return r.raw
}

type TimeOffListRequestsResponseTag string

const (
	TimeOffListRequestsResponseTagHTTPAPIDecodeError TimeOffListRequestsResponseTag = "HttpApiDecodeError"
)

func (r TimeOffListRequestsResponseTag) IsKnown() bool {
	switch r {
	case TimeOffListRequestsResponseTagHTTPAPIDecodeError:
		return true
	}
	return false
}

type TimeOffListAssignmentsParams struct {
	AfterID param.Field[string] `query:"afterId"`
	BeforeID param.Field[string] `query:"beforeId"`
	// a number less than or equal to 100
	Limit param.Field[string] `query:"limit"`
	PolicyIDs param.Field[[]string] `query:"policyIds"`
	WorkerIDs param.Field[[]string] `query:"workerIds"`
}

// URLQuery serializes [TimeOffListAssignmentsParams]'s query parameters as `url.Values`.
func (r TimeOffListAssignmentsParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type TimeOffListBalancesParams struct {
	AfterID param.Field[string] `query:"afterId"`
	BeforeID param.Field[string] `query:"beforeId"`
	// a string to be decoded into a Date
	EndDate param.Field[string] `query:"endDate"`
	// a number less than or equal to 100
	Limit param.Field[string] `query:"limit"`
	PolicyIDs param.Field[[]string] `query:"policyIds"`
	// a string to be decoded into a Date
	StartDate param.Field[string] `query:"startDate"`
	WorkerIDs param.Field[[]string] `query:"workerIds"`
}

// URLQuery serializes [TimeOffListBalancesParams]'s query parameters as `url.Values`.
func (r TimeOffListBalancesParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type TimeOffListRequestsParams struct {
	AfterID param.Field[string] `query:"afterId"`
	BeforeID param.Field[string] `query:"beforeId"`
	// a string to be decoded into a Date
	EndsBefore param.Field[string] `query:"endsBefore"`
	// a string to be decoded into a Date
	EndsOnOrAfter param.Field[string] `query:"endsOnOrAfter"`
	// a number less than or equal to 100
	Limit param.Field[string] `query:"limit"`
	PolicyIDs param.Field[[]string] `query:"policyIds"`
	// a string to be decoded into a Date
	StartsBefore param.Field[string] `query:"startsBefore"`
	// a string to be decoded into a Date
	StartsOnOrAfter param.Field[string] `query:"startsOnOrAfter"`
	// Any of "pending", "approved", "denied".
	Statuses param.Field[[]string] `query:"statuses"`
	WorkerIDs param.Field[[]string] `query:"workerIds"`
}

// URLQuery serializes [TimeOffListRequestsParams]'s query parameters as `url.Values`.
func (r TimeOffListRequestsParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type MissingRequiredCompanyPermissionsRequiredPermission struct {
	// Any of "workers:profile", "workers:global:compensation",
	// "workers:us:compensation", "workers:compliance", "workers:pii",
	// "workers:banking", "workers:access", "workers:dependents",
	// "workers:dependents:pii", "payrolls:global", "payrolls:us", "pay_schedules",
	// "offers", "departments", "workplaces", "time_off", "time_tracking", "expenses",
	// "general_ledger", "benefits", "tax_compliance", "kyb", "mdm", "lms",
	// "authorized_users", "billing", "settings", "developer".
	Scope MissingRequiredCompanyPermissionsRequiredPermissionScope `json:"scope" api:"required"`
	// Any of "read", "write", "manage".
	Level MissingRequiredCompanyPermissionsRequiredPermissionLevel `json:"level" api:"required"`
	JSON missingRequiredCompanyPermissionsRequiredPermissionJSON `json:"-"`
}

// missingRequiredCompanyPermissionsRequiredPermissionJSON contains the JSON metadata for the struct [MissingRequiredCompanyPermissionsRequiredPermission]
type missingRequiredCompanyPermissionsRequiredPermissionJSON struct {
	Scope apijson.Field
	Level apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MissingRequiredCompanyPermissionsRequiredPermission) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r missingRequiredCompanyPermissionsRequiredPermissionJSON) RawJSON() string {
	return r.raw
}

type MissingRequiredCompanyPermissionsRequiredPermissionScope string

const (
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersProfile MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:profile"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersGlobalCompensation MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:global:compensation"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersUsCompensation MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:us:compensation"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersCompliance MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:compliance"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersPii MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:pii"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersBanking MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:banking"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersAccess MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:access"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersDependents MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:dependents"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersDependentsPii MissingRequiredCompanyPermissionsRequiredPermissionScope = "workers:dependents:pii"
	MissingRequiredCompanyPermissionsRequiredPermissionScopePayrollsGlobal MissingRequiredCompanyPermissionsRequiredPermissionScope = "payrolls:global"
	MissingRequiredCompanyPermissionsRequiredPermissionScopePayrollsUs MissingRequiredCompanyPermissionsRequiredPermissionScope = "payrolls:us"
	MissingRequiredCompanyPermissionsRequiredPermissionScopePaySchedules MissingRequiredCompanyPermissionsRequiredPermissionScope = "pay_schedules"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeOffers MissingRequiredCompanyPermissionsRequiredPermissionScope = "offers"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeDepartments MissingRequiredCompanyPermissionsRequiredPermissionScope = "departments"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkplaces MissingRequiredCompanyPermissionsRequiredPermissionScope = "workplaces"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeTimeOff MissingRequiredCompanyPermissionsRequiredPermissionScope = "time_off"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeTimeTracking MissingRequiredCompanyPermissionsRequiredPermissionScope = "time_tracking"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeExpenses MissingRequiredCompanyPermissionsRequiredPermissionScope = "expenses"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeGeneralLedger MissingRequiredCompanyPermissionsRequiredPermissionScope = "general_ledger"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeBenefits MissingRequiredCompanyPermissionsRequiredPermissionScope = "benefits"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeTaxCompliance MissingRequiredCompanyPermissionsRequiredPermissionScope = "tax_compliance"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeKYB MissingRequiredCompanyPermissionsRequiredPermissionScope = "kyb"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeMdm MissingRequiredCompanyPermissionsRequiredPermissionScope = "mdm"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeLms MissingRequiredCompanyPermissionsRequiredPermissionScope = "lms"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeAuthorizedUsers MissingRequiredCompanyPermissionsRequiredPermissionScope = "authorized_users"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeBilling MissingRequiredCompanyPermissionsRequiredPermissionScope = "billing"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeSettings MissingRequiredCompanyPermissionsRequiredPermissionScope = "settings"
	MissingRequiredCompanyPermissionsRequiredPermissionScopeDeveloper MissingRequiredCompanyPermissionsRequiredPermissionScope = "developer"
)

func (r MissingRequiredCompanyPermissionsRequiredPermissionScope) IsKnown() bool {
	switch r {
	case MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersProfile, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersGlobalCompensation, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersUsCompensation, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersCompliance, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersPii, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersBanking, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersAccess, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersDependents, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkersDependentsPii, MissingRequiredCompanyPermissionsRequiredPermissionScopePayrollsGlobal, MissingRequiredCompanyPermissionsRequiredPermissionScopePayrollsUs, MissingRequiredCompanyPermissionsRequiredPermissionScopePaySchedules, MissingRequiredCompanyPermissionsRequiredPermissionScopeOffers, MissingRequiredCompanyPermissionsRequiredPermissionScopeDepartments, MissingRequiredCompanyPermissionsRequiredPermissionScopeWorkplaces, MissingRequiredCompanyPermissionsRequiredPermissionScopeTimeOff, MissingRequiredCompanyPermissionsRequiredPermissionScopeTimeTracking, MissingRequiredCompanyPermissionsRequiredPermissionScopeExpenses, MissingRequiredCompanyPermissionsRequiredPermissionScopeGeneralLedger, MissingRequiredCompanyPermissionsRequiredPermissionScopeBenefits, MissingRequiredCompanyPermissionsRequiredPermissionScopeTaxCompliance, MissingRequiredCompanyPermissionsRequiredPermissionScopeKYB, MissingRequiredCompanyPermissionsRequiredPermissionScopeMdm, MissingRequiredCompanyPermissionsRequiredPermissionScopeLms, MissingRequiredCompanyPermissionsRequiredPermissionScopeAuthorizedUsers, MissingRequiredCompanyPermissionsRequiredPermissionScopeBilling, MissingRequiredCompanyPermissionsRequiredPermissionScopeSettings, MissingRequiredCompanyPermissionsRequiredPermissionScopeDeveloper:
		return true
	}
	return false
}

type MissingRequiredCompanyPermissionsRequiredPermissionLevel string

const (
	MissingRequiredCompanyPermissionsRequiredPermissionLevelRead MissingRequiredCompanyPermissionsRequiredPermissionLevel = "read"
	MissingRequiredCompanyPermissionsRequiredPermissionLevelWrite MissingRequiredCompanyPermissionsRequiredPermissionLevel = "write"
	MissingRequiredCompanyPermissionsRequiredPermissionLevelManage MissingRequiredCompanyPermissionsRequiredPermissionLevel = "manage"
)

func (r MissingRequiredCompanyPermissionsRequiredPermissionLevel) IsKnown() bool {
	switch r {
	case MissingRequiredCompanyPermissionsRequiredPermissionLevelRead, MissingRequiredCompanyPermissionsRequiredPermissionLevelWrite, MissingRequiredCompanyPermissionsRequiredPermissionLevelManage:
		return true
	}
	return false
}
