// Code generated by Scalar SDK Generator. DO NOT EDIT.

package warphr

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/TeamWarp/warp-go-sdk/internal/apijson"
	"github.com/TeamWarp/warp-go-sdk/internal/apiquery"
	"github.com/TeamWarp/warp-go-sdk/internal/param"
	"github.com/TeamWarp/warp-go-sdk/internal/requestconfig"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// WorkplaceService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewWorkplaceService] method instead.
type WorkplaceService struct {
	Options []option.RequestOption
}

// NewWorkplaceService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewWorkplaceService(opts ...option.RequestOption) (r *WorkplaceService) {
	r = &WorkplaceService{}
	r.Options = opts
	return
}

// List all workplaces for your company.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: WorkplaceListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*WorkplaceListResponse: Success
//
// Example:
//
//	workplace, err := client.Workplaces.List(context.Background(), sdk.WorkplaceListParams{
//		Limit: sdk.F[string]("limit"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(workplace)
func (r *WorkplaceService) List(ctx context.Context, query WorkplaceListParams, opts ...option.RequestOption) (res *WorkplaceListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/workplaces"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Create a new workplace.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: WorkplaceNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*WorkplaceNewResponse: Success
//
// Example:
//
//	workplace, err := client.Workplaces.New(context.Background(), sdk.WorkplaceNewParams{
//		Address: sdk.F[sdk.Objects11Param](sdk.Objects11Param{
//			Line1:      sdk.F[interface{}](map[string]interface{}{}),
//			City:       sdk.F[string](""),
//			PostalCode: sdk.F[string](""),
//		}),
//		Name: sdk.F[interface{}](map[string]interface{}{}),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(workplace)
func (r *WorkplaceService) New(ctx context.Context, body WorkplaceNewParams, opts ...option.RequestOption) (res *WorkplaceNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/workplaces"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Update an existing workplace.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Path parameter.
//	body: WorkplaceUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*WorkplaceUpdateResponse: Success
//
// Example:
//
//	workplace, err := client.Workplaces.Update(context.Background(), "id", sdk.WorkplaceUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(workplace)
func (r *WorkplaceService) Update(ctx context.Context, id string, body WorkplaceUpdateParams, opts ...option.RequestOption) (res *WorkplaceUpdateResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/workplaces/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

type Objects11 struct {
	Line1      string           `json:"line1" api:"required"`
	City       string           `json:"city" api:"required"`
	PostalCode string           `json:"postalCode" api:"required"`
	State      Objects11State   `json:"state" api:"required"`
	Country    Objects11Country `json:"country" api:"required"`
	Line2      string           `json:"line2" api:"nullable"`
	JSON       objects11JSON    `json:"-"`
}

// objects11JSON contains the JSON metadata for the struct [Objects11]
type objects11JSON struct {
	Line1       apijson.Field
	City        apijson.Field
	PostalCode  apijson.Field
	State       apijson.Field
	Country     apijson.Field
	Line2       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Objects11) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r objects11JSON) RawJSON() string {
	return r.raw
}

type Objects11Param struct {
	City       param.Field[string]           `json:"city" api:"required"`
	Country    param.Field[Objects11Country] `json:"country" api:"required"`
	Line1      param.Field[string]           `json:"line1" api:"required"`
	PostalCode param.Field[string]           `json:"postalCode" api:"required"`
	State      param.Field[Objects11State]   `json:"state" api:"required"`
	Line2      param.Field[string]           `json:"line2"`
}

func (r Objects11Param) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type Objects11State string

const (
	Objects11StateAl Objects11State = "AL"
	Objects11StateAk Objects11State = "AK"
	Objects11StateAz Objects11State = "AZ"
	Objects11StateAr Objects11State = "AR"
	Objects11StateCa Objects11State = "CA"
	Objects11StateCo Objects11State = "CO"
	Objects11StateCt Objects11State = "CT"
	Objects11StateDc Objects11State = "DC"
	Objects11StateDe Objects11State = "DE"
	Objects11StateFl Objects11State = "FL"
	Objects11StateGa Objects11State = "GA"
	Objects11StateHi Objects11State = "HI"
	Objects11StateID Objects11State = "ID"
	Objects11StateIl Objects11State = "IL"
	Objects11StateIn Objects11State = "IN"
	Objects11StateIa Objects11State = "IA"
	Objects11StateKs Objects11State = "KS"
	Objects11StateKy Objects11State = "KY"
	Objects11StateLa Objects11State = "LA"
	Objects11StateMe Objects11State = "ME"
	Objects11StateMd Objects11State = "MD"
	Objects11StateMa Objects11State = "MA"
	Objects11StateMi Objects11State = "MI"
	Objects11StateMn Objects11State = "MN"
	Objects11StateMs Objects11State = "MS"
	Objects11StateMo Objects11State = "MO"
	Objects11StateMt Objects11State = "MT"
	Objects11StateNe Objects11State = "NE"
	Objects11StateNv Objects11State = "NV"
	Objects11StateNh Objects11State = "NH"
	Objects11StateNj Objects11State = "NJ"
	Objects11StateNm Objects11State = "NM"
	Objects11StateNy Objects11State = "NY"
	Objects11StateNc Objects11State = "NC"
	Objects11StateNd Objects11State = "ND"
	Objects11StateOh Objects11State = "OH"
	Objects11StateOk Objects11State = "OK"
	Objects11StateOr Objects11State = "OR"
	Objects11StatePa Objects11State = "PA"
	Objects11StateRi Objects11State = "RI"
	Objects11StateSc Objects11State = "SC"
	Objects11StateSd Objects11State = "SD"
	Objects11StateTn Objects11State = "TN"
	Objects11StateTx Objects11State = "TX"
	Objects11StateUt Objects11State = "UT"
	Objects11StateVt Objects11State = "VT"
	Objects11StateVa Objects11State = "VA"
	Objects11StateWa Objects11State = "WA"
	Objects11StateWv Objects11State = "WV"
	Objects11StateWi Objects11State = "WI"
	Objects11StateWy Objects11State = "WY"
)

func (r Objects11State) IsKnown() bool {
	switch r {
	case Objects11StateAl, Objects11StateAk, Objects11StateAz, Objects11StateAr, Objects11StateCa, Objects11StateCo, Objects11StateCt, Objects11StateDc, Objects11StateDe, Objects11StateFl, Objects11StateGa, Objects11StateHi, Objects11StateID, Objects11StateIl, Objects11StateIn, Objects11StateIa, Objects11StateKs, Objects11StateKy, Objects11StateLa, Objects11StateMe, Objects11StateMd, Objects11StateMa, Objects11StateMi, Objects11StateMn, Objects11StateMs, Objects11StateMo, Objects11StateMt, Objects11StateNe, Objects11StateNv, Objects11StateNh, Objects11StateNj, Objects11StateNm, Objects11StateNy, Objects11StateNc, Objects11StateNd, Objects11StateOh, Objects11StateOk, Objects11StateOr, Objects11StatePa, Objects11StateRi, Objects11StateSc, Objects11StateSd, Objects11StateTn, Objects11StateTx, Objects11StateUt, Objects11StateVt, Objects11StateVa, Objects11StateWa, Objects11StateWv, Objects11StateWi, Objects11StateWy:
		return true
	}
	return false
}

type Objects11Country string

const (
	Objects11CountryUs Objects11Country = "US"
)

func (r Objects11Country) IsKnown() bool {
	switch r {
	case Objects11CountryUs:
		return true
	}
	return false
}

type WorkplaceListParams struct {
	Limit    param.Field[string] `query:"limit" api:"required"`
	AfterID  param.Field[string] `query:"afterId"`
	BeforeID param.Field[string] `query:"beforeId"`
}

// URLQuery serializes [WorkplaceListParams]'s query parameters as `url.Values`.
func (r WorkplaceListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type WorkplaceNewParams struct {
	// A valid US address
	Address param.Field[Objects11Param]         `json:"address" api:"required"`
	Name    param.Field[interface{}]            `json:"name" api:"required"`
	Type    param.Field[WorkplaceNewParamsType] `json:"type" api:"required"`
}

func (r WorkplaceNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type WorkplaceNewParamsType string

const (
	WorkplaceNewParamsTypeRemote WorkplaceNewParamsType = "remote"
	WorkplaceNewParamsTypeOffice WorkplaceNewParamsType = "office"
)

func (r WorkplaceNewParamsType) IsKnown() bool {
	switch r {
	case WorkplaceNewParamsTypeRemote, WorkplaceNewParamsTypeOffice:
		return true
	}
	return false
}

type WorkplaceUpdateParams struct {
	Name param.Field[string] `json:"name"`
}

func (r WorkplaceUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type WorkplaceListResponse struct {
	HasMore bool                        `json:"hasMore" api:"required"`
	Count   int64                       `json:"count" api:"required"`
	Data    []WorkplaceListResponseData `json:"data" api:"required"`
	JSON    workplaceListResponseJSON   `json:"-"`
}

// workplaceListResponseJSON contains the JSON metadata for the struct [WorkplaceListResponse]
type workplaceListResponseJSON struct {
	HasMore     apijson.Field
	Count       apijson.Field
	Data        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *WorkplaceListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r workplaceListResponseJSON) RawJSON() string {
	return r.raw
}

type WorkplaceNewResponse struct {
	ID     string  `json:"id" api:"required"`
	Name   string  `json:"name" api:"required"`
	Type   Union34 `json:"type" api:"required"`
	Status Union35 `json:"status" api:"required"`
	// A valid US address
	Address   Objects11                `json:"address" api:"required"`
	CreatedAt string                   `json:"createdAt" api:"required"`
	JSON      workplaceNewResponseJSON `json:"-"`
}

// workplaceNewResponseJSON contains the JSON metadata for the struct [WorkplaceNewResponse]
type workplaceNewResponseJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	Type        apijson.Field
	Status      apijson.Field
	Address     apijson.Field
	CreatedAt   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *WorkplaceNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r workplaceNewResponseJSON) RawJSON() string {
	return r.raw
}

type WorkplaceUpdateResponse struct {
	ID     string  `json:"id" api:"required"`
	Name   string  `json:"name" api:"required"`
	Type   Union34 `json:"type" api:"required"`
	Status Union35 `json:"status" api:"required"`
	// A valid US address
	Address   Objects11                   `json:"address" api:"required"`
	CreatedAt string                      `json:"createdAt" api:"required"`
	JSON      workplaceUpdateResponseJSON `json:"-"`
}

// workplaceUpdateResponseJSON contains the JSON metadata for the struct [WorkplaceUpdateResponse]
type workplaceUpdateResponseJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	Type        apijson.Field
	Status      apijson.Field
	Address     apijson.Field
	CreatedAt   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *WorkplaceUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r workplaceUpdateResponseJSON) RawJSON() string {
	return r.raw
}

type WorkplaceListResponseData struct {
	ID     string  `json:"id" api:"required"`
	Name   string  `json:"name" api:"required"`
	Type   Union34 `json:"type" api:"required"`
	Status Union35 `json:"status" api:"required"`
	// A valid US address
	Address   Objects11                     `json:"address" api:"required"`
	CreatedAt string                        `json:"createdAt" api:"required"`
	JSON      workplaceListResponseDataJSON `json:"-"`
}

// workplaceListResponseDataJSON contains the JSON metadata for the struct [WorkplaceListResponseData]
type workplaceListResponseDataJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	Type        apijson.Field
	Status      apijson.Field
	Address     apijson.Field
	CreatedAt   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *WorkplaceListResponseData) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r workplaceListResponseDataJSON) RawJSON() string {
	return r.raw
}
