// Code generated by Scalar SDK Generator. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"sync"
	"time"

	sdk "github.com/TeamWarp/warp-go-sdk"
	"github.com/TeamWarp/warp-go-sdk/option"
)

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `go run tests/smoke-test.go`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
var client = sdk.NewClient(option.WithAPIKey("test"), option.WithHeader("x-api-key", "test"))

type smokeResult struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Status     string `json:"status"`
	DurationMs int64  `json:"durationMs"`
	Error      string `json:"error,omitempty"`
}

type smokeCase struct {
	Operation string
	Method    string
	Path      string
	Run       func()
}

func _smokeCase0() {
	timeOff, err := client.TimeOff.ListAssignments(context.Background(), sdk.TimeOffListAssignmentsParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(timeOff)
}

func _smokeCase1() {
	timeOff, err := client.TimeOff.ListBalances(context.Background(), sdk.TimeOffListBalancesParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(timeOff)
}

func _smokeCase2() {
	timeOff, err := client.TimeOff.ListRequests(context.Background(), sdk.TimeOffListRequestsParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(timeOff)
}

func _smokeCase3() {
	policy, err := client.TimeOff.Policies.List(context.Background(), sdk.TimeOffPolicyListParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(policy)
}

func _smokeCase4() {
	policy, err := client.TimeOff.Policies.Get(context.Background(), "top_1234")
	if err != nil {
		panic(err)
	}
	fmt.Println(policy)
}

func _smokeCase5() {
	worker, err := client.Workers.List(context.Background(), sdk.WorkerListParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(worker)
}

func _smokeCase6() {
	worker, err := client.Workers.Get(context.Background(), "wrk_1234")
	if err != nil {
		panic(err)
	}
	fmt.Println(worker)
}

func _smokeCase7() {
	err := client.Workers.Delete(context.Background(), "wrk_1234")
	if err != nil {
		panic(err)
	}
}

func _smokeCase8() {
	worker, err := client.Workers.NewEmployee(context.Background(), sdk.WorkerNewEmployeeParams{
		Compensation: sdk.F[sdk.WorkerNewEmployeeParamsCompensation](sdk.WorkerNewEmployeeParamsCompensation{
			Amount: sdk.F[float64](0),
		}),
		DepartmentID: sdk.F[string]("dpt_1234"),
		Email: sdk.F[string]("john@joinwarp.com"),
		FirstName: sdk.F[string](""),
		LastName: sdk.F[string](""),
		ManagerID: sdk.F[string]("wrk_1234"),
		Position: sdk.F[string](""),
		StartDate: sdk.F[string]("2000-01-01"),
		WorkLocation: sdk.F[sdk.WorkerNewEmployeeParamsWorkLocationUnion](sdk.WorkerNewEmployeeParamsWorkLocationOfficeWorkLocation{
			WorkplaceID: sdk.F[string]("wkp_1234"),
		}),
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(worker)
}

func _smokeCase9() {
	worker, err := client.Workers.NewContractor(context.Background(), sdk.WorkerNewContractorParams{
		DepartmentID: sdk.F[string]("dpt_1234"),
		Email: sdk.F[string]("john@joinwarp.com"),
		FirstName: sdk.F[string](""),
		LastName: sdk.F[string](""),
		ManagerID: sdk.F[string]("wrk_1234"),
		Position: sdk.F[string](""),
		StartDate: sdk.F[string]("2000-01-01"),
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(worker)
}

func _smokeCase10() {
	worker, err := client.Workers.Invite(context.Background(), "wrk_1234")
	if err != nil {
		panic(err)
	}
	fmt.Println(worker)
}

func _smokeCase11() {
	department, err := client.Departments.List(context.Background(), sdk.DepartmentListParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(department)
}

func _smokeCase12() {
	department, err := client.Departments.New(context.Background(), sdk.DepartmentNewParams{
		Name: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(department)
}

func _smokeCase13() {
	department, err := client.Departments.Update(context.Background(), "dpt_1234", sdk.DepartmentUpdateParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(department)
}

func _smokeCase14() {
	workplace, err := client.Workplaces.List(context.Background(), sdk.WorkplaceListParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(workplace)
}

func _smokeCase15() {
	workplace, err := client.Workplaces.New(context.Background(), sdk.WorkplaceNewParams{
		Address: sdk.F[sdk.WorkplaceNewParamsAddress](sdk.WorkplaceNewParamsAddress{
			Line1: sdk.F[string]("x"),
			City: sdk.F[string](""),
			PostalCode: sdk.F[string](""),
		}),
		Name: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}
	fmt.Println(workplace)
}

func _smokeCase16() {
	workplace, err := client.Workplaces.Update(context.Background(), "wkp_1234", sdk.WorkplaceUpdateParams{})
	if err != nil {
		panic(err)
	}
	fmt.Println(workplace)
}


var cases = []smokeCase{
	{
		Operation: "listAssignments",
		Method:    "GET",
		Path:      "/v1/time_off/assignments",
		Run:       _smokeCase0,
	},

	{
		Operation: "listBalances",
		Method:    "GET",
		Path:      "/v1/time_off/balances",
		Run:       _smokeCase1,
	},

	{
		Operation: "listRequests",
		Method:    "GET",
		Path:      "/v1/time_off/requests",
		Run:       _smokeCase2,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/time_off/policies",
		Run:       _smokeCase3,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/time_off/policies/{id}",
		Run:       _smokeCase4,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/workers",
		Run:       _smokeCase5,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/workers/{id}",
		Run:       _smokeCase6,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/workers/{id}",
		Run:       _smokeCase7,
	},

	{
		Operation: "createEmployee",
		Method:    "POST",
		Path:      "/v1/workers/employee",
		Run:       _smokeCase8,
	},

	{
		Operation: "createContractor",
		Method:    "POST",
		Path:      "/v1/workers/contractor",
		Run:       _smokeCase9,
	},

	{
		Operation: "invite",
		Method:    "POST",
		Path:      "/v1/workers/{id}/invite",
		Run:       _smokeCase10,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/departments",
		Run:       _smokeCase11,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/departments",
		Run:       _smokeCase12,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/departments/{id}",
		Run:       _smokeCase13,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/workplaces",
		Run:       _smokeCase14,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/workplaces",
		Run:       _smokeCase15,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/workplaces/{id}",
		Run:       _smokeCase16,
	},

}

func selectedCases() []smokeCase {
	filter := os.Getenv("SCALAR_SMOKE_FILTER")
	if filter == "" {
		return cases
	}
	needles := strings.Split(filter, ",")
	selected := make([]smokeCase, 0, len(cases))
	for _, testCase := range cases {
		for _, needle := range needles {
			needle = strings.TrimSpace(needle)
			if needle == "" {
				continue
			}
			if strings.Contains(testCase.Operation, needle) || strings.Contains(testCase.Path, needle) {
				selected = append(selected, testCase)
				break
			}
		}
	}
	return selected
}

func runCase(testCase smokeCase) (result smokeResult) {
	startedAt := time.Now()
	result = smokeResult{
		Operation: testCase.Operation,
		Method:    testCase.Method,
		Path:      testCase.Path,
		Status:    "passed",
	}
	defer func() {
		result.DurationMs = time.Since(startedAt).Milliseconds()
		if recovered := recover(); recovered != nil {
			result.Status = "failed"
			result.Error = fmt.Sprint(recovered)
		}
	}()
	testCase.Run()
	return result
}

func main() {
	selected := selectedCases()
	results := make([]smokeResult, len(selected))
	var wg sync.WaitGroup
	for index, testCase := range selected {
		wg.Add(1)
		go func(index int, testCase smokeCase) {
			defer wg.Done()
			results[index] = runCase(testCase)
		}(index, testCase)
	}
	wg.Wait()

	failed := 0
	for _, result := range results {
		if result.Status == "failed" {
			failed++
		}
	}

	report := map[string]interface{}{"total": len(results), "failed": failed, "results": results}
	if reportPath := os.Getenv("SCALAR_SMOKE_REPORT"); reportPath != "" {
		bytes, err := json.Marshal(report)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(reportPath, bytes, 0o644); err != nil {
			panic(err)
		}
	} else {
		for _, result := range results {
			if result.Status == "passed" {
				fmt.Printf("PASS %s (%s %s) %dms\n", result.Operation, result.Method, result.Path, result.DurationMs)
			} else {
				fmt.Fprintf(os.Stderr, "FAIL %s (%s %s)\n%s\n", result.Operation, result.Method, result.Path, result.Error)
			}
		}
		if len(results) == 0 {
			fmt.Fprintln(os.Stderr, "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing).")
		} else {
			fmt.Printf("\n%d/%d samples passed\n", len(results)-failed, len(results))
		}
	}

	if failed > 0 || len(results) == 0 {
		os.Exit(1)
	}
}
